package nl.noscapect.emergentcraft;

import com.mojang.brigadier.arguments.StringArgumentType;
import nl.noscapect.emergentcraft.actions.OfferedAction;
import nl.noscapect.emergentcraft.brain.BrainDecision;
import nl.noscapect.emergentcraft.perception.PerceptionBuilder;
import nl.noscapect.emergentcraft.perception.PerceptionFrame;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;
import net.minecraft.commands.Commands;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.server.permissions.Permissions;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.npc.villager.Villager;
import net.minecraft.world.level.pathfinder.Path;
import net.minecraft.world.phys.Vec3;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.util.*;

public final class EmergentCraftMod implements ModInitializer {
    public static final String MOD_ID="emergentcraft";
    public static final Logger LOGGER=LoggerFactory.getLogger(MOD_ID);
    private static final long STUCK_TICKS=60, MOVE_TIMEOUT_TICKS=400;
    private static final double ARRIVAL_DISTANCE_SQR=2.25;
    private final AgentRegistry registry=new AgentRegistry();
    private final BrainGateway brain=new BrainGateway();
    private final AgentInventoryStore inventory=new AgentInventoryStore();
    private final PerceptionBuilder perceptions=new PerceptionBuilder(registry,inventory);
    private final Map<UUID,AgentRuntime> runtimes=new HashMap<>();
    private final Set<UUID> unloadedBodyIds=new HashSet<>(), pendingRestores=new HashSet<>();

    @Override public void onInitialize() {
        registerCommands(); ServerLifecycleEvents.SERVER_STARTED.register(this::restoreEmbodiments);
        ServerEntityEvents.ENTITY_LOAD.register(this::onEntityLoad); ServerEntityEvents.ENTITY_UNLOAD.register(this::onEntityUnload);
        ServerTickEvents.END_SERVER_TICK.register(this::tick); LOGGER.info("[EmergentCraft] Chunk-safe embodiment restoration initialized.");
    }

    private void registerCommands() {
        CommandRegistrationCallback.EVENT.register((dispatcher,context,environment)->dispatcher.register(Commands.literal("ec").requires(s->s.permissions().hasPermission(Permissions.COMMANDS_GAMEMASTER))
            .then(Commands.literal("spawn").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ String name=StringArgumentType.getString(c,"name"); AgentRecord r=registry.get(name).orElseGet(()->registry.create(name)); BodyResolution body=resolveBody(c.getSource().getServer(),r); if(body.state()==BodyState.UNLOADED) { c.getSource().sendFailure(Component.literal(name+" already has an unloaded body; load its chunk or use /ec repairbody after loading it.")); return 0; } if(body.loadedEntity().isPresent()) { c.getSource().sendSuccess(()->Component.literal(name+" already has body="+body.state()),false); return 1; } spawn(r,c.getSource().getServer(),c.getSource().getPlayerOrException()); c.getSource().sendSuccess(()->Component.literal("EmergentCraft inhabitant "+name+" embodied."),false); return 1; })))
            .then(Commands.literal("list").executes(c->{ c.getSource().sendSuccess(()->Component.literal(registry.all().stream().map(r->r.name()+" ["+(r.alive()?"alive":"dead")+"]").reduce("Inhabitants: ",(a,b)->a+" "+b)),false); return 1; }))
            .then(Commands.literal("inspect").then(Commands.argument("name",StringArgumentType.word()).executes(c->{
                String name=StringArgumentType.getString(c,"name"); Optional<AgentRecord> found=registry.get(name);
                if(found.isEmpty()) { List<Villager> orphans=findOrphanedVanillaBodies(c.getSource().getServer(),name); if(orphans.size()==1) { Villager orphan=orphans.getFirst(); c.getSource().sendSuccess(()->Component.literal(name+" registered=false body=ORPHANED_VANILLA loaded=Villager/"+orphan.getUUID()+"; use /ec remove "+name+" to remove all matching orphaned bodies."),false); return 1; } if(orphans.size()>1) { c.getSource().sendFailure(Component.literal(name+" has "+orphans.size()+" matching unregistered vanilla Villagers: "+orphanIds(orphans)+". Use /ec remove "+name+" to remove all of them, or /ec removeorphan "+name+" <uuid> to choose one.")); return 0; } c.getSource().sendFailure(Component.literal("Unknown inhabitant: "+name)); return 0; }
                AgentRecord r=found.get(); BodyResolution body=resolveBody(c.getSource().getServer(),r); String loaded=body.loadedEntity().map(e->e.getClass().getSimpleName()+"/"+e.getUUID()).orElse("none"); String action=runtime(r).move==null?"none":runtime(r).move.actionId(); c.getSource().sendSuccess(()->Component.literal(r.name()+" alive="+r.alive()+" paused="+r.paused()+" runtime="+runtime(r).describeState()+" activeMove="+action+" body="+body.state()+" embodimentId="+r.embodimentId()+" loaded="+loaded),false); return 1;
            })))
            .then(Commands.literal("perceive").then(Commands.argument("name",StringArgumentType.word()).executes(c->perceive(c,false)).then(Commands.literal("full").executes(c->perceive(c,true)))))
            .then(Commands.literal("actions").then(Commands.argument("name",StringArgumentType.word()).executes(this::showActions)))
            .then(Commands.literal("pause").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord r=require(StringArgumentType.getString(c,"name")); cancelRuntime(c.getSource().getServer(),r); registry.put(r.withPaused(true)); return 1; })))
            .then(Commands.literal("resume").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord r=require(StringArgumentType.getString(c,"name")); registry.put(r.withPaused(false)); return 1; })))
            .then(Commands.literal("repairbody").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord r=require(StringArgumentType.getString(c,"name")); return repairBody(c.getSource().getServer(),c.getSource().getPlayerOrException(),r,c); })))
            .then(Commands.literal("movetest").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord r=require(StringArgumentType.getString(c,"name")); BodyResolution resolution=resolveBody(c.getSource().getServer(),r); if(!resolution.isControlled()) { c.getSource().sendFailure(Component.literal(r.name()+" movement test failed: "+bodyFailure(resolution.state()))); return 0; } cancelRuntime(c.getSource().getServer(),r); GoalLessVillager body=(GoalLessVillager)resolution.entity(); AgentRuntime runtime=runtime(r); runtime.lifecycle.beginAdminActionForcefully(); Optional<Vec3> target=findReachableTestTarget(body); if(target.isEmpty()||!startMove(r,body,runtime,"movetest",r.epoch(),target.get(),true)) { runtime.lifecycle.finishAction(); c.getSource().sendFailure(Component.literal(r.name()+" movement test failed: no path")); return 0; } c.getSource().sendSuccess(()->Component.literal(r.name()+" movement test started"),false); return 1; })))
            .then(Commands.literal("remove").then(Commands.argument("name",StringArgumentType.word()).executes(c->{
                String name=StringArgumentType.getString(c,"name"); Optional<AgentRecord> found=registry.get(name);
                List<Villager> orphans=findOrphanedVanillaBodies(c.getSource().getServer(),name);
                if(found.isPresent()) { AgentRecord r=found.get(); BodyResolution body=resolveBody(c.getSource().getServer(),r); if(body.state()==BodyState.UNLOADED) { c.getSource().sendFailure(Component.literal(name+" has an unloaded registered body; load its chunk before removing all matching bodies.")); return 0; } cancelRuntime(c.getSource().getServer(),r); body.loadedEntity().ifPresent(Entity::discard); runtimes.remove(r.id()); registry.remove(name); }
                for(Villager orphan:orphans) orphan.discard();
                if(found.isEmpty()&&orphans.isEmpty()) { c.getSource().sendFailure(Component.literal("No registered or loaded orphaned Villager named "+name+" was found.")); return 0; }
                int orphanCount=orphans.size(); c.getSource().sendSuccess(()->Component.literal("Removed "+name+(found.isPresent()?" and its registry identity":"")+"; removed "+orphanCount+" matching orphaned body/bodies."),false); return 1;
            })))
            .then(Commands.literal("removeorphan").then(Commands.argument("name",StringArgumentType.word()).executes(c->{
                String name=StringArgumentType.getString(c,"name"); List<Villager> orphans=findOrphanedVanillaBodies(c.getSource().getServer(),name);
                if(orphans.isEmpty()) { c.getSource().sendFailure(Component.literal("No loaded unregistered vanilla Villager named "+name+" was found.")); return 0; }
                if(orphans.size()>1) { c.getSource().sendFailure(Component.literal("Found "+orphans.size()+" matching unregistered vanilla Villagers named "+name+": "+orphanIds(orphans)+". Use /ec removeorphan "+name+" <uuid> to choose one.")); return 0; }
                Villager orphan=orphans.getFirst(); orphan.discard(); c.getSource().sendSuccess(()->Component.literal("Removed orphaned vanilla Villager "+name+" ("+orphan.getUUID()+")."),false); return 1;
            }).then(Commands.argument("uuid",StringArgumentType.word()).executes(c->{
                String name=StringArgumentType.getString(c,"name"), rawId=StringArgumentType.getString(c,"uuid"); UUID id;
                try { id=UUID.fromString(rawId); } catch(IllegalArgumentException ignored) { c.getSource().sendFailure(Component.literal("Invalid UUID: "+rawId)); return 0; }
                List<Villager> matches=findOrphanedVanillaBodies(c.getSource().getServer(),name).stream().filter(v->v.getUUID().equals(id)).toList();
                if(matches.size()!=1) { c.getSource().sendFailure(Component.literal("No loaded unregistered vanilla Villager named "+name+" has UUID "+id+".")); return 0; }
                Villager orphan=matches.getFirst(); orphan.discard(); c.getSource().sendSuccess(()->Component.literal("Removed orphaned vanilla Villager "+name+" ("+id+")."),false); return 1;
            }))))
            .then(Commands.literal("revive").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord old=require(StringArgumentType.getString(c,"name")); cancelRuntime(c.getSource().getServer(),old); AgentRecord r=old.alive()?old:new AgentRecord(old.id(),old.name(),old.createdAt(),true,false,null,old.epoch()+1); registry.put(r); spawn(r,c.getSource().getServer(),c.getSource().getPlayerOrException()); return 1; })))
            .then(Commands.literal("brainstatus").executes(c->{ c.getSource().sendSuccess(()->Component.literal("Brain endpoint: "+System.getProperty("emergentcraft.brainUrl","http://127.0.0.1:3847")),false); return 1; }))));
    }

    private AgentRecord require(String name) { return registry.get(name).orElseThrow(()->new IllegalArgumentException("Unknown inhabitant: "+name)); }
    private int perceive(com.mojang.brigadier.context.CommandContext<net.minecraft.commands.CommandSourceStack> context,boolean full) { String name=StringArgumentType.getString(context,"name"); Optional<AgentRecord> found=registry.get(name); if(found.isEmpty()) { context.getSource().sendFailure(Component.literal("Unknown inhabitant: "+name)); return 0; } BodyResolution resolution=resolveBody(context.getSource().getServer(),found.get()); if(!resolution.isControlled()) { context.getSource().sendFailure(Component.literal(name+" cannot perceive: "+bodyFailure(resolution.state()))); return 0; } PerceptionFrame frame=perceptions.build(found.get(),(GoalLessVillager)resolution.entity(),runtime(found.get()).recent()); var perception=frame.perception(); context.getSource().sendSuccess(()->Component.literal(name+" perception: health "+perception.self().health()+"/"+perception.self().maxHealth()+", biome "+perception.environment().biome()+", visible entities "+perception.entities().size()+", visible blocks "+perception.blocks().size()+", dropped items "+perception.items().size()+", legal actions "+perception.candidates().size()),false); if(full) LOGGER.info("[EmergentCraft] {} perception: {}",name,new com.google.gson.Gson().toJson(perception)); return 1; }
    private int showActions(com.mojang.brigadier.context.CommandContext<net.minecraft.commands.CommandSourceStack> context) { String name=StringArgumentType.getString(context,"name"); Optional<AgentRecord> found=registry.get(name); if(found.isEmpty()) { context.getSource().sendFailure(Component.literal("Unknown inhabitant: "+name)); return 0; } BodyResolution resolution=resolveBody(context.getSource().getServer(),found.get()); if(!resolution.isControlled()) { context.getSource().sendFailure(Component.literal(name+" cannot generate actions: "+bodyFailure(resolution.state()))); return 0; } PerceptionFrame frame=perceptions.build(found.get(),(GoalLessVillager)resolution.entity(),runtime(found.get()).recent()); String summary=frame.perception().candidates().stream().map(candidate->candidate.kind()).distinct().reduce((a,b)->a+", "+b).orElse("none"); context.getSource().sendSuccess(()->Component.literal(name+" legal actions ("+frame.perception().candidates().size()+"): "+summary+". Full list in server log."),false); LOGGER.info("[EmergentCraft] {} actions: {}",name,new com.google.gson.Gson().toJson(frame.perception().candidates())); return 1; }
    private AgentRuntime runtime(AgentRecord r) { return runtimes.computeIfAbsent(r.id(),ignored->new AgentRuntime()); }
    private void spawn(AgentRecord r,MinecraftServer server,ServerPlayer near) { ServerLevel level=(ServerLevel)near.level(); GoalLessVillager body=createBody(r,level,new Vec3(near.getX()+1.5,near.getY(),near.getZ()+1.5),near.getYRot(),near.getXRot(),null,20); if(level.addFreshEntity(body)) { registry.put(r.withEmbodiment(body.getUUID())); unloadedBodyIds.remove(body.getUUID()); } }
    @SuppressWarnings("unchecked") private GoalLessVillager createBody(AgentRecord r,ServerLevel level,Vec3 pos,float yaw,float pitch,Component existingName,float health) { EntityType<?> raw=BuiltInRegistries.ENTITY_TYPE.getValue(Identifier.withDefaultNamespace("villager")); GoalLessVillager body=new GoalLessVillager((EntityType<? extends Villager>)raw,level); body.snapTo(pos.x,pos.y,pos.z,yaw,pitch); body.setCustomName(existingName==null?Component.literal(r.name()):existingName); body.setCustomNameVisible(true); body.removeFreeWill(); body.setNoAi(false); body.setPersistenceRequired(); body.setHealth(Math.min(health,body.getMaxHealth())); return body; }

    private void onEntityLoad(Entity entity,ServerLevel level) { registry.findByEmbodiment(entity.getUUID()).ifPresent(r->{ unloadedBodyIds.remove(entity.getUUID()); if(EmbodimentRestorePolicy.shouldReplace(r.embodimentId(),entity.getUUID(),entity instanceof GoalLessVillager,entity instanceof Villager) && pendingRestores.add(entity.getUUID())) level.getServer().execute(()->{ try { if(!entity.isRemoved()) repairLoadedVillager(r,entity,level); } finally { pendingRestores.remove(entity.getUUID()); } }); }); }
    private void onEntityUnload(Entity entity,ServerLevel level) { registry.findByEmbodiment(entity.getUUID()).ifPresent(r->{ if(entity instanceof GoalLessVillager&& !entity.isAlive()) markDead(level.getServer(),r,"The body died."); else unloadedBodyIds.add(entity.getUUID()); }); }
    private void restoreEmbodiments(MinecraftServer server) { for(AgentRecord r:registry.all()) { if(r.alive()&&r.embodimentId()!=null) unloadedBodyIds.add(r.embodimentId()); BodyResolution body=resolveBody(server,r); if(body.state()==BodyState.VANILLA_NEEDS_RESTORE) repairLoadedVillager(r,body.entity(),(ServerLevel)body.entity().level()); } }
    private boolean repairLoadedVillager(AgentRecord r,Entity entity,ServerLevel level) { if(!(entity instanceof Villager v)||entity.isRemoved()||registry.findByEmbodiment(entity.getUUID()).filter(current->current.id().equals(r.id())).isEmpty()||!EmbodimentRestorePolicy.shouldReplace(r.embodimentId(),entity.getUUID(),entity instanceof GoalLessVillager,true)) return false; GoalLessVillager replacement=createBody(r,level,v.position(),v.getYRot(),v.getXRot(),v.getCustomName(),v.getHealth()); if(!level.addFreshEntity(replacement)) return false; registry.put(r.withEmbodiment(replacement.getUUID())); unloadedBodyIds.remove(entity.getUUID()); unloadedBodyIds.remove(replacement.getUUID()); v.discard(); LOGGER.info("[EmergentCraft] Rewrapped loaded vanilla body for {}",r.name()); return true; }

    private BodyResolution resolveBody(MinecraftServer server,AgentRecord r) { if(!r.alive()) return new BodyResolution(BodyState.DEAD,null); if(r.embodimentId()==null) return new BodyResolution(BodyState.INVALID_REGISTRY,null); Entity entity=findLoadedEntity(server,r.embodimentId()); if(entity==null) return new BodyResolution(unloadedBodyIds.contains(r.embodimentId())?BodyState.UNLOADED:BodyState.MISSING,null); if(entity instanceof GoalLessVillager) return new BodyResolution(BodyState.CONTROLLED,entity); if(entity instanceof Villager) return new BodyResolution(BodyState.VANILLA_NEEDS_RESTORE,entity); return new BodyResolution(BodyState.WRONG_ENTITY,entity); }
    private Entity findLoadedEntity(MinecraftServer server,UUID id) { for(ServerLevel level:server.getAllLevels()) { Entity found=level.getEntity(id); if(found!=null) return found; } return null; }
    private List<Villager> findOrphanedVanillaBodies(MinecraftServer server,String name) { List<Villager> matches=new ArrayList<>(); for(ServerLevel level:server.getAllLevels()) for(Entity entity:level.getAllEntities()) if(entity instanceof Villager villager&&OrphanedBodyPolicy.isExactUnregisteredVanillaVillager(name,villager.getCustomName()==null?null:villager.getCustomName().getString(),registry.findByEmbodiment(villager.getUUID()).isPresent(),villager instanceof GoalLessVillager,true)) matches.add(villager); return matches; }
    private static String orphanIds(List<Villager> orphans) { return orphans.stream().map(villager->villager.getUUID().toString()).toList().toString(); }
    private int repairBody(MinecraftServer server,ServerPlayer player,AgentRecord r,com.mojang.brigadier.context.CommandContext<net.minecraft.commands.CommandSourceStack> context) { BodyResolution body=resolveBody(server,r); if(body.state()==BodyState.CONTROLLED) { context.getSource().sendSuccess(()->Component.literal(r.name()+" body already controlled."),false); return 1; } if(body.state()==BodyState.VANILLA_NEEDS_RESTORE) { boolean repaired=repairLoadedVillager(r,body.entity(),(ServerLevel)body.entity().level()); if(repaired) context.getSource().sendSuccess(()->Component.literal(r.name()+" vanilla body repaired."),false); else context.getSource().sendFailure(Component.literal(r.name()+" body repair could not be completed.")); return repaired?1:0; } if(body.state()==BodyState.UNLOADED) { context.getSource().sendFailure(Component.literal(r.name()+" body chunk is unloaded; load that chunk and automatic repair will run.")); return 0; } if(body.state()==BodyState.MISSING||body.state()==BodyState.INVALID_REGISTRY) { spawn(r,server,player); context.getSource().sendSuccess(()->Component.literal(r.name()+" missing body recreated near you."),false); return 1; } context.getSource().sendFailure(Component.literal(r.name()+" body cannot be repaired: "+body.state())); return 0; }
    private static String bodyFailure(BodyState state) { return switch(state) { case UNLOADED -> "body chunk unloaded; load the chunk first"; case VANILLA_NEEDS_RESTORE -> "vanilla body awaiting restoration"; case MISSING -> "body missing; use /ec repairbody"; case INVALID_REGISTRY -> "invalid body registry; use /ec repairbody"; case WRONG_ENTITY -> "registered UUID belongs to a non-villager entity"; case DEAD -> "inhabitant is dead"; default -> "body unavailable"; }; }

    private void tick(MinecraftServer server) { monitorBodies(server); updateActions(server); if(server.getTickCount()%100!=0) return; for(AgentRecord r:registry.all()) { AgentRuntime runtime=runtime(r); if(!r.alive()||r.paused()||!runtime.lifecycle.canRequestCognition()) continue; BodyResolution body=resolveBody(server,r); if(body.isControlled()) requestDecision(server,r,(GoalLessVillager)body.entity()); } }
    private void monitorBodies(MinecraftServer server) { for(AgentRecord record:registry.all()) { if(!record.alive()) continue; BodyResolution resolution=resolveBody(server,record); if(!resolution.isControlled()) continue; GoalLessVillager body=(GoalLessVillager)resolution.entity(); AgentRuntime runtime=runtime(record); if(!Float.isNaN(runtime.lastHealth)&&body.getHealth()+0.01f<runtime.lastHealth) { String event="Health changed from "+runtime.lastHealth+" to "+body.getHealth()+"."; runtime.event("DAMAGE",event); brain.appendFactualEvent(record.id(),record.epoch(),"DAMAGE",event); } runtime.lastHealth=body.getHealth(); if(!body.isAlive()) markDead(server,record,"The body died."); } }
    private void markDead(MinecraftServer server,AgentRecord record,String event) { AgentRecord latest=registry.get(record.name()).orElse(null); if(latest==null||!latest.alive()) return; cancelRuntime(server,latest); registry.put(new AgentRecord(latest.id(),latest.name(),latest.createdAt(),false,latest.paused(),latest.embodimentId(),latest.epoch()+1)); runtime(latest).event("DEATH",event); brain.appendFactualEvent(latest.id(),latest.epoch(),"DEATH",event); LOGGER.info("[EmergentCraft] {} died",latest.name()); }
    private void requestDecision(MinecraftServer server,AgentRecord stored,GoalLessVillager body) { AgentRecord current=stored.nextEpoch(); AgentRuntime runtime=runtime(current); if(!runtime.lifecycle.beginCognition(current.epoch())) return; registry.put(current); PerceptionFrame frame=perceptions.build(current,body,runtime.recent()); runtime.offeredActions=frame.offeredActions(); LOGGER.info("[EmergentCraft] {} perceived {} entities, {} blocks, {} items and {} actions",current.name(),frame.perception().entities().size(),frame.perception().blocks().size(),frame.perception().items().size(),frame.perception().candidates().size()); brain.decide(frame.perception()).thenAccept(decision->server.execute(()->applyDecision(server,current,decision))); }
    private void applyDecision(MinecraftServer server,AgentRecord current,Optional<BrainDecision> decision) { AgentRuntime runtime=runtime(current); if(!runtime.lifecycle.acceptsDecision(current.epoch())) return; AgentRecord latest=registry.get(current.name()).orElse(null); if(latest==null||latest.epoch()!=current.epoch()||latest.paused()||!latest.alive()||decision.isEmpty()) { runtime.lifecycle.finishCognition(current.epoch()); return; } BodyResolution resolution=resolveBody(server,latest); if(!resolution.isControlled()) { runtime.lifecycle.finishCognition(current.epoch()); return; } BrainDecision selected=decision.get(); OfferedAction action=runtime.offeredActions.get(selected.actionId()); if(action==null) { runtime.lifecycle.finishCognition(current.epoch()); return; } LOGGER.info("[EmergentCraft] {} intent: {}",latest.name(),selected.intent()); GoalLessVillager body=(GoalLessVillager)resolution.entity(); if(action.kind()==OfferedAction.Kind.WAIT) { runtime.lifecycle.finishCognition(current.epoch()); return; } if(action.kind()==OfferedAction.Kind.SPEAK) { speak(server,latest,body,action,selected.speech(),runtime); return; } if(!runtime.lifecycle.beginAction(current.epoch())) return; if(!startOfferedAction(latest,body,runtime,action)) runtime.lifecycle.finishAction(); }
    private boolean startOfferedAction(AgentRecord agent,GoalLessVillager body,AgentRuntime runtime,OfferedAction action) { Vec3 target; if(action.kind()==OfferedAction.Kind.MOVE_TO||action.kind()==OfferedAction.Kind.APPROACH_BLOCK||action.kind()==OfferedAction.Kind.BREAK_BLOCK) { if(action.blockPos()!=null) { var state=body.level().getBlockState(action.blockPos()); if((action.kind()==OfferedAction.Kind.BREAK_BLOCK||action.kind()==OfferedAction.Kind.APPROACH_BLOCK)&&(state.isAir()||!BuiltInRegistries.BLOCK.getKey(state.getBlock()).toString().equals(action.expectedTarget()))) return false; } target=action.destination(); } else { Entity entity=action.entityId()==null?null:findLoadedEntity(((ServerLevel)body.level()).getServer(),action.entityId()); if(entity==null||entity.isRemoved()) return false; if(action.kind()==OfferedAction.Kind.PICK_UP_ITEM) { if(!(entity instanceof net.minecraft.world.entity.item.ItemEntity item)||!BuiltInRegistries.ITEM.getKey(item.getItem().getItem()).toString().equals(action.expectedTarget())) return false; } else if(!BuiltInRegistries.ENTITY_TYPE.getKey(entity.getType()).toString().equals(action.expectedTarget())) return false; target=entity.position(); } runtime.event("ACTION","Attempted "+action.kind()+"."); brain.appendFactualEvent(agent.id(),agent.epoch(),"ACTION","Attempted "+action.kind()+"."); return startMove(agent,body,runtime,action.id(),agent.epoch(),target,false); }
    private void speak(MinecraftServer server,AgentRecord speaker,GoalLessVillager body,OfferedAction action,String speech,AgentRuntime runtime) { Entity target=action.entityId()==null?null:findLoadedEntity(server,action.entityId()); if(target==null||target.isRemoved()||body.distanceToSqr(target)>14*14||speech==null||speech.isBlank()) { runtime.lifecycle.finishCognition(speaker.epoch()); return; } String text=speech.trim(); if(text.length()>240) text=text.substring(0,240); Component message=Component.literal("<"+speaker.name()+"> "+text); for(ServerPlayer player:server.getPlayerList().getPlayers()) if(player.level()==body.level()&&player.distanceToSqr(body)<=14*14) player.sendSystemMessage(message); for(AgentRecord listener:registry.all()) { if(listener.id().equals(speaker.id())||!listener.alive()) continue; BodyResolution listenerBody=resolveBody(server,listener); if(listenerBody.isControlled()&&listenerBody.entity().level()==body.level()&&listenerBody.entity().distanceToSqr(body)<=14*14) { runtime(listener).event("SPEECH","Heard "+speaker.name()+": "+text); brain.appendFactualEvent(listener.id(),listener.epoch(),"SPEECH","Heard "+speaker.name()+": "+text); } } runtime.event("SPEECH","Said: "+text); brain.appendFactualEvent(speaker.id(),speaker.epoch(),"SPEECH","Said: "+text); runtime.lifecycle.finishCognition(speaker.epoch()); }
    private boolean startMove(AgentRecord r,GoalLessVillager body,AgentRuntime runtime,String actionId,long epoch,Vec3 target,boolean diagnostic) { double distance=body.position().distanceTo(target); if(!body.getNavigation().moveTo(target.x,target.y,target.z,0.35)) { finishMove(r,body,runtime,false,"Could not find a path to the destination.",diagnostic); return false; } long tick=((ServerLevel)body.level()).getServer().getTickCount(); runtime.move=new MoveExecution(actionId,epoch,body.position(),target,tick,tick,distance,diagnostic); LOGGER.info("[EmergentCraft] {} started {}",r.name(),diagnostic?"movement test":actionId); return true; }
    private void updateActions(MinecraftServer server) { long tick=server.getTickCount(); for(AgentRecord r:registry.all()) { AgentRuntime runtime=runtime(r); MoveExecution move=runtime.move; if(runtime.lifecycle.state()!=AgentLifecycle.State.EXECUTING_ACTION||move==null) continue; BodyResolution resolution=resolveBody(server,r); if(!resolution.isControlled()) { finishMove(r,null,runtime,false,"Action failed because body is "+resolution.state()+".",move.diagnostic()); continue; } GoalLessVillager body=(GoalLessVillager)resolution.entity(); double distance=body.position().distanceTo(move.target()); if(distance*distance<=ARRIVAL_DISTANCE_SQR) { OfferedAction action=runtime.offeredActions.get(move.actionId()); if(action!=null&&action.kind()==OfferedAction.Kind.BREAK_BLOCK) { if(!finishBreak(r,body,runtime,action,move,tick)) continue; } else if(action!=null&&action.kind()==OfferedAction.Kind.PICK_UP_ITEM) { finishPickup(r,body,runtime,action); } else if(action!=null&&(action.kind()==OfferedAction.Kind.APPROACH_ENTITY||action.kind()==OfferedAction.Kind.APPROACH_BLOCK)) finishApproach(r,body,runtime,action); else finishMove(r,body,runtime,true,"Reached the destination.",move.diagnostic()); continue; } if(body.getNavigation().isDone()) { finishMove(r,body,runtime,false,"Movement path ended before reaching the destination.",move.diagnostic()); continue; } if(tick-move.lastProgressTick()>=STUCK_TICKS) { if(move.lastDistance()-distance>=0.25) runtime.move=move.withProgress(tick,distance); else { finishMove(r,body,runtime,false,"Movement failed because the body became stuck.",move.diagnostic()); continue; } } if(tick-move.startTick()>=MOVE_TIMEOUT_TICKS) finishMove(r,body,runtime,false,"Movement timed out before reaching the destination.",move.diagnostic()); } }
    private void finishApproach(AgentRecord agent,GoalLessVillager body,AgentRuntime runtime,OfferedAction action) { if(action.kind()==OfferedAction.Kind.APPROACH_ENTITY) { Entity target=action.entityId()==null?null:findLoadedEntity(((ServerLevel)body.level()).getServer(),action.entityId()); if(target==null||target.isRemoved()||body.distanceToSqr(target)>9||!BuiltInRegistries.ENTITY_TYPE.getKey(target.getType()).toString().equals(action.expectedTarget())) { finishMove(agent,body,runtime,false,"Target entity was no longer reachable.",false); return; } } else { var state=body.level().getBlockState(action.blockPos()); if(state.isAir()||!BuiltInRegistries.BLOCK.getKey(state.getBlock()).toString().equals(action.expectedTarget())) { finishMove(agent,body,runtime,false,"Target block changed before arrival.",false); return; } } finishMove(agent,body,runtime,true,"Reached the selected target.",false); }
    private boolean finishBreak(AgentRecord agent,GoalLessVillager body,AgentRuntime runtime,OfferedAction action,MoveExecution move,long tick) { if(action.blockPos()==null) { finishMove(agent,body,runtime,false,"Block target was unavailable.",false); return true; } var level=(ServerLevel)body.level(); var state=level.getBlockState(action.blockPos()); boolean exact=!state.isAir()&&BuiltInRegistries.BLOCK.getKey(state.getBlock()).toString().equals(action.expectedTarget()); if(!nl.noscapect.emergentcraft.actions.ActionValidation.canBreak(state.getDestroySpeed(level,action.blockPos()),body.distanceToSqr(Vec3.atCenterOf(action.blockPos())),exact)) { finishMove(agent,body,runtime,false,"Block changed, was unbreakable, or was out of range.",false); return true; } long required=Math.max(8,Math.min(160,(long)Math.ceil((state.getDestroySpeed(level,action.blockPos())+1)*20))); if(tick-move.startTick()<required) return false; boolean broken=level.destroyBlock(action.blockPos(),true,body,512); finishMove(agent,body,runtime,broken,broken?"Broke "+action.expectedTarget()+".":"Minecraft rejected block destruction.",false); return true; }
    private void finishPickup(AgentRecord agent,GoalLessVillager body,AgentRuntime runtime,OfferedAction action) { Entity target=action.entityId()==null?null:findLoadedEntity(((ServerLevel)body.level()).getServer(),action.entityId()); if(!(target instanceof net.minecraft.world.entity.item.ItemEntity item)||item.isRemoved()) { finishMove(agent,body,runtime,false,"Dropped item was no longer available.",false); return; } var stack=item.getItem(); boolean exact=BuiltInRegistries.ITEM.getKey(stack.getItem()).toString().equals(action.expectedTarget()); boolean capacity=inventory.canAccept(agent.id(),action.expectedTarget(),stack.getCount()); if(!nl.noscapect.emergentcraft.actions.ActionValidation.canPickUp(body.distanceToSqr(item),exact,capacity)) { finishMove(agent,body,runtime,false,"Dropped item changed, was out of range, or inventory was full.",false); return; } inventory.add(agent.id(),action.expectedTarget(),stack.getCount()); item.discard(); runtime.event("ACQUISITION","Picked up "+stack.getCount()+" "+action.expectedTarget()+"."); brain.appendFactualEvent(agent.id(),agent.epoch(),"ACQUISITION","Picked up "+stack.getCount()+" "+action.expectedTarget()+"."); finishMove(agent,body,runtime,true,"Picked up "+action.expectedTarget()+".",false); }
    private void finishMove(AgentRecord r,GoalLessVillager body,AgentRuntime runtime,boolean success,String outcome,boolean diagnostic) { if(body!=null) body.getNavigation().stop(); runtime.move=null; runtime.lifecycle.finishAction(); runtime.offeredActions=Map.of(); if(!diagnostic) { runtime.event(success?"OUTCOME":"FAILURE",outcome); brain.appendFactualEvent(r.id(),r.epoch(),"OUTCOME",outcome); } LOGGER.info("[EmergentCraft] {} {} {}: {}",r.name(),diagnostic?"movement test":"action",success?"completed":"failed",outcome); }
    private void cancelRuntime(MinecraftServer server,AgentRecord r) { BodyResolution body=resolveBody(server,r); if(body.isControlled()) ((GoalLessVillager)body.entity()).getNavigation().stop(); AgentRuntime runtime=runtime(r); runtime.move=null; runtime.lifecycle.cancel(); }
    private Optional<Vec3> findReachableTestTarget(GoalLessVillager body) { int[][] offsets={{4,0},{-4,0},{0,4},{0,-4},{3,3},{3,-3},{-3,3},{-3,-3}}; for(int[] o:offsets) { BlockPos candidate=body.blockPosition().offset(o[0],0,o[1]); Path path=body.getNavigation().createPath(candidate,0); if(path!=null&&path.canReach()) { BlockPos end=path.getTarget(); return Optional.of(new Vec3(end.getX()+0.5,end.getY(),end.getZ()+0.5)); } } return Optional.empty(); }
    private static String escape(String value) { return value.replace("\\","\\\\").replace("\"","\\\""); }
}
