package nl.noscapect.emergentcraft;

import com.mojang.brigadier.arguments.StringArgumentType;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;
import net.minecraft.commands.Commands;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.server.permissions.Permissions;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.npc.villager.Villager;
import net.minecraft.world.level.pathfinder.Path;
import net.minecraft.world.phys.Vec3;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.util.*;

public final class EmergentCraftMod implements ModInitializer {
    public static final String MOD_ID="emergentcraft";
    public static final Logger LOGGER=LoggerFactory.getLogger(MOD_ID);
    private static final long STUCK_TICKS=60, MOVE_TIMEOUT_TICKS=400;
    private static final double ARRIVAL_DISTANCE_SQR=2.25;
    private final AgentRegistry registry=new AgentRegistry();
    private final BrainGateway brain=new BrainGateway();
    private final Map<UUID,AgentRuntime> runtimes=new HashMap<>();
    private final Set<UUID> unloadedBodyIds=new HashSet<>(), pendingRestores=new HashSet<>();

    @Override public void onInitialize() {
        registerCommands(); ServerLifecycleEvents.SERVER_STARTED.register(this::restoreEmbodiments);
        ServerEntityEvents.ENTITY_LOAD.register(this::onEntityLoad); ServerEntityEvents.ENTITY_UNLOAD.register(this::onEntityUnload);
        ServerTickEvents.END_SERVER_TICK.register(this::tick); LOGGER.info("[EmergentCraft] Chunk-safe embodiment restoration initialized.");
    }

    private void registerCommands() {
        CommandRegistrationCallback.EVENT.register((dispatcher,context,environment)->dispatcher.register(Commands.literal("ec").requires(s->s.permissions().hasPermission(Permissions.COMMANDS_GAMEMASTER))
            .then(Commands.literal("spawn").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ String name=StringArgumentType.getString(c,"name"); AgentRecord r=registry.get(name).orElseGet(()->registry.create(name)); BodyResolution body=resolveBody(c.getSource().getServer(),r); if(body.state()==BodyState.UNLOADED) { c.getSource().sendFailure(Component.literal(name+" already has an unloaded body; load its chunk or use /ec repairbody after loading it.")); return 0; } if(body.loadedEntity().isPresent()) { c.getSource().sendSuccess(()->Component.literal(name+" already has body="+body.state()),false); return 1; } spawn(r,c.getSource().getServer(),c.getSource().getPlayerOrException()); c.getSource().sendSuccess(()->Component.literal("EmergentCraft inhabitant "+name+" embodied."),false); return 1; })))
            .then(Commands.literal("list").executes(c->{ c.getSource().sendSuccess(()->Component.literal(registry.all().stream().map(r->r.name()+" ["+(r.alive()?"alive":"dead")+"]").reduce("Inhabitants: ",(a,b)->a+" "+b)),false); return 1; }))
            .then(Commands.literal("inspect").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ Optional<AgentRecord> found=registry.get(StringArgumentType.getString(c,"name")); if(found.isEmpty()) { c.getSource().sendFailure(Component.literal("Unknown inhabitant.")); return 0; } AgentRecord r=found.get(); BodyResolution body=resolveBody(c.getSource().getServer(),r); String loaded=body.loadedEntity().map(e->e.getClass().getSimpleName()+"/"+e.getUUID()).orElse("none"); String action=runtime(r).move==null?"none":runtime(r).move.actionId(); c.getSource().sendSuccess(()->Component.literal(r.name()+" alive="+r.alive()+" paused="+r.paused()+" runtime="+runtime(r).describeState()+" activeMove="+action+" body="+body.state()+" embodimentId="+r.embodimentId()+" loaded="+loaded),false); return 1; })))
            .then(Commands.literal("pause").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord r=require(StringArgumentType.getString(c,"name")); cancelRuntime(c.getSource().getServer(),r); registry.put(r.withPaused(true)); return 1; })))
            .then(Commands.literal("resume").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord r=require(StringArgumentType.getString(c,"name")); registry.put(r.withPaused(false)); return 1; })))
            .then(Commands.literal("repairbody").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord r=require(StringArgumentType.getString(c,"name")); return repairBody(c.getSource().getServer(),c.getSource().getPlayerOrException(),r,c); })))
            .then(Commands.literal("movetest").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord r=require(StringArgumentType.getString(c,"name")); BodyResolution resolution=resolveBody(c.getSource().getServer(),r); if(!resolution.isControlled()) { c.getSource().sendFailure(Component.literal(r.name()+" movement test failed: "+bodyFailure(resolution.state()))); return 0; } cancelRuntime(c.getSource().getServer(),r); GoalLessVillager body=(GoalLessVillager)resolution.entity(); AgentRuntime runtime=runtime(r); runtime.lifecycle.beginAdminActionForcefully(); Optional<Vec3> target=findReachableTestTarget(body); if(target.isEmpty()||!startMove(r,body,runtime,"movetest",r.epoch(),target.get(),true)) { runtime.lifecycle.finishAction(); c.getSource().sendFailure(Component.literal(r.name()+" movement test failed: no path")); return 0; } c.getSource().sendSuccess(()->Component.literal(r.name()+" movement test started"),false); return 1; })))
            .then(Commands.literal("remove").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ String n=StringArgumentType.getString(c,"name"); registry.get(n).ifPresent(r->{ cancelRuntime(c.getSource().getServer(),r); resolveBody(c.getSource().getServer(),r).loadedEntity().ifPresent(Entity::discard); runtimes.remove(r.id()); }); registry.remove(n); return 1; })))
            .then(Commands.literal("revive").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord old=require(StringArgumentType.getString(c,"name")); cancelRuntime(c.getSource().getServer(),old); AgentRecord r=old.alive()?old:new AgentRecord(old.id(),old.name(),old.createdAt(),true,false,null,old.epoch()+1); registry.put(r); spawn(r,c.getSource().getServer(),c.getSource().getPlayerOrException()); return 1; })))
            .then(Commands.literal("brainstatus").executes(c->{ c.getSource().sendSuccess(()->Component.literal("Brain endpoint: "+System.getProperty("emergentcraft.brainUrl","http://127.0.0.1:3847")),false); return 1; }))));
    }

    private AgentRecord require(String name) { return registry.get(name).orElseThrow(()->new IllegalArgumentException("Unknown inhabitant: "+name)); }
    private AgentRuntime runtime(AgentRecord r) { return runtimes.computeIfAbsent(r.id(),ignored->new AgentRuntime()); }
    private void spawn(AgentRecord r,MinecraftServer server,ServerPlayer near) { ServerLevel level=(ServerLevel)near.level(); GoalLessVillager body=createBody(r,level,new Vec3(near.getX()+1.5,near.getY(),near.getZ()+1.5),near.getYRot(),near.getXRot(),null,20); if(level.addFreshEntity(body)) { registry.put(r.withEmbodiment(body.getUUID())); unloadedBodyIds.remove(body.getUUID()); } }
    @SuppressWarnings("unchecked") private GoalLessVillager createBody(AgentRecord r,ServerLevel level,Vec3 pos,float yaw,float pitch,Component existingName,float health) { EntityType<?> raw=BuiltInRegistries.ENTITY_TYPE.getValue(Identifier.withDefaultNamespace("villager")); GoalLessVillager body=new GoalLessVillager((EntityType<? extends Villager>)raw,level); body.snapTo(pos.x,pos.y,pos.z,yaw,pitch); body.setCustomName(existingName==null?Component.literal(r.name()):existingName); body.setCustomNameVisible(true); body.removeFreeWill(); body.setNoAi(false); body.setPersistenceRequired(); body.setHealth(Math.min(health,body.getMaxHealth())); return body; }

    private void onEntityLoad(Entity entity,ServerLevel level) { registry.findByEmbodiment(entity.getUUID()).ifPresent(r->{ unloadedBodyIds.remove(entity.getUUID()); if(EmbodimentRestorePolicy.shouldReplace(r.embodimentId(),entity.getUUID(),entity instanceof GoalLessVillager,entity instanceof Villager) && pendingRestores.add(entity.getUUID())) level.getServer().execute(()->{ try { if(!entity.isRemoved()) repairLoadedVillager(r,entity,level); } finally { pendingRestores.remove(entity.getUUID()); } }); }); }
    private void onEntityUnload(Entity entity,ServerLevel level) { registry.findByEmbodiment(entity.getUUID()).ifPresent(r->unloadedBodyIds.add(entity.getUUID())); }
    private void restoreEmbodiments(MinecraftServer server) { for(AgentRecord r:registry.all()) { if(r.alive()&&r.embodimentId()!=null) unloadedBodyIds.add(r.embodimentId()); BodyResolution body=resolveBody(server,r); if(body.state()==BodyState.VANILLA_NEEDS_RESTORE) repairLoadedVillager(r,body.entity(),(ServerLevel)body.entity().level()); } }
    private boolean repairLoadedVillager(AgentRecord r,Entity entity,ServerLevel level) { if(!(entity instanceof Villager v)||entity.isRemoved()||registry.findByEmbodiment(entity.getUUID()).filter(current->current.id().equals(r.id())).isEmpty()||!EmbodimentRestorePolicy.shouldReplace(r.embodimentId(),entity.getUUID(),entity instanceof GoalLessVillager,true)) return false; GoalLessVillager replacement=createBody(r,level,v.position(),v.getYRot(),v.getXRot(),v.getCustomName(),v.getHealth()); if(!level.addFreshEntity(replacement)) return false; registry.put(r.withEmbodiment(replacement.getUUID())); unloadedBodyIds.remove(entity.getUUID()); unloadedBodyIds.remove(replacement.getUUID()); v.discard(); LOGGER.info("[EmergentCraft] Rewrapped loaded vanilla body for {}",r.name()); return true; }

    private BodyResolution resolveBody(MinecraftServer server,AgentRecord r) { if(!r.alive()) return new BodyResolution(BodyState.DEAD,null); if(r.embodimentId()==null) return new BodyResolution(BodyState.INVALID_REGISTRY,null); Entity entity=findLoadedEntity(server,r.embodimentId()); if(entity==null) return new BodyResolution(unloadedBodyIds.contains(r.embodimentId())?BodyState.UNLOADED:BodyState.MISSING,null); if(entity instanceof GoalLessVillager) return new BodyResolution(BodyState.CONTROLLED,entity); if(entity instanceof Villager) return new BodyResolution(BodyState.VANILLA_NEEDS_RESTORE,entity); return new BodyResolution(BodyState.WRONG_ENTITY,entity); }
    private Entity findLoadedEntity(MinecraftServer server,UUID id) { for(ServerLevel level:server.getAllLevels()) { Entity found=level.getEntity(id); if(found!=null) return found; } return null; }
    private int repairBody(MinecraftServer server,ServerPlayer player,AgentRecord r,com.mojang.brigadier.context.CommandContext<net.minecraft.commands.CommandSourceStack> context) { BodyResolution body=resolveBody(server,r); if(body.state()==BodyState.CONTROLLED) { context.getSource().sendSuccess(()->Component.literal(r.name()+" body already controlled."),false); return 1; } if(body.state()==BodyState.VANILLA_NEEDS_RESTORE) { boolean repaired=repairLoadedVillager(r,body.entity(),(ServerLevel)body.entity().level()); if(repaired) context.getSource().sendSuccess(()->Component.literal(r.name()+" vanilla body repaired."),false); else context.getSource().sendFailure(Component.literal(r.name()+" body repair could not be completed.")); return repaired?1:0; } if(body.state()==BodyState.UNLOADED) { context.getSource().sendFailure(Component.literal(r.name()+" body chunk is unloaded; load that chunk and automatic repair will run.")); return 0; } if(body.state()==BodyState.MISSING||body.state()==BodyState.INVALID_REGISTRY) { spawn(r,server,player); context.getSource().sendSuccess(()->Component.literal(r.name()+" missing body recreated near you."),false); return 1; } context.getSource().sendFailure(Component.literal(r.name()+" body cannot be repaired: "+body.state())); return 0; }
    private static String bodyFailure(BodyState state) { return switch(state) { case UNLOADED -> "body chunk unloaded; load the chunk first"; case VANILLA_NEEDS_RESTORE -> "vanilla body awaiting restoration"; case MISSING -> "body missing; use /ec repairbody"; case INVALID_REGISTRY -> "invalid body registry; use /ec repairbody"; case WRONG_ENTITY -> "registered UUID belongs to a non-villager entity"; case DEAD -> "inhabitant is dead"; default -> "body unavailable"; }; }

    private void tick(MinecraftServer server) { updateActions(server); if(server.getTickCount()%100!=0) return; for(AgentRecord r:registry.all()) { AgentRuntime runtime=runtime(r); if(!r.alive()||r.paused()||!runtime.lifecycle.canRequestCognition()) continue; BodyResolution body=resolveBody(server,r); if(body.isControlled()) requestDecision(server,r,(GoalLessVillager)body.entity()); } }
    private void requestDecision(MinecraftServer server,AgentRecord stored,GoalLessVillager body) { AgentRecord current=stored.nextEpoch(); if(!runtime(current).lifecycle.beginCognition(current.epoch())) return; registry.put(current); String wait="wait:"+current.epoch(),move="move:"+current.epoch(); Vec3 target=new Vec3(body.getX()+3,body.getY(),body.getZ()); ServerLevel world=(ServerLevel)body.level(); String snapshot="{\"agentId\":\""+current.id()+"\",\"name\":\""+escape(current.name())+"\",\"epoch\":"+current.epoch()+",\"self\":{\"position\":{\"x\":"+body.getX()+",\"y\":"+body.getY()+",\"z\":"+body.getZ()+"},\"health\":20,\"hunger\":20,\"heldItem\":\"minecraft:air\"},\"environment\":{\"dimension\":\""+escape(world.dimension().identifier().toString())+"\",\"timeOfDay\":"+world.getOverworldClockTime()+",\"weather\":\"unknown\",\"light\":0,\"biome\":\"local\"},\"entities\":[],\"events\":[],\"candidates\":[{\"id\":\""+wait+"\",\"kind\":\"WAIT\",\"description\":\"Wait and observe.\"},{\"id\":\""+move+"\",\"kind\":\"MOVE_TO\",\"description\":\"Walk a short distance east on foot.\",\"target\":{\"x\":"+target.x+",\"y\":"+target.y+",\"z\":"+target.z+"}}]}"; LOGGER.info("[EmergentCraft] {} perceived 0 entities, 2 candidate actions",current.name()); brain.decide(snapshot).thenAccept(action->server.execute(()->applyDecision(server,current,wait,move,target,action))); }
    private void applyDecision(MinecraftServer server,AgentRecord current,String wait,String move,Vec3 target,Optional<String> action) { AgentRuntime runtime=runtime(current); if(!runtime.lifecycle.acceptsDecision(current.epoch())) return; AgentRecord latest=registry.get(current.name()).orElse(null); if(latest==null||latest.epoch()!=current.epoch()||latest.paused()||!latest.alive()) { runtime.lifecycle.finishCognition(current.epoch()); return; } BodyResolution body=resolveBody(server,latest); if(!body.isControlled()) { runtime.lifecycle.finishCognition(current.epoch()); return; } if(action.filter(wait::equals).isPresent()) { runtime.lifecycle.finishCognition(current.epoch()); LOGGER.info("[EmergentCraft] {} chose WAIT",latest.name()); return; } if(action.filter(move::equals).isPresent()&&runtime.lifecycle.beginAction(current.epoch())) startMove(latest,(GoalLessVillager)body.entity(),runtime,move,current.epoch(),target,false); else runtime.lifecycle.finishCognition(current.epoch()); }
    private boolean startMove(AgentRecord r,GoalLessVillager body,AgentRuntime runtime,String actionId,long epoch,Vec3 target,boolean diagnostic) { double distance=body.position().distanceTo(target); if(!diagnostic) brain.appendFactualEvent(r.id(),epoch,"ACTION","Attempted to move toward a nearby location."); if(!body.getNavigation().moveTo(target.x,target.y,target.z,0.35)) { finishMove(r,body,runtime,false,"Could not find a path to the destination.",diagnostic); return false; } long tick=((ServerLevel)body.level()).getServer().getTickCount(); runtime.move=new MoveExecution(actionId,epoch,body.position(),target,tick,tick,distance,diagnostic); LOGGER.info("[EmergentCraft] {} started {}",r.name(),diagnostic?"movement test":"MOVE_TO"); return true; }
    private void updateActions(MinecraftServer server) { long tick=server.getTickCount(); for(AgentRecord r:registry.all()) { AgentRuntime runtime=runtime(r); MoveExecution move=runtime.move; if(runtime.lifecycle.state()!=AgentLifecycle.State.EXECUTING_ACTION||move==null) continue; BodyResolution resolution=resolveBody(server,r); if(!resolution.isControlled()) { finishMove(r,null,runtime,false,"Movement failed because body is "+resolution.state()+".",move.diagnostic()); continue; } GoalLessVillager body=(GoalLessVillager)resolution.entity(); double distance=body.position().distanceTo(move.target()); if(distance*distance<=ARRIVAL_DISTANCE_SQR) { finishMove(r,body,runtime,true,"Reached the destination.",move.diagnostic()); continue; } if(body.getNavigation().isDone()) { finishMove(r,body,runtime,false,"Movement path ended before reaching the destination.",move.diagnostic()); continue; } if(tick-move.lastProgressTick()>=STUCK_TICKS) { if(move.lastDistance()-distance>=0.25) runtime.move=move.withProgress(tick,distance); else { finishMove(r,body,runtime,false,"Movement failed because the body became stuck.",move.diagnostic()); continue; } } if(tick-move.startTick()>=MOVE_TIMEOUT_TICKS) finishMove(r,body,runtime,false,"Movement timed out before reaching the destination.",move.diagnostic()); } }
    private void finishMove(AgentRecord r,GoalLessVillager body,AgentRuntime runtime,boolean success,String outcome,boolean diagnostic) { if(body!=null) body.getNavigation().stop(); runtime.move=null; runtime.lifecycle.finishAction(); if(!diagnostic) brain.appendFactualEvent(r.id(),r.epoch(),"OUTCOME",outcome); LOGGER.info("[EmergentCraft] {} {} {}: {}",r.name(),diagnostic?"movement test":"MOVE_TO",success?"completed":"failed",outcome); }
    private void cancelRuntime(MinecraftServer server,AgentRecord r) { BodyResolution body=resolveBody(server,r); if(body.isControlled()) ((GoalLessVillager)body.entity()).getNavigation().stop(); AgentRuntime runtime=runtime(r); runtime.move=null; runtime.lifecycle.cancel(); }
    private Optional<Vec3> findReachableTestTarget(GoalLessVillager body) { int[][] offsets={{4,0},{-4,0},{0,4},{0,-4},{3,3},{3,-3},{-3,3},{-3,-3}}; for(int[] o:offsets) { BlockPos candidate=body.blockPosition().offset(o[0],0,o[1]); Path path=body.getNavigation().createPath(candidate,0); if(path!=null&&path.canReach()) { BlockPos end=path.getTarget(); return Optional.of(new Vec3(end.getX()+0.5,end.getY(),end.getZ()+0.5)); } } return Optional.empty(); }
    private static String escape(String value) { return value.replace("\\","\\\\").replace("\"","\\\""); }
}
