package nl.noscapect.emergentcraft;

import com.mojang.brigadier.arguments.StringArgumentType;
import nl.noscapect.emergentcraft.actions.OfferedAction;
import nl.noscapect.emergentcraft.actions.RecipePlanner;
import nl.noscapect.emergentcraft.brain.BrainDecision;
import nl.noscapect.emergentcraft.perception.PerceptionBuilder;
import nl.noscapect.emergentcraft.perception.PerceptionFrame;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerEntityEvents;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents;
import net.minecraft.commands.Commands;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.server.permissions.Permissions;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.npc.villager.Villager;
import net.minecraft.world.level.pathfinder.Path;
import net.minecraft.world.phys.Vec3;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.context.BlockPlaceContext;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.core.Direction;
import com.mojang.authlib.GameProfile;
import net.fabricmc.fabric.api.entity.FakePlayer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.util.*;

public final class EmergentCraftMod implements ModInitializer {
    public static final String MOD_ID="emergentcraft";
    public static final Logger LOGGER=LoggerFactory.getLogger(MOD_ID);
    private static final long STUCK_TICKS=60, MOVE_TIMEOUT_TICKS=400;
    private static final double ARRIVAL_DISTANCE_SQR=2.25;
    private final AgentRegistry registry=new AgentRegistry();
    private final BrainGateway brain=new BrainGateway();
    private final AgentInventoryStore inventory=new AgentInventoryStore();
    private final AgentMetabolismStore metabolism=new AgentMetabolismStore();
    private final PerceptionBuilder perceptions=new PerceptionBuilder(registry,inventory,metabolism);
    private final Map<UUID,AgentRuntime> runtimes=new HashMap<>();
    private final Set<UUID> unloadedBodyIds=new HashSet<>(), pendingRestores=new HashSet<>();

    @Override public void onInitialize() {
        registerCommands(); ServerLifecycleEvents.SERVER_STARTED.register(this::restoreEmbodiments);
        ServerEntityEvents.ENTITY_LOAD.register(this::onEntityLoad); ServerEntityEvents.ENTITY_UNLOAD.register(this::onEntityUnload);
        ServerTickEvents.END_SERVER_TICK.register(this::tick); LOGGER.info("[EmergentCraft] Chunk-safe embodiment restoration initialized.");
    }

    private void registerCommands() {
        CommandRegistrationCallback.EVENT.register((dispatcher,context,environment)->dispatcher.register(Commands.literal("ec").requires(s->s.permissions().hasPermission(Permissions.COMMANDS_GAMEMASTER))
            .then(Commands.literal("spawn").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ String name=StringArgumentType.getString(c,"name"); AgentRecord r=registry.get(name).orElseGet(()->registry.create(name)); BodyResolution body=resolveBody(c.getSource().getServer(),r); if(body.state()==BodyState.UNLOADED) { c.getSource().sendFailure(Component.literal(name+" already has an unloaded body; load its chunk or use /ec repairbody after loading it.")); return 0; } if(body.loadedEntity().isPresent()) { c.getSource().sendSuccess(()->Component.literal(name+" already has body="+body.state()),false); return 1; } spawn(r,c.getSource().getServer(),c.getSource().getPlayerOrException()); c.getSource().sendSuccess(()->Component.literal("EmergentCraft inhabitant "+name+" embodied."),false); return 1; })))
            .then(Commands.literal("list").executes(c->{ c.getSource().sendSuccess(()->Component.literal(registry.all().stream().map(r->r.name()+" ["+(r.alive()?"alive":"dead")+"]").reduce("Inhabitants: ",(a,b)->a+" "+b)),false); return 1; }))
            .then(Commands.literal("inspect").then(Commands.argument("name",StringArgumentType.word()).executes(c->{
                String name=StringArgumentType.getString(c,"name"); Optional<AgentRecord> found=registry.get(name);
                if(found.isEmpty()) { List<Villager> orphans=findOrphanedVanillaBodies(c.getSource().getServer(),name); if(orphans.size()==1) { Villager orphan=orphans.getFirst(); c.getSource().sendSuccess(()->Component.literal(name+" registered=false body=ORPHANED_VANILLA loaded=Villager/"+orphan.getUUID()+"; use /ec remove "+name+" to remove all matching orphaned bodies."),false); return 1; } if(orphans.size()>1) { c.getSource().sendFailure(Component.literal(name+" has "+orphans.size()+" matching unregistered vanilla Villagers: "+orphanIds(orphans)+". Use /ec remove "+name+" to remove all of them, or /ec removeorphan "+name+" <uuid> to choose one.")); return 0; } c.getSource().sendFailure(Component.literal("Unknown inhabitant: "+name)); return 0; }
                AgentRecord r=found.get(); BodyResolution body=resolveBody(c.getSource().getServer(),r); String loaded=body.loadedEntity().map(e->e.getClass().getSimpleName()+"/"+e.getUUID()).orElse("none"); String action=runtime(r).move==null?"none":runtime(r).move.actionId(); c.getSource().sendSuccess(()->Component.literal(r.name()+" alive="+r.alive()+" paused="+r.paused()+" runtime="+runtime(r).describeState()+" activeMove="+action+" body="+body.state()+" embodimentId="+r.embodimentId()+" loaded="+loaded),false); return 1;
            })))
            .then(Commands.literal("activity").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord r=require(StringArgumentType.getString(c,"name")); AgentRuntime runtime=runtime(r); AgentMetabolismStore.State hunger=metabolism.state(r.id(),c.getSource().getServer().getTickCount()); AgentInventoryStore.Equipment equipment=inventory.equipment(r.id()); c.getSource().sendSuccess(()->Component.literal(r.name()+" activity="+runtime.describeState()+" hunger="+hunger.hunger()+"/20 saturation="+hunger.saturation()+" mainHand="+(equipment.mainHand()==null?"empty":equipment.mainHand())+" inventory="+inventory.entries(r.id())),false); return 1; })))
            .then(Commands.literal("perceive").then(Commands.argument("name",StringArgumentType.word()).executes(c->perceive(c,false)).then(Commands.literal("full").executes(c->perceive(c,true)))))
            .then(Commands.literal("actions").then(Commands.argument("name",StringArgumentType.word()).executes(this::showActions)))
            .then(Commands.literal("mind").then(Commands.argument("name",StringArgumentType.word()).executes(c->brainDiagnostic(c,"/v1/mind",false))))
            .then(Commands.literal("memories").then(Commands.argument("name",StringArgumentType.word()).executes(c->brainDiagnostic(c,"/v1/memories",false))))
            .then(Commands.literal("recall").then(Commands.argument("name",StringArgumentType.word()).executes(c->brainDiagnostic(c,"/v1/recall",true))))
            .then(Commands.literal("pause").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord r=require(StringArgumentType.getString(c,"name")); cancelRuntime(c.getSource().getServer(),r); registry.put(r.withPaused(true)); return 1; })))
            .then(Commands.literal("resume").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord r=require(StringArgumentType.getString(c,"name")); registry.put(r.withPaused(false)); return 1; })))
            .then(Commands.literal("repairbody").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord r=require(StringArgumentType.getString(c,"name")); return repairBody(c.getSource().getServer(),c.getSource().getPlayerOrException(),r,c); })))
            .then(Commands.literal("movetest").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord r=require(StringArgumentType.getString(c,"name")); BodyResolution resolution=resolveBody(c.getSource().getServer(),r); if(!resolution.isControlled()) { c.getSource().sendFailure(Component.literal(r.name()+" movement test failed: "+bodyFailure(resolution.state()))); return 0; } cancelRuntime(c.getSource().getServer(),r); GoalLessVillager body=(GoalLessVillager)resolution.entity(); AgentRuntime runtime=runtime(r); runtime.lifecycle.beginAdminActionForcefully(); Optional<Vec3> target=findReachableTestTarget(body); if(target.isEmpty()||!startMove(r,body,runtime,"movetest",r.epoch(),target.get(),true)) { runtime.lifecycle.finishAction(); c.getSource().sendFailure(Component.literal(r.name()+" movement test failed: no path")); return 0; } c.getSource().sendSuccess(()->Component.literal(r.name()+" movement test started"),false); return 1; })))
            .then(Commands.literal("remove").then(Commands.argument("name",StringArgumentType.word()).executes(c->{
                String name=StringArgumentType.getString(c,"name"); Optional<AgentRecord> found=registry.get(name);
                List<Villager> orphans=findOrphanedVanillaBodies(c.getSource().getServer(),name);
                if(found.isPresent()) { AgentRecord r=found.get(); BodyResolution body=resolveBody(c.getSource().getServer(),r); if(body.state()==BodyState.UNLOADED) { c.getSource().sendFailure(Component.literal(name+" has an unloaded registered body; load its chunk before removing all matching bodies.")); return 0; } cancelRuntime(c.getSource().getServer(),r); body.loadedEntity().ifPresent(Entity::discard); runtimes.remove(r.id()); registry.remove(name); }
                for(Villager orphan:orphans) orphan.discard();
                if(found.isEmpty()&&orphans.isEmpty()) { c.getSource().sendFailure(Component.literal("No registered or loaded orphaned Villager named "+name+" was found.")); return 0; }
                int orphanCount=orphans.size(); c.getSource().sendSuccess(()->Component.literal("Removed "+name+(found.isPresent()?" and its registry identity":"")+"; removed "+orphanCount+" matching orphaned body/bodies."),false); return 1;
            })))
            .then(Commands.literal("removeorphan").then(Commands.argument("name",StringArgumentType.word()).executes(c->{
                String name=StringArgumentType.getString(c,"name"); List<Villager> orphans=findOrphanedVanillaBodies(c.getSource().getServer(),name);
                if(orphans.isEmpty()) { c.getSource().sendFailure(Component.literal("No loaded unregistered vanilla Villager named "+name+" was found.")); return 0; }
                if(orphans.size()>1) { c.getSource().sendFailure(Component.literal("Found "+orphans.size()+" matching unregistered vanilla Villagers named "+name+": "+orphanIds(orphans)+". Use /ec removeorphan "+name+" <uuid> to choose one.")); return 0; }
                Villager orphan=orphans.getFirst(); orphan.discard(); c.getSource().sendSuccess(()->Component.literal("Removed orphaned vanilla Villager "+name+" ("+orphan.getUUID()+")."),false); return 1;
            }).then(Commands.argument("uuid",StringArgumentType.word()).executes(c->{
                String name=StringArgumentType.getString(c,"name"), rawId=StringArgumentType.getString(c,"uuid"); UUID id;
                try { id=UUID.fromString(rawId); } catch(IllegalArgumentException ignored) { c.getSource().sendFailure(Component.literal("Invalid UUID: "+rawId)); return 0; }
                List<Villager> matches=findOrphanedVanillaBodies(c.getSource().getServer(),name).stream().filter(v->v.getUUID().equals(id)).toList();
                if(matches.size()!=1) { c.getSource().sendFailure(Component.literal("No loaded unregistered vanilla Villager named "+name+" has UUID "+id+".")); return 0; }
                Villager orphan=matches.getFirst(); orphan.discard(); c.getSource().sendSuccess(()->Component.literal("Removed orphaned vanilla Villager "+name+" ("+id+")."),false); return 1;
            }))))
            .then(Commands.literal("revive").then(Commands.argument("name",StringArgumentType.word()).executes(c->{ AgentRecord old=require(StringArgumentType.getString(c,"name")); cancelRuntime(c.getSource().getServer(),old); AgentRecord r=old.alive()?old:new AgentRecord(old.id(),old.name(),old.createdAt(),true,false,null,old.epoch()+1); registry.put(r); spawn(r,c.getSource().getServer(),c.getSource().getPlayerOrException()); return 1; })))
            .then(Commands.literal("brainstatus").executes(c->{ c.getSource().sendSuccess(()->Component.literal("Brain endpoint: "+System.getProperty("emergentcraft.brainUrl","http://127.0.0.1:3847")),false); return 1; }))));
    }

    private AgentRecord require(String name) { return registry.get(name).orElseThrow(()->new IllegalArgumentException("Unknown inhabitant: "+name)); }
    private int perceive(com.mojang.brigadier.context.CommandContext<net.minecraft.commands.CommandSourceStack> context,boolean full) { String name=StringArgumentType.getString(context,"name"); Optional<AgentRecord> found=registry.get(name); if(found.isEmpty()) { context.getSource().sendFailure(Component.literal("Unknown inhabitant: "+name)); return 0; } BodyResolution resolution=resolveBody(context.getSource().getServer(),found.get()); if(!resolution.isControlled()) { context.getSource().sendFailure(Component.literal(name+" cannot perceive: "+bodyFailure(resolution.state()))); return 0; } PerceptionFrame frame=perceptions.build(found.get(),(GoalLessVillager)resolution.entity(),runtime(found.get()).recent()); var perception=frame.perception(); context.getSource().sendSuccess(()->Component.literal(name+" perception: health "+perception.self().health()+"/"+perception.self().maxHealth()+", biome "+perception.environment().biome()+", visible entities "+perception.entities().size()+", visible blocks "+perception.blocks().size()+", dropped items "+perception.items().size()+", legal actions "+perception.candidates().size()),false); if(full) LOGGER.info("[EmergentCraft] {} perception: {}",name,new com.google.gson.Gson().toJson(perception)); return 1; }
    private int showActions(com.mojang.brigadier.context.CommandContext<net.minecraft.commands.CommandSourceStack> context) { String name=StringArgumentType.getString(context,"name"); Optional<AgentRecord> found=registry.get(name); if(found.isEmpty()) { context.getSource().sendFailure(Component.literal("Unknown inhabitant: "+name)); return 0; } BodyResolution resolution=resolveBody(context.getSource().getServer(),found.get()); if(!resolution.isControlled()) { context.getSource().sendFailure(Component.literal(name+" cannot generate actions: "+bodyFailure(resolution.state()))); return 0; } PerceptionFrame frame=perceptions.build(found.get(),(GoalLessVillager)resolution.entity(),runtime(found.get()).recent()); String summary=frame.perception().candidates().stream().map(candidate->candidate.kind()).distinct().reduce((a,b)->a+", "+b).orElse("none"); context.getSource().sendSuccess(()->Component.literal(name+" legal actions ("+frame.perception().candidates().size()+"): "+summary+". Full list in server log."),false); LOGGER.info("[EmergentCraft] {} actions: {}",name,new com.google.gson.Gson().toJson(frame.perception().candidates())); return 1; }
    private int brainDiagnostic(com.mojang.brigadier.context.CommandContext<net.minecraft.commands.CommandSourceStack> context,String route,boolean needsPerception) { String name=StringArgumentType.getString(context,"name"); Optional<AgentRecord> found=registry.get(name); if(found.isEmpty()) { context.getSource().sendFailure(Component.literal("Unknown inhabitant: "+name)); return 0; } Object payload=Map.of("agentId",found.get().id().toString()); if(needsPerception) { BodyResolution body=resolveBody(context.getSource().getServer(),found.get()); if(!body.isControlled()) { context.getSource().sendFailure(Component.literal(name+" cannot recall: "+bodyFailure(body.state()))); return 0; } payload=perceptions.build(found.get(),(GoalLessVillager)body.entity(),runtime(found.get()).recent()).perception(); } net.minecraft.commands.CommandSourceStack source=context.getSource(); brain.diagnostic(route,payload).thenAccept(result->source.getServer().execute(()->{ if(result.isEmpty()) { source.sendFailure(Component.literal("Brain memory diagnostic unavailable.")); return; } String json=result.get(); LOGGER.info("[EmergentCraft] {} {}: {}",name,route,json); try { com.google.gson.JsonObject object=com.google.gson.JsonParser.parseString(json).getAsJsonObject(); if(route.equals("/v1/mind")) { int projects=object.getAsJsonArray("projects").size(),beliefs=object.getAsJsonArray("beliefs").size(),episodes=object.getAsJsonObject("memoryCounts").get("episodes").getAsInt(); source.sendSuccess(()->Component.literal(name+" mind: projects="+projects+", beliefs="+beliefs+", episodes="+episodes+". Details in server log."),false); } else if(route.equals("/v1/recall")) source.sendSuccess(()->Component.literal(name+" recall: working="+object.getAsJsonArray("working").size()+", relevant="+object.getAsJsonArray("recalled").size()+", social="+object.getAsJsonArray("social").size()+", chapters="+object.getAsJsonArray("chapters").size()+". Details in server log."),false); else source.sendSuccess(()->Component.literal(name+" memories written to server log."),false); } catch(Exception error) { source.sendFailure(Component.literal("Brain memory diagnostic returned invalid data.")); } })); return 1; }
    private AgentRuntime runtime(AgentRecord r) { return runtimes.computeIfAbsent(r.id(),ignored->new AgentRuntime()); }
    private void spawn(AgentRecord r,MinecraftServer server,ServerPlayer near) { ServerLevel level=(ServerLevel)near.level(); GoalLessVillager body=createBody(r,level,new Vec3(near.getX()+1.5,near.getY(),near.getZ()+1.5),near.getYRot(),near.getXRot(),null,20); if(level.addFreshEntity(body)) { registry.put(r.withEmbodiment(body.getUUID())); unloadedBodyIds.remove(body.getUUID()); } }
    @SuppressWarnings("unchecked") private GoalLessVillager createBody(AgentRecord r,ServerLevel level,Vec3 pos,float yaw,float pitch,Component existingName,float health) { EntityType<?> raw=BuiltInRegistries.ENTITY_TYPE.getValue(Identifier.withDefaultNamespace("villager")); GoalLessVillager body=new GoalLessVillager((EntityType<? extends Villager>)raw,level); body.snapTo(pos.x,pos.y,pos.z,yaw,pitch); body.setCustomName(existingName==null?Component.literal(r.name()):existingName); body.setCustomNameVisible(true); body.removeFreeWill(); body.setNoAi(false); body.setPersistenceRequired(); body.setHealth(Math.min(health,body.getMaxHealth())); return body; }

    private void onEntityLoad(Entity entity,ServerLevel level) { registry.findByEmbodiment(entity.getUUID()).ifPresent(r->{ unloadedBodyIds.remove(entity.getUUID()); if(EmbodimentRestorePolicy.shouldReplace(r.embodimentId(),entity.getUUID(),entity instanceof GoalLessVillager,entity instanceof Villager) && pendingRestores.add(entity.getUUID())) level.getServer().execute(()->{ try { if(!entity.isRemoved()) repairLoadedVillager(r,entity,level); } finally { pendingRestores.remove(entity.getUUID()); } }); }); }
    private void onEntityUnload(Entity entity,ServerLevel level) { registry.findByEmbodiment(entity.getUUID()).ifPresent(r->{ if(entity instanceof GoalLessVillager&& !entity.isAlive()) markDead(level.getServer(),r,"The body died."); else unloadedBodyIds.add(entity.getUUID()); }); }
    private void restoreEmbodiments(MinecraftServer server) { for(AgentRecord r:registry.all()) { if(r.alive()&&r.embodimentId()!=null) unloadedBodyIds.add(r.embodimentId()); BodyResolution body=resolveBody(server,r); if(body.state()==BodyState.VANILLA_NEEDS_RESTORE) repairLoadedVillager(r,body.entity(),(ServerLevel)body.entity().level()); } }
    private boolean repairLoadedVillager(AgentRecord r,Entity entity,ServerLevel level) { if(!(entity instanceof Villager v)||entity.isRemoved()||registry.findByEmbodiment(entity.getUUID()).filter(current->current.id().equals(r.id())).isEmpty()||!EmbodimentRestorePolicy.shouldReplace(r.embodimentId(),entity.getUUID(),entity instanceof GoalLessVillager,true)) return false; GoalLessVillager replacement=createBody(r,level,v.position(),v.getYRot(),v.getXRot(),v.getCustomName(),v.getHealth()); if(!level.addFreshEntity(replacement)) return false; registry.put(r.withEmbodiment(replacement.getUUID())); unloadedBodyIds.remove(entity.getUUID()); unloadedBodyIds.remove(replacement.getUUID()); v.discard(); LOGGER.info("[EmergentCraft] Rewrapped loaded vanilla body for {}",r.name()); return true; }

    private BodyResolution resolveBody(MinecraftServer server,AgentRecord r) { if(!r.alive()) return new BodyResolution(BodyState.DEAD,null); if(r.embodimentId()==null) return new BodyResolution(BodyState.INVALID_REGISTRY,null); Entity entity=findLoadedEntity(server,r.embodimentId()); if(entity==null) return new BodyResolution(unloadedBodyIds.contains(r.embodimentId())?BodyState.UNLOADED:BodyState.MISSING,null); if(entity instanceof GoalLessVillager) return new BodyResolution(BodyState.CONTROLLED,entity); if(entity instanceof Villager) return new BodyResolution(BodyState.VANILLA_NEEDS_RESTORE,entity); return new BodyResolution(BodyState.WRONG_ENTITY,entity); }
    private Entity findLoadedEntity(MinecraftServer server,UUID id) { for(ServerLevel level:server.getAllLevels()) { Entity found=level.getEntity(id); if(found!=null) return found; } return null; }
    private List<Villager> findOrphanedVanillaBodies(MinecraftServer server,String name) { List<Villager> matches=new ArrayList<>(); for(ServerLevel level:server.getAllLevels()) for(Entity entity:level.getAllEntities()) if(entity instanceof Villager villager&&OrphanedBodyPolicy.isExactUnregisteredVanillaVillager(name,villager.getCustomName()==null?null:villager.getCustomName().getString(),registry.findByEmbodiment(villager.getUUID()).isPresent(),villager instanceof GoalLessVillager,true)) matches.add(villager); return matches; }
    private static String orphanIds(List<Villager> orphans) { return orphans.stream().map(villager->villager.getUUID().toString()).toList().toString(); }
    private int repairBody(MinecraftServer server,ServerPlayer player,AgentRecord r,com.mojang.brigadier.context.CommandContext<net.minecraft.commands.CommandSourceStack> context) { BodyResolution body=resolveBody(server,r); if(body.state()==BodyState.CONTROLLED) { context.getSource().sendSuccess(()->Component.literal(r.name()+" body already controlled."),false); return 1; } if(body.state()==BodyState.VANILLA_NEEDS_RESTORE) { boolean repaired=repairLoadedVillager(r,body.entity(),(ServerLevel)body.entity().level()); if(repaired) context.getSource().sendSuccess(()->Component.literal(r.name()+" vanilla body repaired."),false); else context.getSource().sendFailure(Component.literal(r.name()+" body repair could not be completed.")); return repaired?1:0; } if(body.state()==BodyState.UNLOADED) { context.getSource().sendFailure(Component.literal(r.name()+" body chunk is unloaded; load that chunk and automatic repair will run.")); return 0; } if(body.state()==BodyState.MISSING||body.state()==BodyState.INVALID_REGISTRY) { spawn(r,server,player); context.getSource().sendSuccess(()->Component.literal(r.name()+" missing body recreated near you."),false); return 1; } context.getSource().sendFailure(Component.literal(r.name()+" body cannot be repaired: "+body.state())); return 0; }
    private static String bodyFailure(BodyState state) { return switch(state) { case UNLOADED -> "body chunk unloaded; load the chunk first"; case VANILLA_NEEDS_RESTORE -> "vanilla body awaiting restoration"; case MISSING -> "body missing; use /ec repairbody"; case INVALID_REGISTRY -> "invalid body registry; use /ec repairbody"; case WRONG_ENTITY -> "registered UUID belongs to a non-villager entity"; case DEAD -> "inhabitant is dead"; default -> "body unavailable"; }; }

    private void tick(MinecraftServer server) { monitorBodies(server); updateActions(server); if(server.getTickCount()%100!=0) return; for(AgentRecord r:registry.all()) { AgentRuntime runtime=runtime(r); if(!r.alive()||r.paused()||!runtime.lifecycle.canRequestCognition()) continue; BodyResolution body=resolveBody(server,r); if(body.isControlled()) requestDecision(server,r,(GoalLessVillager)body.entity()); } }
    private void monitorBodies(MinecraftServer server) { for(AgentRecord record:registry.all()) { if(!record.alive()) continue; BodyResolution resolution=resolveBody(server,record); if(!resolution.isControlled()) continue; GoalLessVillager body=(GoalLessVillager)resolution.entity(); AgentRuntime runtime=runtime(record); syncEquipment(record,body); AgentMetabolismStore.State before=metabolism.state(record.id(),server.getTickCount()), hunger=metabolism.tick(record.id(),server.getTickCount(),runtime.lifecycle.state()==AgentLifecycle.State.EXECUTING_ACTION); if(hunger.hunger()!=before.hunger()&&(hunger.hunger()==0||hunger.hunger()==5||hunger.hunger()==10)) { String event="Hunger is now "+hunger.hunger()+"/20."; runtime.event("HUNGER",event); brain.appendFactualEvent(record.id(),record.epoch(),"OUTCOME",event,factualMetadata(body,null,null,null)); } if(hunger.starving()&&server.getTickCount()%80==0) body.hurtServer((ServerLevel)body.level(),((ServerLevel)body.level()).damageSources().starve(),1f); if(!Float.isNaN(runtime.lastHealth)&&body.getHealth()+0.01f<runtime.lastHealth) { String event="Health changed from "+runtime.lastHealth+" to "+body.getHealth()+"."; runtime.event("DAMAGE",event); brain.appendFactualEvent(record.id(),record.epoch(),"DAMAGE",event,factualMetadata(body,null,null,null)); } runtime.lastHealth=body.getHealth(); if(!body.isAlive()) markDead(server,record,"The body died.",body); } }
    private void markDead(MinecraftServer server,AgentRecord record,String event) { markDead(server,record,event,null); }
    private void markDead(MinecraftServer server,AgentRecord record,String event,GoalLessVillager body) { AgentRecord latest=registry.get(record.name()).orElse(null); if(latest==null||!latest.alive()) return; cancelRuntime(server,latest); registry.put(new AgentRecord(latest.id(),latest.name(),latest.createdAt(),false,latest.paused(),latest.embodimentId(),latest.epoch()+1)); runtime(latest).event("DEATH",event); brain.appendFactualEvent(latest.id(),latest.epoch(),"DEATH",event,body==null?Map.of():factualMetadata(body,null,null,null)); LOGGER.info("[EmergentCraft] {} died",latest.name()); }
    private void requestDecision(MinecraftServer server,AgentRecord stored,GoalLessVillager body) { AgentRecord current=stored.nextEpoch(); AgentRuntime runtime=runtime(current); if(!runtime.lifecycle.beginCognition(current.epoch())) return; registry.put(current); PerceptionFrame frame=perceptions.build(current,body,runtime.recent()); runtime.offeredActions=frame.offeredActions(); LOGGER.info("[EmergentCraft] {} perceived {} entities, {} blocks, {} items and {} actions",current.name(),frame.perception().entities().size(),frame.perception().blocks().size(),frame.perception().items().size(),frame.perception().candidates().size()); brain.decide(frame.perception()).thenAccept(decision->server.execute(()->applyDecision(server,current,decision))); }
    private void applyDecision(MinecraftServer server,AgentRecord current,Optional<BrainDecision> decision) { AgentRuntime runtime=runtime(current); if(!runtime.lifecycle.acceptsDecision(current.epoch())) return; AgentRecord latest=registry.get(current.name()).orElse(null); if(latest==null||latest.epoch()!=current.epoch()||latest.paused()||!latest.alive()||decision.isEmpty()) { runtime.lifecycle.finishCognition(current.epoch()); return; } BodyResolution resolution=resolveBody(server,latest); if(!resolution.isControlled()) { runtime.lifecycle.finishCognition(current.epoch()); return; } BrainDecision selected=decision.get(); OfferedAction action=runtime.offeredActions.get(selected.actionId()); if(action==null) { runtime.lifecycle.finishCognition(current.epoch()); return; } LOGGER.info("[EmergentCraft] {} intent: {}",latest.name(),selected.intent()); GoalLessVillager body=(GoalLessVillager)resolution.entity(); if(action.kind()==OfferedAction.Kind.WAIT) { runtime.lifecycle.finishCognition(current.epoch()); return; } if(action.kind()==OfferedAction.Kind.SPEAK) { speak(server,latest,body,action,selected.speech(),runtime); return; } if(!runtime.lifecycle.beginAction(current.epoch())) return; boolean started=switch(action.kind()) { case EAT_ITEM -> eat(latest,body,runtime,action); case EQUIP_ITEM -> equip(latest,body,runtime,action); case CRAFT -> craft(latest,body,runtime,action); case BUILD_PLAN -> startBuildPlan(latest,body,runtime,action,selected.buildPlan()); default -> startOfferedAction(latest,body,runtime,action); }; if(!started) runtime.lifecycle.finishAction(); }
    private boolean startOfferedAction(AgentRecord agent,GoalLessVillager body,AgentRuntime runtime,OfferedAction action) { Vec3 target; Entity targetEntity=null; if(action.kind()==OfferedAction.Kind.MOVE_TO||action.kind()==OfferedAction.Kind.TRAVEL||action.kind()==OfferedAction.Kind.APPROACH_BLOCK||action.kind()==OfferedAction.Kind.BREAK_BLOCK||action.kind()==OfferedAction.Kind.ACQUIRE_BLOCK||action.kind()==OfferedAction.Kind.PLACE_BLOCK) { if(action.blockPos()!=null&&(action.kind()==OfferedAction.Kind.BREAK_BLOCK||action.kind()==OfferedAction.Kind.ACQUIRE_BLOCK||action.kind()==OfferedAction.Kind.APPROACH_BLOCK)) { var state=body.level().getBlockState(action.blockPos()); if(state.isAir()||!BuiltInRegistries.BLOCK.getKey(state.getBlock()).toString().equals(action.expectedTarget())) return false; } target=action.destination(); } else { targetEntity=action.entityId()==null?null:findLoadedEntity(((ServerLevel)body.level()).getServer(),action.entityId()); if(targetEntity==null||targetEntity.isRemoved()) return false; if(action.kind()==OfferedAction.Kind.PICK_UP_ITEM) { if(!(targetEntity instanceof net.minecraft.world.entity.item.ItemEntity item)||!BuiltInRegistries.ITEM.getKey(item.getItem().getItem()).toString().equals(action.expectedTarget())) return false; } else if(!(targetEntity instanceof LivingEntity)||!BuiltInRegistries.ENTITY_TYPE.getKey(targetEntity.getType()).toString().equals(action.expectedTarget())) return false; target=targetEntity.position(); } long tick=((ServerLevel)body.level()).getServer().getTickCount(); runtime.skill=new SkillExecution(action.id(),action.kind(),"NAVIGATE",tick,tick,action.expectedTarget(),0,1,false); runtime.event("ACTION","Attempted "+action.kind()+"."); brain.appendFactualEvent(agent.id(),agent.epoch(),"ACTION","Attempted "+action.kind()+".",factualMetadata(body,action,null,targetEntity)); return startMove(agent,body,runtime,action.id(),agent.epoch(),target,false); }
    private boolean startBuildPlan(AgentRecord agent,GoalLessVillager body,AgentRuntime runtime,OfferedAction action,BrainDecision.BuildPlan requested) { if(requested==null||requested.placements()==null||requested.placements().isEmpty()||requested.placements().size()>24) return false; BlockPos origin=body.blockPosition(); List<OfferedAction> placements=new ArrayList<>(); int index=0; for(BrainDecision.Placement placement:requested.placements()) { if(Math.abs(placement.x())>4||Math.abs(placement.y())>3||Math.abs(placement.z())>4||placement.itemId()==null||inventory.count(agent.id(),placement.itemId())<=0) return false; BlockPos target=origin.offset(placement.x(),placement.y(),placement.z()); if(!body.level().getBlockState(target).isAir()||!body.level().getBlockState(target.below()).isSolid()) return false; ItemStack stack=inventory.stack(agent.id(),placement.itemId()).orElse(ItemStack.EMPTY); if(!(stack.getItem() instanceof net.minecraft.world.item.BlockItem)) return false; String id="buildplace:"+agent.epoch()+":"+index++; placements.add(new OfferedAction(id,OfferedAction.Kind.PLACE_BLOCK,Vec3.atCenterOf(target),null,target,placement.itemId())); }
        Map<String,OfferedAction> offered=new LinkedHashMap<>(runtime.offeredActions); for(OfferedAction placement:placements) offered.put(placement.id(),placement); runtime.offeredActions=Map.copyOf(offered); runtime.buildPlan=new BuildPlanExecution(requested.purpose()==null?"":requested.purpose(),List.copyOf(placements),0); long tick=((ServerLevel)body.level()).getServer().getTickCount(); runtime.skill=new SkillExecution(action.id(),OfferedAction.Kind.BUILD_PLAN,"NAVIGATE",tick,tick,requested.purpose(),0,placements.size(),false); runtime.event("ACTION","Started build plan with "+placements.size()+" placements."); brain.appendFactualEvent(agent.id(),agent.epoch(),"ACTION","Started build plan with "+placements.size()+" placements.",factualMetadata(body,action,null,null)); OfferedAction first=runtime.buildPlan.current(); return startMove(agent,body,runtime,first.id(),agent.epoch(),first.destination(),false); }
    private void speak(MinecraftServer server,AgentRecord speaker,GoalLessVillager body,OfferedAction action,String speech,AgentRuntime runtime) { Entity target=action.entityId()==null?null:findLoadedEntity(server,action.entityId()); if(target==null||target.isRemoved()||body.distanceToSqr(target)>14*14||speech==null||speech.isBlank()) { runtime.lifecycle.finishCognition(speaker.epoch()); return; } String text=speech.trim(); if(text.length()>240) text=text.substring(0,240); Component message=Component.literal("<"+speaker.name()+"> "+text); for(ServerPlayer player:server.getPlayerList().getPlayers()) if(player.level()==body.level()&&player.distanceToSqr(body)<=14*14) player.sendSystemMessage(message); for(AgentRecord listener:registry.all()) { if(listener.id().equals(speaker.id())||!listener.alive()) continue; BodyResolution listenerBody=resolveBody(server,listener); if(listenerBody.isControlled()&&listenerBody.entity().level()==body.level()&&listenerBody.entity().distanceToSqr(body)<=14*14) { runtime(listener).event("SPEECH","Heard "+speaker.name()+": "+text); Map<String,Object> metadata=factualMetadata((GoalLessVillager)listenerBody.entity(),null,null,body); metadata.put("actionKind","SPEAK"); brain.appendFactualEvent(listener.id(),listener.epoch(),"SPEECH","Heard "+speaker.name()+": "+text,metadata); } } runtime.event("SPEECH","Said: "+text); brain.appendFactualEvent(speaker.id(),speaker.epoch(),"SPEECH","Said: "+text,factualMetadata(body,action,null,target)); runtime.lifecycle.finishCognition(speaker.epoch()); }
    private boolean startMove(AgentRecord r,GoalLessVillager body,AgentRuntime runtime,String actionId,long epoch,Vec3 target,boolean diagnostic) { double distance=body.position().distanceTo(target); if(!body.getNavigation().moveTo(target.x,target.y,target.z,0.35)) { finishMove(r,body,runtime,false,"Could not find a path to the destination.",diagnostic); return false; } long tick=((ServerLevel)body.level()).getServer().getTickCount(); runtime.move=new MoveExecution(actionId,epoch,body.position(),target,tick,tick,distance,diagnostic); LOGGER.info("[EmergentCraft] {} started {}",r.name(),diagnostic?"movement test":actionId); return true; }
    private void updateActions(MinecraftServer server) { long tick=server.getTickCount(); for(AgentRecord r:registry.all()) { AgentRuntime runtime=runtime(r); MoveExecution move=runtime.move; if(runtime.lifecycle.state()!=AgentLifecycle.State.EXECUTING_ACTION||move==null) continue; BodyResolution resolution=resolveBody(server,r); if(!resolution.isControlled()) { finishMove(r,null,runtime,false,"Action failed because body is "+resolution.state()+".",move.diagnostic()); continue; } GoalLessVillager body=(GoalLessVillager)resolution.entity(); double distance=body.position().distanceTo(move.target()); if(distance*distance<=ARRIVAL_DISTANCE_SQR) { OfferedAction action=runtime.offeredActions.get(move.actionId()); if(action!=null&&(action.kind()==OfferedAction.Kind.BREAK_BLOCK||action.kind()==OfferedAction.Kind.ACQUIRE_BLOCK)) { if(!finishBreak(r,body,runtime,action,move,tick)) continue; } else if(action!=null&&action.kind()==OfferedAction.Kind.PICK_UP_ITEM) { finishPickup(r,body,runtime,action); } else if(action!=null&&action.kind()==OfferedAction.Kind.PLACE_BLOCK) { finishPlace(r,body,runtime,action); } else if(action!=null&&action.kind()==OfferedAction.Kind.ENGAGE) { finishAttack(r,body,runtime,action); } else if(action!=null&&(action.kind()==OfferedAction.Kind.APPROACH_ENTITY||action.kind()==OfferedAction.Kind.APPROACH_BLOCK)) finishApproach(r,body,runtime,action); else finishMove(r,body,runtime,true,"Reached the destination.",move.diagnostic()); continue; } if(body.getNavigation().isDone()) { finishMove(r,body,runtime,false,"Movement path ended before reaching the destination.",move.diagnostic()); continue; } if(tick-move.lastProgressTick()>=STUCK_TICKS) { if(move.lastDistance()-distance>=0.25) runtime.move=move.withProgress(tick,distance); else { finishMove(r,body,runtime,false,"Movement failed because the body became stuck.",move.diagnostic()); continue; } } if(tick-move.startTick()>=MOVE_TIMEOUT_TICKS) finishMove(r,body,runtime,false,"Movement timed out before reaching the destination.",move.diagnostic()); } }
    private void finishApproach(AgentRecord agent,GoalLessVillager body,AgentRuntime runtime,OfferedAction action) { if(action.kind()==OfferedAction.Kind.APPROACH_ENTITY) { Entity target=action.entityId()==null?null:findLoadedEntity(((ServerLevel)body.level()).getServer(),action.entityId()); if(target==null||target.isRemoved()||body.distanceToSqr(target)>9||!BuiltInRegistries.ENTITY_TYPE.getKey(target.getType()).toString().equals(action.expectedTarget())) { finishMove(agent,body,runtime,false,"Target entity was no longer reachable.",false); return; } } else { var state=body.level().getBlockState(action.blockPos()); if(state.isAir()||!BuiltInRegistries.BLOCK.getKey(state.getBlock()).toString().equals(action.expectedTarget())) { finishMove(agent,body,runtime,false,"Target block changed before arrival.",false); return; } } finishMove(agent,body,runtime,true,"Reached the selected target.",false); }
    private boolean finishBreak(AgentRecord agent,GoalLessVillager body,AgentRuntime runtime,OfferedAction action,MoveExecution move,long tick) { if(action.blockPos()==null) { finishMove(agent,body,runtime,false,"Block target was unavailable.",false); return true; } var level=(ServerLevel)body.level(); var state=level.getBlockState(action.blockPos()); boolean exact=!state.isAir()&&BuiltInRegistries.BLOCK.getKey(state.getBlock()).toString().equals(action.expectedTarget()); if(!nl.noscapect.emergentcraft.actions.ActionValidation.canBreak(state.getDestroySpeed(level,action.blockPos()),body.distanceToSqr(Vec3.atCenterOf(action.blockPos())),exact)) { finishMove(agent,body,runtime,false,"Block changed, was unbreakable, or was out of range.",false); return true; } long required=Math.max(8,Math.min(160,(long)Math.ceil((state.getDestroySpeed(level,action.blockPos())+1)*20))); if(tick-move.startTick()<required) return false; boolean broken=level.destroyBlock(action.blockPos(),true,body,512); finishMove(agent,body,runtime,broken,broken?"Broke "+action.expectedTarget()+".":"Minecraft rejected block destruction.",false); return true; }
    private void finishAttack(AgentRecord agent,GoalLessVillager body,AgentRuntime runtime,OfferedAction action) { Entity target=action.entityId()==null?null:findLoadedEntity(((ServerLevel)body.level()).getServer(),action.entityId()); if(!(target instanceof LivingEntity living)||target.isRemoved()||!living.isAlive()||body.distanceToSqr(living)>9||!BuiltInRegistries.ENTITY_TYPE.getKey(living.getType()).toString().equals(action.expectedTarget())) { finishMove(agent,body,runtime,false,"Engagement target was lost or out of range.",false); return; } syncEquipment(agent,body); float before=living.getHealth(); boolean hit=body.doHurtTarget((ServerLevel)body.level(),living); float dealt=Math.max(0,before-living.getHealth()); finishMove(agent,body,runtime,hit,"Attacked "+action.expectedTarget()+" and dealt "+dealt+" damage.",false); }
    private void finishPlace(AgentRecord agent,GoalLessVillager body,AgentRuntime runtime,OfferedAction action) { if(action.blockPos()==null||!body.level().getBlockState(action.blockPos()).isAir()) { finishMove(agent,body,runtime,false,"Placement position changed or was obstructed.",false); return; } Optional<ItemStack> source=inventory.stack(agent.id(),action.expectedTarget()); if(source.isEmpty()||!(source.get().getItem() instanceof net.minecraft.world.item.BlockItem block)) { finishMove(agent,body,runtime,false,"Required block item was unavailable.",false); return; } BlockPos support=action.blockPos().below(); if(!body.level().getBlockState(support).isSolid()) { finishMove(agent,body,runtime,false,"Placement needs a solid adjacent support.",false); return; } ServerLevel level=(ServerLevel)body.level(); FakePlayer proxy=FakePlayer.get(level,new GameProfile(UUID.nameUUIDFromBytes(("emergentcraft:"+agent.id()).getBytes(java.nio.charset.StandardCharsets.UTF_8)),"[EmergentCraft]")); proxy.snapTo(body.getX(),body.getY(),body.getZ(),body.getYRot(),body.getXRot()); ItemStack held=source.get().copyWithCount(1); proxy.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,held); boolean placed=block.place(new BlockPlaceContext(proxy,net.minecraft.world.InteractionHand.MAIN_HAND,held,new BlockHitResult(Vec3.atCenterOf(support),Direction.UP,support,false))).consumesAction(); if(placed&&!inventory.remove(agent.id(),action.expectedTarget(),1)) placed=false; if(placed&&runtime.buildPlan!=null&&runtime.buildPlan.hasNext()) { runtime.buildPlan=runtime.buildPlan.next(); OfferedAction next=runtime.buildPlan.current(); if(startMove(agent,body,runtime,next.id(),agent.epoch(),next.destination(),false)) return; finishMove(agent,body,runtime,false,"Build plan path failed after "+runtime.buildPlan.index()+" placements.",false); return; } String result=placed?"Placed "+action.expectedTarget()+" at "+action.blockPos().getX()+"/"+action.blockPos().getY()+"/"+action.blockPos().getZ()+".":"Minecraft rejected block placement."; if(placed&&runtime.buildPlan!=null) result="Completed build plan: placed "+runtime.buildPlan.placements().size()+" blocks."; finishMove(agent,body,runtime,placed,result,false); }
    private void finishPickup(AgentRecord agent,GoalLessVillager body,AgentRuntime runtime,OfferedAction action) { Entity target=action.entityId()==null?null:findLoadedEntity(((ServerLevel)body.level()).getServer(),action.entityId()); if(!(target instanceof net.minecraft.world.entity.item.ItemEntity item)||item.isRemoved()) { finishMove(agent,body,runtime,false,"Dropped item was no longer available.",false); return; } var stack=item.getItem(); boolean exact=BuiltInRegistries.ITEM.getKey(stack.getItem()).toString().equals(action.expectedTarget()); boolean capacity=inventory.canAccept(agent.id(),action.expectedTarget(),stack.getCount()); if(!nl.noscapect.emergentcraft.actions.ActionValidation.canPickUp(body.distanceToSqr(item),exact,capacity)) { finishMove(agent,body,runtime,false,"Dropped item changed, was out of range, or inventory was full.",false); return; } inventory.add(agent.id(),action.expectedTarget(),stack.getCount()); runtime.event("ACQUISITION","Picked up "+stack.getCount()+" "+action.expectedTarget()+"."); brain.appendFactualEvent(agent.id(),agent.epoch(),"ACQUISITION","Picked up "+stack.getCount()+" "+action.expectedTarget()+".",factualMetadata(body,action,true,item)); item.discard(); finishMove(agent,body,runtime,true,"Picked up "+action.expectedTarget()+".",false); }
    private boolean eat(AgentRecord agent,GoalLessVillager body,AgentRuntime runtime,OfferedAction action) { Optional<ItemStack> stack=inventory.stack(agent.id(),action.expectedTarget()); if(stack.isEmpty()||stack.get().get(net.minecraft.core.component.DataComponents.FOOD)==null) return false; AgentMetabolismStore.State before=metabolism.state(agent.id(),((ServerLevel)body.level()).getServer().getTickCount()); if(!inventory.remove(agent.id(),action.expectedTarget(),1)) return false; AgentMetabolismStore.State after=metabolism.eat(agent.id(),((ServerLevel)body.level()).getServer().getTickCount(),stack.get()); body.swing(net.minecraft.world.InteractionHand.MAIN_HAND); finishMove(agent,body,runtime,true,"Ate "+action.expectedTarget()+"; hunger changed from "+before.hunger()+" to "+after.hunger()+".",false); return true; }
    private boolean equip(AgentRecord agent,GoalLessVillager body,AgentRuntime runtime,OfferedAction action) { int split=action.expectedTarget().lastIndexOf(':'); if(split<0) return false; String itemId=action.expectedTarget().substring(0,split),slotName=action.expectedTarget().substring(split+1); Optional<ItemStack> stack=inventory.stack(agent.id(),itemId); if(stack.isEmpty()) return false; EquipmentSlot slot; try { slot=EquipmentSlot.valueOf(slotName); } catch(IllegalArgumentException error) { return false; } if(!inventory.equip(agent.id(),itemId,slot.name())) return false; body.setItemSlot(slot,stack.get().copyWithCount(1)); finishMove(agent,body,runtime,true,"Equipped "+itemId+" in "+slot.name()+".",false); return true; }
    private boolean craft(AgentRecord agent,GoalLessVillager body,AgentRuntime runtime,OfferedAction action) { RecipePlanner.Plan plan=RecipePlanner.byRecipeId((ServerLevel)body.level(),inventory,agent.id(),action.expectedTarget()); if(plan==null) return false; if(plan.needsTable()&&!nearCraftingTable((ServerLevel)body.level(),body.blockPosition())) return false; if(!inventory.canAccept(agent.id(),plan.outputId(),plan.outputCount())) return false; for(AgentInventoryStore.Entry ingredient:plan.ingredients()) if(inventory.count(agent.id(),ingredient.item())<ingredient.count()) return false; for(AgentInventoryStore.Entry ingredient:plan.ingredients()) if(!inventory.remove(agent.id(),ingredient.item(),ingredient.count())) return false; if(!inventory.add(agent.id(),plan.outputId(),plan.outputCount())) return false; finishMove(agent,body,runtime,true,"Crafted "+plan.outputCount()+" "+plan.outputId()+" using "+plan.ingredients()+".",false); return true; }
    private static boolean nearCraftingTable(ServerLevel level,BlockPos origin) { for(BlockPos pos:BlockPos.betweenClosed(origin.offset(-2,-2,-2),origin.offset(2,2,2))) if(BuiltInRegistries.BLOCK.getKey(level.getBlockState(pos).getBlock()).toString().equals("minecraft:crafting_table")) return true; return false; }
    private void finishMove(AgentRecord r,GoalLessVillager body,AgentRuntime runtime,boolean success,String outcome,boolean diagnostic) { OfferedAction action=runtime.move==null?null:runtime.offeredActions.get(runtime.move.actionId()); if(body!=null) body.getNavigation().stop(); runtime.move=null; runtime.skill=null; runtime.buildPlan=null; runtime.lifecycle.finishAction(); runtime.offeredActions=Map.of(); if(!diagnostic) { runtime.event(success?"OUTCOME":"FAILURE",outcome); brain.appendFactualEvent(r.id(),r.epoch(),"OUTCOME",outcome,body==null?Map.of("success",success):factualMetadata(body,action,success,null)); } LOGGER.info("[EmergentCraft] {} {} {}: {}",r.name(),diagnostic?"movement test":"action",success?"completed":"failed",outcome); }
    private Map<String,Object> factualMetadata(GoalLessVillager body,OfferedAction action,Boolean success,Entity target) { Map<String,Object> metadata=new LinkedHashMap<>(); ServerLevel level=(ServerLevel)body.level(); metadata.put("worldTime",level.getOverworldClockTime()); metadata.put("dimension",level.dimension().identifier().toString()); metadata.put("position",Map.of("x",body.getX(),"y",body.getY(),"z",body.getZ())); if(action!=null) { metadata.put("actionKind",action.kind().toString()); if(action.kind()==OfferedAction.Kind.BREAK_BLOCK||action.kind()==OfferedAction.Kind.APPROACH_BLOCK) { if(action.expectedTarget()!=null) metadata.put("blockId",action.expectedTarget()); } else if(action.kind()==OfferedAction.Kind.PICK_UP_ITEM) { if(action.expectedTarget()!=null) metadata.put("itemId",action.expectedTarget()); } else if(action.entityId()!=null) metadata.put("entityId",action.entityId().toString()); } if(target!=null) { metadata.put("entityId",target.getUUID().toString()); metadata.put("targetName",target.getName().getString()); registry.findByEmbodiment(target.getUUID()).ifPresent(record->metadata.put("targetAgentId",record.id().toString())); } if(success!=null) metadata.put("success",success); return metadata; }
    private void syncEquipment(AgentRecord agent,GoalLessVillager body) { AgentInventoryStore.Equipment equipment=inventory.equipment(agent.id()); syncSlot(agent,body,EquipmentSlot.MAINHAND,equipment.mainHand()); syncSlot(agent,body,EquipmentSlot.OFFHAND,equipment.offHand()); syncSlot(agent,body,EquipmentSlot.HEAD,equipment.head()); syncSlot(agent,body,EquipmentSlot.CHEST,equipment.chest()); syncSlot(agent,body,EquipmentSlot.LEGS,equipment.legs()); syncSlot(agent,body,EquipmentSlot.FEET,equipment.feet()); }
    private void syncSlot(AgentRecord agent,GoalLessVillager body,EquipmentSlot slot,String itemId) { if(itemId==null) return; ItemStack stack=inventory.stack(agent.id(),itemId).orElse(ItemStack.EMPTY); if(!stack.isEmpty()&&!net.minecraft.world.item.ItemStack.isSameItem(body.getItemBySlot(slot),stack)) body.setItemSlot(slot,stack.copyWithCount(1)); }
    private void cancelRuntime(MinecraftServer server,AgentRecord r) { BodyResolution body=resolveBody(server,r); if(body.isControlled()) ((GoalLessVillager)body.entity()).getNavigation().stop(); AgentRuntime runtime=runtime(r); runtime.move=null; runtime.skill=null; runtime.buildPlan=null; runtime.lifecycle.cancel(); }
    private Optional<Vec3> findReachableTestTarget(GoalLessVillager body) { int[][] offsets={{4,0},{-4,0},{0,4},{0,-4},{3,3},{3,-3},{-3,3},{-3,-3}}; for(int[] o:offsets) { BlockPos candidate=body.blockPosition().offset(o[0],0,o[1]); Path path=body.getNavigation().createPath(candidate,0); if(path!=null&&path.canReach()) { BlockPos end=path.getTarget(); return Optional.of(new Vec3(end.getX()+0.5,end.getY(),end.getZ()+0.5)); } } return Optional.empty(); }
    private static String escape(String value) { return value.replace("\\","\\\\").replace("\"","\\\""); }
}
