import test from "node:test";
import assert from "node:assert/strict";
import { PerceptionSchema, validateDecision } from "../src/contracts.js";
import { andyCommandDocs, cleanAndyOutput, matchAndyCommand, parseAndyCommand, safePublicIntent, toAndyDecision } from "../src/andy.js";

const perception=PerceptionSchema.parse({schemaVersion:1,agentId:"4bde43d4-cbe1-49d0-8a33-9b2e8004881d",name:"Bob",epoch:3,capabilities:{playerHunger:false,inventory:true,nativeNavigation:true,blockBreaking:true,itemPickup:true},self:{position:{x:0,y:64,z:0},health:20,maxHealth:20,alive:true,onGround:true,inWater:false,onFire:false,airSupply:300,fallDistance:0,effects:[],inventory:[{item:"minecraft:bread",count:1},{item:"minecraft:oak_planks",count:4}]},environment:{dimension:"minecraft:overworld",timeOfDay:0,weather:"clear",light:10,biome:"minecraft:plains",daytime:true,temperature:0.8,downfall:0},entities:[{id:"entity:zombie",type:"minecraft:zombie",relativePosition:{x:3,y:0,z:0},distance:3,name:null,alive:true,emergentCraft:null,burning:false},{id:"entity:alice",type:"minecraft:player",relativePosition:{x:4,y:0,z:0},distance:4,name:"Alice",alive:true,emergentCraft:null,burning:false}],blocks:[{id:"block:near",type:"minecraft:oak_log",relativePosition:{x:2,y:0,z:0},distance:2,hardness:2,breakable:true,solid:true,fluid:false,position:{x:2,y:64,z:0}},{id:"block:far",type:"minecraft:oak_log",relativePosition:{x:6,y:0,z:0},distance:6,hardness:2,breakable:true,solid:true,fluid:false,position:{x:6,y:64,z:0}}],items:[{id:"item:egg",item:"minecraft:egg",count:1,relativePosition:{x:1,y:0,z:0},distance:1}],events:[],candidates:[
  {id:"wait:3",kind:"WAIT",description:"Wait."},{id:"acquire:near",kind:"ACQUIRE_BLOCK",description:"Acquire oak.",targetId:"block:near",target:{x:2,y:64,z:0}},{id:"acquire:far",kind:"ACQUIRE_BLOCK",description:"Acquire oak.",targetId:"block:far",target:{x:6,y:64,z:0}},{id:"pickup:egg",kind:"PICK_UP_ITEM",description:"Pick egg.",targetId:"item:egg"},{id:"engage:zombie",kind:"ENGAGE",description:"Engage zombie.",targetId:"entity:zombie"},{id:"approach:alice",kind:"APPROACH_ENTITY",description:"Approach Alice.",targetId:"entity:alice"},{id:"eat:bread",kind:"EAT_ITEM",description:"Eat bread.",targetId:"minecraft:bread"},{id:"place:oak",kind:"PLACE_BLOCK",description:"Place planks.",targetId:"minecraft:oak_planks",target:{x:1,y:64,z:0}},{id:"travel:home",kind:"TRAVEL",description:"Travel.",target:{x:8,y:64,z:0}},{id:"build:3",kind:"BUILD_PLAN",description:"Build."}
]});

test("Mindcraft think blocks and code never become public intent",()=>{const cleaned=cleanAndyOutput("<think>private chain</think> I want wood. !collectBlocks(\"oak_log\", 1) ```javascript\nsteal()\n```");assert.equal(cleaned.text,"I want wood. !collectBlocks(\"oak_log\", 1)");assert.equal(safePublicIntent("the user has just told me to build !newAction(\"hut\")","!newAction(\"hut\")"),"");assert.equal(safePublicIntent("const target = oak; !collectBlocks(\"oak_log\", 1)","!collectBlocks(\"oak_log\", 1)"),"");assert.equal(cleanAndyOutput("<think>unfinished").incompleteThink,true);});
test("Mindcraft-style command parsing rejects unknown commands and wrong argument counts",()=>{assert.deepEqual(parseAndyCommand("I want wood. !collectBlocks(\"oak_log\", 1)").ok,true);assert.equal(parseAndyCommand("!destroyWorld(\"x\")").ok,false);assert.equal(parseAndyCommand("!collectBlocks(\"oak_log\")").ok,false);});
test("commands resolve only currently offered visible targets and choose nearest ties",()=>{const parsed=parseAndyCommand("!collectBlocks(\"oak_log\", 1)");assert.equal(parsed.ok,true);if(parsed.ok){const match=matchAndyCommand(parsed.command,perception);assert.equal("candidate" in match&&match.candidate.id,"acquire:near");}const hidden=parseAndyCommand("!collectBlocks(\"diamond_ore\", 1)");assert.equal(hidden.ok,true);if(hidden.ok)assert.equal("error" in matchAndyCommand(hidden.command,perception),true);});
test("attack, consume, and coordinates resolve only exact offered authority",()=>{for(const [text,id] of [["!attack(\"zombie\")","engage:zombie"],["!consume(\"bread\")","eat:bread"],["!goToCoordinates(8, 64, 0, 2)","travel:home"]] as const){const parsed=parseAndyCommand(text);assert.equal(parsed.ok,true);if(parsed.ok){const match=matchAndyCommand(parsed.command,perception);assert.equal("candidate" in match&&match.candidate.id,id);}}for(const text of ["!attack(\"creeper\")","!consume(\"apple\")","!goToCoordinates(999, 64, 999, 2)"]){const parsed=parseAndyCommand(text);assert.equal(parsed.ok,true);if(parsed.ok)assert.equal("error" in matchAndyCommand(parsed.command,perception),true);}});
test("canonical command wins over unrelated public text",()=>{const result=toAndyDecision("I will travel. !collectDrops(\"egg\", 1)",perception);assert.equal("decision" in result,true);if("decision" in result){assert.equal(result.decision.actionId,"pickup:egg");assert.equal(validateDecision(result.decision,perception).actionId,"pickup:egg");}});
test("newAction is inert unless a build candidate exists and code is rejected",()=>{const parsed=parseAndyCommand("!newAction(\"Build a tiny shelter\")");assert.equal(parsed.ok,true);if(parsed.ok)assert.equal("candidate" in matchAndyCommand(parsed.command,perception),true);const code=parseAndyCommand("!newAction(\"function hack() {}\")");assert.equal(code.ok,false);const noBuild=PerceptionSchema.parse({...perception,candidates:perception.candidates.filter(value=>value.kind!=="BUILD_PLAN")});if(parsed.ok)assert.equal("error" in matchAndyCommand(parsed.command,noBuild),true);});
test("dynamic docs are semantic commands rather than candidate indexes",()=>{const docs=andyCommandDocs(perception);assert.match(docs,/collectBlocks/);assert.match(docs,/collectDrops/);assert.match(docs,/goToCoordinates\(8, 64, 0, 2\)/);assert.doesNotMatch(docs,/choice/);});
