import test from "node:test";
import assert from "node:assert/strict";
import { PerceptionSchema, validateDecision } from "../src/contracts.js";
import { andyCommandDocs, andyInfoResult, cleanAndyOutput, matchAndyCommand, parseAndyCommand, safePublicIntent, toAndyDecision } from "../src/andy.js";
import { OllamaProvider } from "../src/provider.js";

const perception=PerceptionSchema.parse({schemaVersion:1,agentId:"4bde43d4-cbe1-49d0-8a33-9b2e8004881d",name:"Bob",epoch:3,capabilities:{playerHunger:false,inventory:true,nativeNavigation:true,blockBreaking:true,itemPickup:true},self:{position:{x:0,y:64,z:0},health:20,maxHealth:20,alive:true,onGround:true,inWater:false,onFire:false,airSupply:300,fallDistance:0,effects:[],inventory:[{item:"minecraft:bread",count:1},{item:"minecraft:oak_planks",count:4}]},environment:{dimension:"minecraft:overworld",timeOfDay:0,weather:"clear",light:10,biome:"minecraft:plains",daytime:true,temperature:0.8,downfall:0},entities:[{id:"entity:zombie",type:"minecraft:zombie",relativePosition:{x:3,y:0,z:0},distance:3,name:null,alive:true,emergentCraft:null,burning:false},{id:"entity:alice",type:"minecraft:player",relativePosition:{x:4,y:0,z:0},distance:4,name:"Alice",alive:true,emergentCraft:null,burning:false}],blocks:[{id:"block:near",type:"minecraft:oak_log",relativePosition:{x:2,y:0,z:0},distance:2,hardness:2,breakable:true,solid:true,fluid:false,position:{x:2,y:64,z:0}},{id:"block:far",type:"minecraft:oak_log",relativePosition:{x:6,y:0,z:0},distance:6,hardness:2,breakable:true,solid:true,fluid:false,position:{x:6,y:64,z:0}}],items:[{id:"item:egg",item:"minecraft:egg",count:1,relativePosition:{x:1,y:0,z:0},distance:1}],events:[],candidates:[
  {id:"wait:3",kind:"WAIT",description:"Wait."},{id:"acquire:near",kind:"ACQUIRE_BLOCK",description:"Acquire oak.",targetId:"block:near",target:{x:2,y:64,z:0}},{id:"acquire:far",kind:"ACQUIRE_BLOCK",description:"Acquire oak.",targetId:"block:far",target:{x:6,y:64,z:0}},{id:"pickup:egg",kind:"PICK_UP_ITEM",description:"Pick egg.",targetId:"item:egg"},{id:"engage:zombie",kind:"ENGAGE",description:"Engage zombie.",targetId:"entity:zombie"},{id:"approach:alice",kind:"APPROACH_ENTITY",description:"Approach Alice.",targetId:"entity:alice"},{id:"eat:bread",kind:"EAT_ITEM",description:"Eat bread.",targetId:"minecraft:bread"},{id:"place:oak",kind:"PLACE_BLOCK",description:"Place planks.",targetId:"minecraft:oak_planks",target:{x:1,y:64,z:0}},{id:"travel:home",kind:"TRAVEL",description:"Travel.",target:{x:8,y:64,z:0}},{id:"build:3",kind:"BUILD_PLAN",description:"Build."}
]});

test("Mindcraft think blocks and code never become public intent",()=>{const cleaned=cleanAndyOutput("<think>private chain</think> I want wood. !collectBlocks(\"oak_log\", 1) ```javascript\nsteal()\n```");assert.equal(cleaned.text,"I want wood. !collectBlocks(\"oak_log\", 1)");assert.equal(safePublicIntent("the user has just told me to build !newAction(\"hut\")","!newAction(\"hut\")"),"");assert.equal(safePublicIntent("const target = oak; !collectBlocks(\"oak_log\", 1)","!collectBlocks(\"oak_log\", 1)"),"");assert.equal(cleanAndyOutput("<think>unfinished").incompleteThink,true);});
test("Mindcraft-style command parsing rejects unknown commands and wrong argument counts",()=>{assert.deepEqual(parseAndyCommand("I want wood. !collectBlocks(\"oak_log\", 1)").ok,true);assert.equal(parseAndyCommand("!destroyWorld(\"x\")").ok,false);assert.equal(parseAndyCommand("!collectBlocks(\"oak_log\")").ok,false);});
test("commands resolve only currently offered visible targets and choose nearest ties",()=>{const parsed=parseAndyCommand("!collectBlocks(\"oak_log\", 1)");assert.equal(parsed.ok,true);if(parsed.ok){const match=matchAndyCommand(parsed.command,perception);assert.equal("candidate" in match&&match.candidate.id,"acquire:near");}const hidden=parseAndyCommand("!collectBlocks(\"diamond_ore\", 1)");assert.equal(hidden.ok,true);if(hidden.ok)assert.equal("error" in matchAndyCommand(hidden.command,perception),true);});
test("attack, consume, and coordinates resolve only exact offered authority",()=>{for(const [text,id] of [["!attack(\"zombie\")","engage:zombie"],["!consume(\"bread\")","eat:bread"],["!goToCoordinates(8, 64, 0, 2)","travel:home"]] as const){const parsed=parseAndyCommand(text);assert.equal(parsed.ok,true);if(parsed.ok){const match=matchAndyCommand(parsed.command,perception);assert.equal("candidate" in match&&match.candidate.id,id);}}for(const text of ["!attack(\"creeper\")","!consume(\"apple\")","!goToCoordinates(999, 64, 999, 2)"]){const parsed=parseAndyCommand(text);assert.equal(parsed.ok,true);if(parsed.ok)assert.equal("error" in matchAndyCommand(parsed.command,perception),true);}});
test("canonical command wins over unrelated public text",()=>{const result=toAndyDecision("I will travel. !collectDrops(\"egg\", 1)",perception);assert.equal("decision" in result,true);if("decision" in result){assert.equal(result.decision.actionId,"pickup:egg");assert.equal(validateDecision(result.decision,perception).actionId,"pickup:egg");}});
test("newAction is inert unless a build candidate exists and code is rejected",()=>{const parsed=parseAndyCommand("!newAction(\"Build a tiny shelter\")");assert.equal(parsed.ok,true);if(parsed.ok)assert.equal("candidate" in matchAndyCommand(parsed.command,perception),true);const code=parseAndyCommand("!newAction(\"function hack() {}\")");assert.equal(code.ok,false);const noBuild=PerceptionSchema.parse({...perception,candidates:perception.candidates.filter(value=>value.kind!=="BUILD_PLAN")});if(parsed.ok)assert.equal("error" in matchAndyCommand(parsed.command,noBuild),true);});
test("dynamic docs are semantic commands rather than candidate indexes",()=>{const docs=andyCommandDocs(perception);assert.match(docs,/collectBlocks/);assert.match(docs,/collectDrops/);assert.match(docs,/goToCoordinates\(8, 64, 0, 2\)/);assert.doesNotMatch(docs,/choice/);});
test("information commands expose only the supplied snapshot and offered crafts",()=>{const command=(text:string)=>{const parsed=parseAndyCommand(text);if(!parsed.ok)throw new Error(parsed.error);return parsed.command;};const stats=andyInfoResult(command("!stats()"),perception),inventory=andyInfoResult(command("!inventory()"),perception),blocks=andyInfoResult(command("!nearbyBlocks()"),perception),entities=andyInfoResult(command("!nearbyEntities()"),perception),crafts=andyInfoResult(command("!craftable()"),perception);assert.match(stats,/health 20\/20/);assert.match(inventory,/bread x1/);assert.match(blocks,/oak_log x2/);assert.match(entities,/Alice/);assert.match(crafts,/none/);assert.doesNotMatch(`${stats}${inventory}${blocks}${entities}${crafts}`,/diamond|hidden/i);});
test("safe compatibility searches and coordinate tolerance select only offered candidates",()=>{for(const [text,id] of [["!searchForEntity(\"player\", 64)","approach:alice"],["!searchForBlock(\"oak_log\", 100)","acquire:near"],["!goToCoordinates(9, 64, 0, 2)","travel:home"]] as const){const parsed=parseAndyCommand(text);assert.equal(parsed.ok,true);if(parsed.ok){const match=matchAndyCommand(parsed.command,perception);assert.equal("candidate" in match&&match.candidate.id,id);}}for(const text of ["!searchForEntity(\"cow\", 64)","!searchForBlock(\"diamond_ore\", 100)","!goToCoordinates(10, 64, 0, 2)"]){const parsed=parseAndyCommand(text);assert.equal(parsed.ok,true);if(parsed.ok)assert.equal("error" in matchAndyCommand(parsed.command,perception),true);}assert.equal(parseAndyCommand("!goToPlayer(\"Alice\", -1)").ok,false);});
test("bounded provider correction retries prose and info locally without retaining intermediate output",async()=>{const original=globalThis.fetch;const calls:unknown[]=[];const replies=["I should look around.","!nearbyEntities()","!goToPlayer(\"Alice\", 3)"];globalThis.fetch=(async (_input,init)=>{calls.push(JSON.parse(String(init?.body)));return new Response(JSON.stringify({message:{content:replies.shift()}}),{status:200,headers:{"content-type":"application/json"}});}) as typeof fetch;try{const provider=new OllamaProvider("http://unused",1000,"0",3);const decision=await provider.decide(perception,{working:[],recalled:[],social:[],knowledge:[],beliefs:[],reflections:[],projects:[],chapters:[],self:{intent:"",updatedAt:new Date(0).toISOString()},contextChars:0},{model:"andy",profile:"minecraft-andy4"});assert.equal(decision.actionId,"approach:alice");assert.equal(calls.length,3);const finalMessages=(calls[2] as {messages:{role:string;content:string}[]}).messages;assert.equal(finalMessages.some(message=>message.content.includes("I should look around.")),true);assert.equal(finalMessages.some(message=>message.content.includes("perceived entities")),true);assert.equal(provider.lastAndyDiagnostic?.rawCleaned,"!goToPlayer(\"Alice\", 3)");}finally{globalThis.fetch=original;}});
test("unknown command is corrected in the same provider chat before a valid action",async()=>{const original=globalThis.fetch;let calls=0;const replies=["!destroyWorld(\"x\")","!stay(5)"];globalThis.fetch=(async (_input,init)=>{calls++;const body=JSON.parse(String(init?.body)) as {messages:{content:string}[]};if(calls===2)assert.equal(body.messages.some(message=>message.content.includes("Unknown command: !destroyWorld.")),true);return new Response(JSON.stringify({message:{content:replies.shift()}}),{status:200,headers:{"content-type":"application/json"}});}) as typeof fetch;try{const decision=await new OllamaProvider("http://unused",1000,"0",3).decide(perception,{working:[],recalled:[],social:[],knowledge:[],beliefs:[],reflections:[],projects:[],chapters:[],self:{intent:"",updatedAt:new Date(0).toISOString()},contextChars:0},{model:"andy",profile:"minecraft-andy4"});assert.equal(decision.actionId,"wait:3");assert.equal(calls,2);}finally{globalThis.fetch=original;}});
test("bounded provider stops after its hard maximum",async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=(async ()=>{calls++;return new Response(JSON.stringify({message:{content:"no command"}}),{status:200,headers:{"content-type":"application/json"}});}) as typeof fetch;try{await assert.rejects(new OllamaProvider("http://unused",1000,"0",99).decide(perception,{working:[],recalled:[],social:[],knowledge:[],beliefs:[],reflections:[],projects:[],chapters:[],self:{intent:"",updatedAt:new Date(0).toISOString()},contextChars:0},{model:"andy",profile:"minecraft-andy4"}),/ANDY_COMMAND_REJECTED/);assert.equal(calls,3);}finally{globalThis.fetch=original;}});
