import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { MemoryStore } from "../src/memory.js";
import { PerceptionSchema } from "../src/contracts.js";

const rowan="4bde43d4-cbe1-49d0-8a33-9b2e8004881d", alice="9bde43d4-cbe1-49d0-8a33-9b2e8004881d";
const view=(entities:unknown[]=[])=>PerceptionSchema.parse({schemaVersion:1,agentId:rowan,name:"Rowan",epoch:9,capabilities:{playerHunger:false,inventory:true,nativeNavigation:true,blockBreaking:true,itemPickup:true},self:{position:{x:10,y:64,z:10},health:20,maxHealth:20,alive:true,onGround:true,inWater:false,onFire:false,airSupply:300,fallDistance:0,effects:[],inventory:[]},environment:{dimension:"minecraft:overworld",timeOfDay:1000,weather:"clear",light:10,biome:"minecraft:plains",daytime:true,temperature:0.8,downfall:0},entities,blocks:[],items:[],events:[],candidates:[{id:"wait:9",kind:"WAIT",description:"Wait."}]});

test("an old Alice episode survives fifty unrelated events and is recalled when Alice is seen",async()=>{const store=new MemoryStore(await mkdtemp(join(tmpdir(),"ec-continuity-")));await store.appendEpisode(rowan,{at:"2026-01-01T00:00:00.000Z",epoch:1,kind:"SPEECH",text:"Alice said hello near the river.",metadata:{targetAgentId:alice,targetName:"Alice",dimension:"minecraft:overworld",position:{x:10,y:64,z:10}}});for(let index=0;index<50;index++)await store.appendEpisode(rowan,{at:`2026-01-02T00:${String(index%60).padStart(2,"0")}:00.000Z`,epoch:index+2,kind:"OUTCOME",text:`Unrelated action ${index}.`});const context=await store.context(view([{id:`entity:${alice}`,type:"minecraft:player",relativePosition:{x:2,y:0,z:0},distance:2,name:"Alice",alive:true,emergentCraft:{agentId:alice,name:"Alice"}}]));assert.ok([...context.social,...context.recalled].some(event=>event.text.includes("Alice said hello")));});

test("spatial and objective knowledge are evidence-derived and agent-local",async()=>{const store=new MemoryStore(await mkdtemp(join(tmpdir(),"ec-knowledge-")));const perception=view();await store.observe(perception);await store.appendEpisode(rowan,{at:"2026-01-01T00:00:00.000Z",epoch:1,kind:"OUTCOME",text:"Something happened here.",metadata:{dimension:"minecraft:overworld",position:{x:11,y:64,z:10}}});const context=await store.context(perception);assert.ok([...context.working,...context.recalled].some(event=>event.text.includes("Something happened")));assert.ok((await store.knowledge(rowan)).biomes["minecraft:plains"]);const aliceContext=await store.context({...perception,agentId:alice});assert.equal(aliceContext.recalled.length,0);});

test("context budget is enforced while salient relevant history remains",async()=>{const store=new MemoryStore(await mkdtemp(join(tmpdir(),"ec-budget-")));await store.appendEpisode(rowan,{at:"2026-01-01T00:00:00.000Z",epoch:1,kind:"DAMAGE",text:"Alice was present when Rowan was hurt."});for(let index=0;index<80;index++)await store.appendEpisode(rowan,{at:"2026-01-02T00:00:00.000Z",epoch:index+2,kind:"OUTCOME",text:`${"trivia ".repeat(25)}${index}`});const context=await store.context(view([{id:`entity:${alice}`,type:"minecraft:player",relativePosition:{x:1,y:0,z:0},distance:1,name:"Alice",alive:true,emergentCraft:{agentId:alice,name:"Alice"}}]),1200);assert.ok(context.contextChars<=1200);assert.ok([...context.social,...context.recalled].some(event=>event.text.includes("was hurt")),JSON.stringify(context));});
