import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { EmbodimentEventSchema, PerceptionSchema } from "../src/contracts.js";
import { MemoryStore } from "../src/memory.js";
import { DecisionOutputFormat } from "../src/provider.js";

const id="4bde43d4-cbe1-49d0-8a33-9b2e8004881d";
const perception=PerceptionSchema.parse({schemaVersion:1,agentId:id,name:"Rowan",epoch:1,capabilities:{playerHunger:false,inventory:true,nativeNavigation:true,blockBreaking:true,itemPickup:true},self:{position:{x:0,y:64,z:0},health:20,maxHealth:20,alive:true,onGround:true,inWater:false,onFire:false,airSupply:300,fallDistance:0,effects:[],inventory:[]},environment:{dimension:"minecraft:overworld",timeOfDay:0,weather:"clear",light:10,biome:"minecraft:plains",daytime:true,temperature:0.8,downfall:0},entities:[],blocks:[],items:[],events:[],candidates:[{id:"wait:1",kind:"WAIT",description:"Wait."}]});
const store=async(prefix:string)=>new MemoryStore(await mkdtemp(join(tmpdir(),prefix)));
const episode=(text:string,epoch:number,worldTime?:number)=>({at:"2026-01-01T00:00:00.000Z",epoch,kind:"OUTCOME" as const,text,metadata:worldTime===undefined?undefined:{worldTime}});

test("newer equal relevant episodes rank ahead of older ones",async()=>{const memory=await store("ec-recall-recency-");await memory.appendEpisode(id,episode("Reached the river.",1));await memory.appendEpisode(id,episode("Reached the river.",2));for(let index=0;index<6;index++)await memory.appendEpisode(id,episode(`unrelated ${index}`,index+3));const context=await memory.context({...perception,blocks:[{position:{x:1,y:64,z:1},type:"minecraft:river"}]});assert.deepEqual(context.recalled.slice(0,2).map(fact=>fact.epoch),[2,1]);});

test("an active project recalls an old project-relevant episode after unrelated history",async()=>{const memory=await store("ec-recall-project-");await memory.writeProjects(id,[{id:"hill",title:"Investigate the wooded hill",purpose:"Understand the river crossing",progress:"Reach the hill.",status:"ACTIVE",createdAt:"2026-01-01T00:00:00.000Z",lastUpdatedAt:"2026-01-01T00:00:00.000Z"}]);await memory.appendEpisode(id,episode("I reached the wooded hill but could not cross the river.",1));for(let index=0;index<50;index++)await memory.appendEpisode(id,episode(`unrelated observation ${index}`,index+2));const context=await memory.context(perception);assert.ok(context.recalled.some(fact=>fact.text.includes("wooded hill")));});

test("subjective retrieval cues never create factual episodes or knowledge",async()=>{const memory=await store("ec-recall-boundary-");await memory.writeState(id,{intent:"Find a secret diamond palace",selfDescription:"I remember imagined treasure",updatedAt:"2026-01-01T00:00:00.000Z"});await memory.writeBeliefs(id,[{id:"belief",belief:"A diamond palace exists",confidence:0.2,createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z"}]);await memory.observe(perception);const beforeEpisodes=await memory.readEpisodes(id,Number.MAX_SAFE_INTEGER),beforeKnowledge=JSON.stringify(await memory.knowledge(id));await memory.context(perception);assert.equal((await memory.readEpisodes(id,Number.MAX_SAFE_INTEGER)).length,beforeEpisodes.length);assert.equal(JSON.stringify(await memory.knowledge(id)),beforeKnowledge);});

test("Minecraft world time is presented relative to the latest authoritative event",async()=>{const memory=await store("ec-recall-time-");await memory.writeProjects(id,[{id:"river",title:"Return to river",purpose:"Remember the river",progress:"",status:"ACTIVE",createdAt:"2026-01-01T00:00:00.000Z",lastUpdatedAt:"2026-01-01T00:00:00.000Z"}]);await memory.appendEpisode(id,episode("Reached the river.",1,24000));for(let index=0;index<6;index++)await memory.appendEpisode(id,episode(`later ${index}`,index+2,48000));const context=await memory.context(perception);assert.equal(context.recalled.find(fact=>fact.text.includes("river"))?.relativeTime,"1 Minecraft day ago");});

test("large subjective sections are clipped before the configured context budget",async()=>{const memory=await store("ec-recall-budget-");const huge="long subjective text ".repeat(300);await memory.writeState(id,{intent:huge,selfDescription:huge,preferences:[huge,huge],concerns:[huge],aspirations:[huge],updatedAt:"2026-01-01T00:00:00.000Z"});await memory.writeProjects(id,[{id:"large",title:huge,purpose:huge,progress:huge,status:"ACTIVE",createdAt:"2026-01-01T00:00:00.000Z",lastUpdatedAt:"2026-01-01T00:00:00.000Z"}]);await memory.writeBeliefs(id,[{id:"large",belief:huge,confidence:0.5,createdAt:"2026-01-01T00:00:00.000Z",updatedAt:"2026-01-01T00:00:00.000Z"}]);await memory.appendChapter(id,{id:"large",startedAt:"2026-01-01T00:00:00.000Z",endedAt:"2026-01-01T00:00:00.000Z",summary:huge,topics:[huge],people:[huge],sourceStart:0,sourceEnd:1,createdAt:"2026-01-01T00:00:00.000Z"});const context=await memory.context(perception,1200);assert.equal(JSON.stringify(context).length,context.contextChars);assert.ok(context.contextChars<=1200,JSON.stringify(context));});

test("factual event contract accepts populated authoritative metadata",()=>{const event=EmbodimentEventSchema.parse({agentId:id,epoch:1,kind:"ACTION",text:"Attempted SPEAK.",metadata:{worldTime:48000,dimension:"minecraft:overworld",position:{x:1,y:64,z:2},actionKind:"SPEAK",blockId:"minecraft:oak_log",itemId:"minecraft:apple",entityId:"entity-uuid",targetAgentId:"6fd3f3bd-31e7-4a54-a4a4-48b16d7ba64e",targetName:"Alice",success:true}});assert.equal(event.metadata?.targetName,"Alice");});

test("Ollama output schema describes nested subjective updates",()=>{const project=DecisionOutputFormat.properties.projectUpdate;assert.deepEqual(project.properties.operation.enum,["KEEP","CREATE","UPDATE","COMPLETE","ABANDON","PAUSE"]);assert.equal(DecisionOutputFormat.properties.selfUpdate.properties.preferences.maxItems,6);assert.deepEqual(DecisionOutputFormat.properties.beliefUpdate.properties.operation.enum,["KEEP","CREATE","UPDATE","REMOVE"]);});
