import "dotenv/config";
import { resolve } from "node:path";
import { createBrainServer } from "./service.js";
import { MemoryStore } from "./memory.js";
import { DeterministicProvider, OllamaProvider, OpenAICompatibleProvider, resolveOllamaModel } from "./provider.js";
import { AsyncQueue } from "./queue.js";
import { ModelConfigStore } from "./model-config.js";
const cfg={host:process.env.HOST??"127.0.0.1",port:Number(process.env.PORT??3847),ollamaUrl:process.env.OLLAMA_BASE_URL??"http://127.0.0.1:11434",ollamaModel:process.env.OLLAMA_MODEL??"",openaiUrl:process.env.LOCAL_OPENAI_BASE_URL??"http://127.0.0.1:1234/v1",openaiModel:process.env.LOCAL_OPENAI_MODEL??"",openaiKey:process.env.LOCAL_OPENAI_API_KEY??"",timeout:Number(process.env.LOCAL_OPENAI_TIMEOUT_MS??process.env.OLLAMA_REQUEST_TIMEOUT_MS??120000),keepAlive:process.env.OLLAMA_KEEP_ALIVE??"15m",provider:process.env.EC_PROVIDER??"ollama",profile:process.env.EC_MODEL_PROFILE??"generic",maxConcurrent:Number(process.env.OLLAMA_MAX_CONCURRENT??1)};
const root=resolve(process.env.EC_MEMORY_DIR??"data"),ollamaModel=cfg.provider==="ollama"?(cfg.ollamaModel||await resolveOllamaModel(cfg.ollamaUrl,"")):(cfg.ollamaModel||"");
const providers={mock:new DeterministicProvider(),ollama:new OllamaProvider(cfg.ollamaUrl,cfg.timeout,cfg.keepAlive),"openai-compatible":new OpenAICompatibleProvider(cfg.openaiUrl,cfg.timeout,cfg.openaiKey)} as const;
const selected=cfg.provider==="mock"?providers.mock:cfg.provider==="openai-compatible"?providers["openai-compatible"]:providers.ollama;
const defaultModel=cfg.provider==="openai-compatible"?cfg.openaiModel:cfg.provider==="mock"?"deterministic":ollamaModel;
const configs=new ModelConfigStore(root,{provider:cfg.provider as "ollama"|"openai-compatible"|"mock",model:defaultModel,profile:cfg.profile as import("./profiles.js").ModelProfileId});
createBrainServer(selected,new MemoryStore(root),new AsyncQueue(cfg.maxConcurrent),providers,configs).listen(cfg.port,cfg.host,()=>console.log(`[EmergentCraft Brain] loopback http://${cfg.host}:${cfg.port}; default=${cfg.provider}/${defaultModel}/${cfg.profile}; queue=${cfg.maxConcurrent}`));
