import "dotenv/config";
import { resolve } from "node:path";
import { createBrainServer } from "./service.js";
import { MemoryStore } from "./memory.js";
import { DeterministicProvider, OllamaProvider, OpenAICompatibleProvider, resolveOllamaModel, resolveOpenAICompatibleModel } from "./provider.js";
import { AsyncQueue } from "./queue.js";
const cfg={host:process.env.HOST??"127.0.0.1",port:Number(process.env.PORT??3847),provider:process.env.EC_PROVIDER??"ollama",profile:process.env.EC_MODEL_PROFILE??"minecraft-andy4",ollamaUrl:process.env.OLLAMA_BASE_URL??"http://127.0.0.1:11434",ollamaModel:process.env.OLLAMA_MODEL??"sweaterdog/andy-4:micro-q8_0",openaiUrl:process.env.LOCAL_OPENAI_BASE_URL??"http://127.0.0.1:1234/v1",openaiModel:process.env.LOCAL_OPENAI_MODEL??"",openaiKey:process.env.LOCAL_OPENAI_API_KEY??"",timeout:Number(process.env.LOCAL_OPENAI_TIMEOUT_MS??process.env.OLLAMA_REQUEST_TIMEOUT_MS??120000),keepAlive:process.env.OLLAMA_KEEP_ALIVE??"15m",maxConcurrent:Number(process.env.OLLAMA_MAX_CONCURRENT??1),andyActionAttempts:Number(process.env.ANDY_ACTION_ATTEMPTS??3)};
const ollama=new OllamaProvider(cfg.ollamaUrl,cfg.timeout,cfg.keepAlive,cfg.andyActionAttempts),openai=new OpenAICompatibleProvider(cfg.openaiUrl,cfg.timeout,cfg.openaiKey),provider=cfg.provider==="mock"?new DeterministicProvider():cfg.provider==="openai-compatible"?openai:ollama;
const model=cfg.provider==="ollama"?await resolveOllamaModel(cfg.ollamaUrl,cfg.ollamaModel):cfg.provider==="openai-compatible"?await resolveOpenAICompatibleModel(openai,cfg.openaiModel):"deterministic";
const config={model,profile:cfg.profile as import("./profiles.js").ModelProfileId};
console.log(`[EmergentCraft Brain]\nProvider: ${cfg.provider}\nModel: ${model}\nProfile: ${cfg.profile}\nConcurrency: ${cfg.maxConcurrent}\nEndpoint: ${cfg.provider==="ollama"?cfg.ollamaUrl:cfg.openaiUrl}`);
createBrainServer(provider,config,new MemoryStore(resolve(process.env.EC_MEMORY_DIR??"data")),new AsyncQueue(cfg.maxConcurrent)).listen(cfg.port,cfg.host,()=>console.log(`[EmergentCraft Brain] listening on http://${cfg.host}:${cfg.port}`));
