import { appendFile, mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { EmbodimentEvent, Perception } from "./contracts.js";

export type EventMetadata={worldTime?:number;dimension?:string;position?:{x:number;y:number;z:number};actionKind?:string;blockId?:string;itemId?:string;entityId?:string;targetAgentId?:string;targetName?:string;success?:boolean};
export type EpisodicFact={schemaVersion?:1;id?:string;at:string;epoch:number;kind:"ACTION"|"OUTCOME"|"DEATH"|"SPEECH"|"DAMAGE"|"ACQUISITION";text:string;metadata?:EventMetadata;salience?:number};
export type Reflection={at:string;text:string;salience?:number};
export type SubjectiveState={goals?:string[];intent:string;selfDescription?:string;preferences?:string[];concerns?:string[];aspirations?:string[];updatedAt:string};
export type Project={id:string;title:string;purpose:string;status:"ACTIVE"|"COMPLETED"|"ABANDONED"|"PAUSED";createdAt:string;lastUpdatedAt:string;progress:string};
export type Belief={id:string;belief:string;confidence:number;createdAt:string;updatedAt:string};
export type KnowledgeEntry={id:string;firstSeen:string;lastSeen:string;encounters:number;dimension?:string;position?:{x:number;y:number;z:number};name?:string};
export type Knowledge={dimensions:Record<string,KnowledgeEntry>;biomes:Record<string,KnowledgeEntry>;entityTypes:Record<string,KnowledgeEntry>;blockTypes:Record<string,KnowledgeEntry>;itemTypes:Record<string,KnowledgeEntry>;people:Record<string,KnowledgeEntry>};
export type Chapter={id:string;startedAt:string;endedAt:string;summary:string;topics:string[];people:string[];sourceStart:number;sourceEnd:number;createdAt:string};
export type MemoryMeta={schemaVersion:1;consolidatedUntil:number};
export type MemoryContext={working:EpisodicFact[];recalled:EpisodicFact[];social:EpisodicFact[];knowledge:string[];beliefs:Belief[];reflections:Reflection[];projects:Project[];chapters:Chapter[];self:SubjectiveState;contextChars:number};

const state=():SubjectiveState=>({goals:[],intent:"",updatedAt:new Date(0).toISOString()});
const knowledge=():Knowledge=>({dimensions:{},biomes:{},entityTypes:{},blockTypes:{},itemTypes:{},people:{}});
const salience=(kind:EpisodicFact["kind"])=>kind==="DEATH"?1:kind==="DAMAGE"?0.8:kind==="SPEECH"?0.65:kind==="ACQUISITION"?0.55:kind==="OUTCOME"?0.35:0.25;
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
const distance=(a:{x:number;y:number;z:number},b:{x:number;y:number;z:number})=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);
const relative=(time:string)=>{const minutes=Math.max(0,Math.floor((Date.now()-Date.parse(time))/60000));return minutes<60?`${minutes} minutes ago`:`${Math.floor(minutes/60)} hours ago`;};

/** Per-agent durable memory; legacy episode/reflection/self data remains readable. */
export class MemoryStore {
  private readonly episodeCache=new Map<string,EpisodicFact[]>();
  constructor(private readonly root:string){}
  private dir(id:string){return join(this.root,id);} private path(id:string,file:string){return join(this.dir(id),file);}
  private async json<T>(id:string,file:string,fallback:T):Promise<T>{try{return JSON.parse(await readFile(this.path(id,file),"utf8")) as T;}catch{return fallback;}}
  private async atomic(id:string,file:string,value:unknown){await mkdir(this.dir(id),{recursive:true});const target=this.path(id,file),temp=`${target}.tmp`;await writeFile(temp,JSON.stringify(value,null,2),"utf8");await rename(temp,target);}
  async readEpisodes(id:string,limit=12){let all=this.episodeCache.get(id);if(!all){try{all=(await readFile(this.path(id,"episodes.jsonl"),"utf8")).split("\n").filter(Boolean).flatMap((line,index)=>{try{const raw=JSON.parse(line) as EpisodicFact;return[{...raw,id:raw.id??`legacy-${index}`,schemaVersion:1,salience:clamp(raw.salience??salience(raw.kind))}];}catch{return[];}});}catch{all=[];}this.episodeCache.set(id,all);}return limit>=all.length?[...all]:all.slice(-limit);}
  async appendEpisode(id:string,fact:EpisodicFact){const episodes=await this.readEpisodes(id,Number.MAX_SAFE_INTEGER);const next={...fact,schemaVersion:1 as const,id:fact.id??`${Date.now()}-${episodes.length}`,salience:clamp(fact.salience??salience(fact.kind))};const prior=episodes.at(-1);if(prior&&prior.kind===next.kind&&prior.text===next.text&&next.salience<=0.3)return;await mkdir(this.dir(id),{recursive:true});await appendFile(this.path(id,"episodes.jsonl"),JSON.stringify(next)+"\n","utf8");episodes.push(next);this.episodeCache.set(id,episodes);}
  async appendEmbodiment(id:string,event:EmbodimentEvent){await this.appendEpisode(id,{at:new Date().toISOString(),epoch:event.epoch,kind:event.kind,text:event.text,metadata:event.metadata,salience:salience(event.kind)});}
  async appendReflection(id:string,value:Reflection){await mkdir(this.dir(id),{recursive:true});await appendFile(this.path(id,"reflections.jsonl"),JSON.stringify(value)+"\n","utf8");}
  async readReflections(id:string,limit=4){try{return(await readFile(this.path(id,"reflections.jsonl"),"utf8")).split("\n").filter(Boolean).slice(-limit).flatMap(line=>{try{return[JSON.parse(line) as Reflection];}catch{return[];}});}catch{return[];}}
  async readState(id:string){const value=await this.json(id,"self.json",state());return{...state(),...value,goals:value.goals??[],preferences:value.preferences??[],concerns:value.concerns??[],aspirations:value.aspirations??[]};}
  async writeState(id:string,value:SubjectiveState){await this.atomic(id,"self.json",value);}
  async projects(id:string){return this.json<Project[]>(id,"projects.json",[]);} async writeProjects(id:string,value:Project[]){await this.atomic(id,"projects.json",value.slice(0,12));}
  async beliefs(id:string){return this.json<Belief[]>(id,"beliefs.json",[]);} async writeBeliefs(id:string,value:Belief[]){await this.atomic(id,"beliefs.json",value.slice(0,16));}
  async knowledge(id:string){return{...knowledge(),...(await this.json<Partial<Knowledge>>(id,"knowledge.json",{}))};} async writeKnowledge(id:string,value:Knowledge){await this.atomic(id,"knowledge.json",value);}
  async chapters(id:string,limit=8){try{return(await readFile(this.path(id,"autobiography.jsonl"),"utf8")).split("\n").filter(Boolean).slice(-limit).flatMap(line=>{try{return[JSON.parse(line) as Chapter];}catch{return[];}});}catch{return[];}}
  async appendChapter(id:string,value:Chapter){await mkdir(this.dir(id),{recursive:true});await appendFile(this.path(id,"autobiography.jsonl"),JSON.stringify(value)+"\n","utf8");}
  async meta(id:string){return this.json<MemoryMeta>(id,"memory-meta.json",{schemaVersion:1,consolidatedUntil:0});} async writeMeta(id:string,value:MemoryMeta){await this.atomic(id,"memory-meta.json",value);}
  async observe(perception:Perception){const now=new Date().toISOString(),all=await this.knowledge(perception.agentId);const hit=(bucket:Record<string,KnowledgeEntry>,id:string,extra:Partial<KnowledgeEntry>={})=>{const old=bucket[id];bucket[id]={...old,...extra,id,firstSeen:old?.firstSeen??now,lastSeen:now,encounters:(old?.encounters??0)+1};};const local={dimension:perception.environment.dimension,position:perception.self.position};hit(all.dimensions,perception.environment.dimension,local);hit(all.biomes,perception.environment.biome,local);for(const block of perception.blocks)hit(all.blockTypes,block.type,{dimension:local.dimension,position:block.position});for(const item of perception.items)hit(all.itemTypes,item.item,local);for(const entity of perception.entities){hit(all.entityTypes,entity.type,local);if(entity.name)hit(all.people,entity.emergentCraft?.agentId??`name:${entity.name}`,{name:entity.name,dimension:local.dimension,position:{x:local.position.x+entity.relativePosition.x,y:local.position.y+entity.relativePosition.y,z:local.position.z+entity.relativePosition.z}});}await this.writeKnowledge(perception.agentId,all);}
  async context(perception:Perception,budget=6000):Promise<MemoryContext>{const [episodes,reflections,self,allProjects,allBeliefs,allKnowledge,chapters]=await Promise.all([this.readEpisodes(perception.agentId,Number.MAX_SAFE_INTEGER),this.readReflections(perception.agentId,8),this.readState(perception.agentId),this.projects(perception.agentId),this.beliefs(perception.agentId),this.knowledge(perception.agentId),this.chapters(perception.agentId,3)]);const terms=new Set([perception.environment.dimension,perception.environment.biome,...perception.entities.flatMap(e=>[e.type,e.name??""]),...perception.blocks.map(b=>b.type),...perception.items.map(i=>i.item)].filter(Boolean).map(value=>value.toLowerCase()));const working=episodes.slice(-6),ranked=episodes.map((fact,index)=>{const hay=`${fact.text} ${JSON.stringify(fact.metadata??{})}`.toLowerCase();const overlap=[...terms].filter(term=>term.length>2&&hay.includes(term)).length;const social=perception.entities.some(entity=>entity.name&&hay.includes(entity.name.toLowerCase()))?2:0;const nearby=fact.metadata?.dimension===perception.environment.dimension&&fact.metadata.position&&distance(fact.metadata.position,perception.self.position)<32?1:0;return{fact,score:overlap*3+social+nearby+(fact.salience??0)*2-index/Math.max(1,episodes.length)};}).sort((a,b)=>b.score-a.score);const social=ranked.filter(item=>perception.entities.some(entity=>entity.name&&item.fact.text.toLowerCase().includes(entity.name.toLowerCase()))).slice(0,4).map(item=>item.fact),recalled=ranked.filter(item=>!working.includes(item.fact)&&!social.includes(item.fact)).slice(0,8).map(item=>item.fact);const known=[...Object.values(allKnowledge.people),...Object.values(allKnowledge.entityTypes),...Object.values(allKnowledge.blockTypes),...Object.values(allKnowledge.itemTypes),...Object.values(allKnowledge.biomes)].filter(item=>terms.has(item.id.toLowerCase())||(item.name!==undefined&&terms.has(item.name.toLowerCase()))).slice(0,10).map(item=>`${item.name??item.id}: first seen ${relative(item.firstSeen)}, last seen ${relative(item.lastSeen)}${item.dimension?` in ${item.dimension}`:""}`);const result:MemoryContext={working:[],recalled:[],social:[],knowledge:[],beliefs:[],reflections:[],projects:allProjects.filter(project=>project.status==="ACTIVE"||project.status==="PAUSED").slice(0,3),chapters,self,contextChars:0};let used=JSON.stringify({self,projects:result.projects,chapters}).length;const fit=<T>(source:T[],target:T[])=>{for(const item of source){const size=JSON.stringify(item).length;if(used+size>budget)break;target.push(item);used+=size;}};fit(social,result.social);fit(recalled,result.recalled);fit(working,result.working);fit(known,result.knowledge);fit(allBeliefs.slice(0,6),result.beliefs);fit(reflections.slice(-4),result.reflections);result.contextChars=used;return result;}
}
