import { DecisionSchema, type Decision, type Perception } from "./contracts.js";
import type { EpisodicFact, MemoryContext } from "./memory.js";
import { profileFor, profilePrompt, type ModelProfileId } from "./profiles.js";

export type CognitionContext = MemoryContext;
export type Consolidation={ summary:string; topics:string[]; people:string[] };
export type ProviderStatus={provider:string;endpoint:string;available:boolean;models:string[];error?:string};
export type ProviderRequest={model:string;profile:ModelProfileId};
export interface CognitionProvider { decide(perception:Perception,context:CognitionContext,request:ProviderRequest):Promise<Decision>; discover():Promise<ProviderStatus>; consolidate?(episodes:EpisodicFact[]):Promise<Consolidation>; }
/** Kept alongside Zod validation: validation after generation remains authoritative. */
export const DecisionOutputFormat={type:"object",properties:{actionId:{type:"string",maxLength:128},intent:{type:"string",maxLength:280},reflection:{type:["string","null"],maxLength:400},speech:{type:["string","null"],maxLength:240},memorySalience:{type:"number",minimum:0,maximum:1},projectUpdate:{type:["object","null"],properties:{operation:{type:"string",enum:["KEEP","CREATE","UPDATE","COMPLETE","ABANDON","PAUSE"]},projectId:{type:"string",maxLength:80},title:{type:"string",maxLength:120},purpose:{type:"string",maxLength:280},progress:{type:"string",maxLength:280}},required:["operation"],additionalProperties:false},selfUpdate:{type:["object","null"],properties:{selfDescription:{type:"string",maxLength:280},preferences:{type:"array",items:{type:"string",maxLength:120},maxItems:6},concerns:{type:"array",items:{type:"string",maxLength:120},maxItems:6},aspirations:{type:"array",items:{type:"string",maxLength:120},maxItems:6}},additionalProperties:false},beliefUpdate:{type:["object","null"],properties:{operation:{type:"string",enum:["KEEP","CREATE","UPDATE","REMOVE"]},belief:{type:"string",maxLength:280},confidence:{type:"number",minimum:0,maximum:1}},required:["operation"],additionalProperties:false},buildPlan:{type:["object","null"],properties:{purpose:{type:"string",maxLength:180},placements:{type:"array",minItems:1,maxItems:24,items:{type:"object",properties:{x:{type:"integer",minimum:-4,maximum:4},y:{type:"integer",minimum:-2,maximum:3},z:{type:"integer",minimum:-4,maximum:4},itemId:{type:"string",maxLength:100}},required:["x","y","z","itemId"],additionalProperties:false}}},required:["placements"],additionalProperties:false}},required:["actionId","intent","reflection","speech"],additionalProperties:false} as const;
const parse=(value:string)=>DecisionSchema.parse(JSON.parse(value)); const url=(base:string,path:string)=>`${base.replace(/\/$/,"")}${path}`;
export class DeterministicProvider implements CognitionProvider { async decide(perception:Perception,_:CognitionContext,_request:ProviderRequest):Promise<Decision>{return {actionId:perception.candidates[0].id,intent:"I will pause and observe.",reflection:null,speech:null};} async discover():Promise<ProviderStatus>{return {provider:"mock",endpoint:"in-process",available:true,models:["deterministic"]};} }
export class OllamaProvider implements CognitionProvider {
  constructor(private readonly baseUrl:string,private readonly timeoutMs:number,private readonly keepAlive:string){}
  async discover():Promise<ProviderStatus>{try{const response=await fetch(url(this.baseUrl,"/api/tags"),{signal:AbortSignal.timeout(this.timeoutMs)});if(!response.ok)throw new Error(`HTTP ${response.status}`);const body=await response.json() as {models?:{name:string}[]};return {provider:"ollama",endpoint:this.baseUrl,available:true,models:(body.models??[]).map(model=>model.name)};}catch(error){return {provider:"ollama",endpoint:this.baseUrl,available:false,models:[],error:error instanceof Error?error.message:String(error)};}}
  async decide(perception:Perception,context:CognitionContext,request:ProviderRequest):Promise<Decision>{const profile=profileFor(request.profile);const response=await fetch(url(this.baseUrl,"/api/generate"),{method:"POST",signal:AbortSignal.timeout(this.timeoutMs),headers:{"content-type":"application/json"},body:JSON.stringify({model:request.model,prompt:JSON.stringify(profilePrompt(profile,perception,context)),stream:false,think:profile.sampling.think,keep_alive:this.keepAlive,options:{temperature:profile.sampling.temperature,top_p:profile.sampling.topP,min_p:profile.sampling.minP,repeat_penalty:profile.sampling.repeatPenalty,num_ctx:profile.sampling.numCtx},format:DecisionOutputFormat})});if(!response.ok)throw new Error(`Ollama ${response.status}: ${await response.text()}`);return parse((await response.json() as {response:string}).response);}
}
export class OpenAICompatibleProvider implements CognitionProvider {
  constructor(private readonly baseUrl:string,private readonly timeoutMs:number,private readonly apiKey=""){}
  private headers(){return {"content-type":"application/json",...(this.apiKey?{authorization:`Bearer ${this.apiKey}`}:{})};}
  async discover():Promise<ProviderStatus>{try{const response=await fetch(url(this.baseUrl,"/models"),{headers:this.headers(),signal:AbortSignal.timeout(this.timeoutMs)});if(!response.ok)throw new Error(`HTTP ${response.status}`);const body=await response.json() as {data?:{id:string}[]};return {provider:"openai-compatible",endpoint:this.baseUrl,available:true,models:(body.data??[]).map(value=>value.id)};}catch(error){return {provider:"openai-compatible",endpoint:this.baseUrl,available:false,models:[],error:error instanceof Error?error.message:String(error)};}}
  async decide(perception:Perception,context:CognitionContext,request:ProviderRequest):Promise<Decision>{const profile=profileFor(request.profile);const response=await fetch(url(this.baseUrl,"/chat/completions"),{method:"POST",signal:AbortSignal.timeout(this.timeoutMs),headers:this.headers(),body:JSON.stringify({model:request.model,messages:[{role:"system",content:profile.system},{role:"user",content:JSON.stringify(profilePrompt(profile,perception,context))}],temperature:profile.sampling.temperature,top_p:profile.sampling.topP,max_tokens:900,response_format:{type:"json_schema",json_schema:{name:"emergentcraft_decision",strict:true,schema:DecisionOutputFormat}}})});if(!response.ok)throw new Error(`OpenAI-compatible ${response.status}: ${await response.text()}`);const payload=await response.json() as {choices?:{message?:{content?:string|{text?:string}[]}}[]};const content=payload.choices?.[0]?.message?.content;const text=typeof content==="string"?content:Array.isArray(content)?content.map(part=>part.text??"").join(""):"";if(!text)throw new Error("OpenAI-compatible response did not contain message content");return parse(text);}
}
export async function resolveOllamaModel(baseUrl:string,requested:string):Promise<string>{if(requested)return requested;const response=await fetch(url(baseUrl,"/api/tags"));if(!response.ok)throw new Error("Ollama model listing failed");const tags=await response.json() as {models?:{name:string}[]};const model=tags.models?.[0]?.name;if(!model)throw new Error("No Ollama model installed; set OLLAMA_MODEL after intentionally pulling one");return model;}
