import { DecisionSchema, type Decision, type Perception } from "./contracts.js";
import type { Chapter, EpisodicFact, MemoryContext } from "./memory.js";

export type CognitionContext = MemoryContext;
export type Consolidation={ summary:string; topics:string[]; people:string[] };
export interface CognitionProvider { decide(perception: Perception, context: CognitionContext): Promise<Decision>; consolidate?(episodes:EpisodicFact[]):Promise<Consolidation>; }
export class DeterministicProvider implements CognitionProvider {
  async decide(perception: Perception, _context: CognitionContext): Promise<Decision> { return { actionId: perception.candidates[0].id, intent: "I will pause and observe.", reflection: null, speech: null }; }
}
export class OllamaProvider implements CognitionProvider {
  constructor(private readonly baseUrl: string, private readonly model: string, private readonly think: boolean, private readonly timeoutMs: number, private readonly keepAlive: string, private readonly numCtx: number) {}
  async decide(perception: Perception, context: CognitionContext): Promise<Decision> {
    const prompt = JSON.stringify({ instruction: "You are the same person across decisions. You have no assigned mission. Continue existing projects only while you still care about them; you may change your mind. Choose only an offered physical action. Factual memories describe experiences that happened to you. Beliefs, reflections, self-model and chapters are subjective interpretations and may be wrong. Do not fabricate current facts or claim an action succeeded.", IDENTITY_AND_SELF: context.self, CURRENT_PROJECTS: context.projects, CURRENT_WORLD_PERCEPTION: { self:perception.self, capabilities: perception.capabilities, environment: perception.environment, entities: perception.entities, blocks: perception.blocks, items: perception.items }, RECENT_WORKING_MEMORY: context.working, RELEVANT_RECALLED_EPISODES: context.recalled, RELEVANT_SOCIAL_HISTORY: context.social, RELEVANT_KNOWN_WORLD_FACTS: context.knowledge, YOUR_CURRENT_BELIEFS: context.beliefs, RECENT_SUBJECTIVE_REFLECTIONS:context.reflections, RELEVANT_AUTOBIOGRAPHICAL_MEMORY: context.chapters, AVAILABLE_PHYSICAL_ACTIONS: perception.candidates });
    const response = await fetch(`${this.baseUrl}/api/generate`, { method: "POST", signal: AbortSignal.timeout(this.timeoutMs), headers: { "content-type": "application/json" }, body: JSON.stringify({ model: this.model, prompt, stream: false, think: this.think, keep_alive: this.keepAlive, options: { num_ctx: this.numCtx }, format: { type: "object", properties: { actionId: { type: "string" }, intent: { type: "string" }, reflection: { type: ["string", "null"] }, speech: { type: ["string", "null"] }, memorySalience:{type:"number"}, projectUpdate:{type:["object","null"]}, selfUpdate:{type:["object","null"]}, beliefUpdate:{type:["object","null"]} }, required: ["actionId", "intent", "reflection", "speech"], additionalProperties: false } }) });
    if (!response.ok) throw new Error(`Ollama ${response.status}: ${await response.text()}`);
    const body = await response.json() as { response: string };
    return DecisionSchema.parse(JSON.parse(body.response));
  }
  async consolidate(episodes:EpisodicFact[]):Promise<Consolidation>{const prompt=JSON.stringify({instruction:"Write one short first-person autobiographical summary from these factual episodes. Do not state interpretations as facts. Return summary, compact topics, and people names only.",episodes});const response=await fetch(`${this.baseUrl}/api/generate`,{method:"POST",signal:AbortSignal.timeout(this.timeoutMs),headers:{"content-type":"application/json"},body:JSON.stringify({model:this.model,prompt,stream:false,think:false,keep_alive:this.keepAlive,options:{num_ctx:this.numCtx},format:{type:"object",properties:{summary:{type:"string"},topics:{type:"array",items:{type:"string"}},people:{type:"array",items:{type:"string"}}},required:["summary","topics","people"],additionalProperties:false}})});if(!response.ok)throw new Error(`Ollama ${response.status}`);const body=await response.json() as {response:string};const parsed=JSON.parse(body.response) as Consolidation;if(!parsed.summary||parsed.summary.length>800||!Array.isArray(parsed.topics)||!Array.isArray(parsed.people))throw new Error("Invalid consolidation");return {summary:parsed.summary,topics:parsed.topics.slice(0,8).map(String),people:parsed.people.slice(0,8).map(String)};}
}
export async function resolveOllamaModel(baseUrl: string, requested: string): Promise<string> { if (requested) return requested; const response = await fetch(`${baseUrl}/api/tags`); if (!response.ok) throw new Error("Ollama model listing failed"); const tags = await response.json() as { models?: { name: string }[] }; const model = tags.models?.[0]?.name; if (!model) throw new Error("No Ollama model installed; set OLLAMA_MODEL after pulling one"); return model; }
