import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { EmbodimentEventSchema, PerceptionSchema, validateDecision, type Decision } from "./contracts.js";
import type { CognitionProvider, ProviderRequest, SubjectiveContinuation } from "./provider.js";
import { MemoryStore, type SubjectiveState } from "./memory.js";
import { AsyncQueue } from "./queue.js";
const body=async(request:IncomingMessage):Promise<unknown>=>{let text="";for await(const chunk of request)text+=chunk;return JSON.parse(text);}; const json=(response:ServerResponse,status:number,value:unknown)=>{response.writeHead(status,{"content-type":"application/json"});response.end(JSON.stringify(value));}; const now=()=>new Date().toISOString(); const unique=(values:string[])=>([...new Set(values.map(value=>value.trim()).filter(Boolean))]).slice(0,6);

/** One server model serves private per-agent contexts; consolidation is background-only. */
export function createBrainServer(provider:CognitionProvider,configOrMemory:ProviderRequest|MemoryStore,memoryMaybe?:MemoryStore,queue=new AsyncQueue(1)){
 const config=configOrMemory instanceof MemoryStore?{model:"deterministic",profile:"generic" as const}:configOrMemory, memory=configOrMemory instanceof MemoryStore?configOrMemory:memoryMaybe!;
 const consolidating=new Set<string>(),continuing=new Set<string>(),continuityTurns=new Map<string,number>(),after=Math.max(10,Number(process.env.MEMORY_CONSOLIDATE_AFTER_EVENTS??30)),batch=Math.max(5,Number(process.env.MEMORY_CONSOLIDATION_BATCH??20)),continuityEvery=Math.max(3,Number(process.env.MEMORY_CONTINUITY_EVERY_DECISIONS??6));
 const unsafe=(text:string)=>/(<\/?think>|```|\bjavascript\b|the user has just told me|system prompt|json schema|\bactionid\b|^\s*\/\/|\b(?:const|let|var|function)\b|=>)/i.test(text);
 const apply=async(id:string,decision:Decision)=>{const timestamp=now(),state=await memory.readState(id),update=decision.selfUpdate,next:SubjectiveState={...state,intent:unsafe(decision.intent)?"":decision.intent.slice(0,280),updatedAt:timestamp};if(update?.selfDescription!==undefined&&!unsafe(update.selfDescription))next.selfDescription=update.selfDescription;if(update?.preferences)next.preferences=unique([...(state.preferences??[]),...update.preferences.filter(value=>!unsafe(value))]);if(update?.concerns)next.concerns=unique([...(state.concerns??[]),...update.concerns.filter(value=>!unsafe(value))]);if(update?.aspirations)next.aspirations=unique([...(state.aspirations??[]),...update.aspirations.filter(value=>!unsafe(value))]);await memory.writeState(id,next);if(decision.reflection&&!unsafe(decision.reflection))await memory.appendReflection(id,{at:timestamp,text:decision.reflection,salience:decision.memorySalience});const project=decision.projectUpdate;if(project&&project.operation!=="KEEP"&&!(project.title&&unsafe(project.title))&&!(project.purpose&&unsafe(project.purpose))&&!(project.progress&&unsafe(project.progress))){const projects=await memory.projects(id);if(project.operation==="CREATE"&&project.title&&project.purpose&&projects.filter(value=>value.status==="ACTIVE").length<3)projects.push({id:`project-${Date.now()}-${projects.length}`,title:project.title,purpose:project.purpose,status:"ACTIVE",createdAt:timestamp,lastUpdatedAt:timestamp,progress:project.progress??"Started."});else if(project.projectId){const found=projects.find(value=>value.id===project.projectId);if(found){if(project.progress)found.progress=project.progress;found.status=project.operation==="COMPLETE"?"COMPLETED":project.operation==="ABANDON"?"ABANDONED":project.operation==="PAUSE"?"PAUSED":"ACTIVE";found.lastUpdatedAt=timestamp;}}await memory.writeProjects(id,projects);}const belief=decision.beliefUpdate;if(belief&&belief.operation!=="KEEP"&&(!belief.belief||!unsafe(belief.belief))){const beliefs=await memory.beliefs(id);if(belief.operation==="CREATE"&&belief.belief)beliefs.push({id:`belief-${Date.now()}-${beliefs.length}`,belief:belief.belief,confidence:belief.confidence??0.5,createdAt:timestamp,updatedAt:timestamp});else if(belief.operation==="REMOVE"&&belief.belief){const index=beliefs.findIndex(value=>value.belief===belief.belief);if(index>=0)beliefs.splice(index,1);}else if(belief.operation==="UPDATE"&&belief.belief&&beliefs[0]){beliefs[0]={...beliefs[0],belief:belief.belief,confidence:belief.confidence??beliefs[0].confidence,updatedAt:timestamp};}await memory.writeBeliefs(id,beliefs);}};
 const schedule=async(id:string)=>{if(consolidating.has(id)||!provider.consolidate)return;const [episodes,meta]=await Promise.all([memory.readEpisodes(id,Number.MAX_SAFE_INTEGER),memory.meta(id)]);if(episodes.length-meta.consolidatedUntil<after)return;const start=meta.consolidatedUntil,end=Math.min(episodes.length,start+batch),source=episodes.slice(start,end);consolidating.add(id);void queue.run(async()=>{try{const result=await provider.consolidate!(source,config);await memory.appendChapter(id,{id:`chapter-${Date.now()}-${start}`,startedAt:source[0].at,endedAt:source.at(-1)!.at,summary:result.summary,topics:result.topics,people:result.people,sourceStart:start,sourceEnd:end-1,createdAt:now()});await memory.writeMeta(id,{schemaVersion:1,consolidatedUntil:end});}catch(error){console.warn(`[EmergentCraft Brain] consolidation failed for ${id}: ${error instanceof Error?error.message:String(error)}`);}finally{consolidating.delete(id);}},"background");};
 const scheduleContinuity=(id:string,context:import("./memory.js").MemoryContext)=>{const turns=(continuityTurns.get(id)??0)+1;continuityTurns.set(id,turns);if(turns%continuityEvery!==0||continuing.has(id)||!provider.continueSubjectively)return;continuing.add(id);void queue.run(async()=>{try{const update:SubjectiveContinuation=await provider.continueSubjectively!(context,config);const state=await memory.readState(id);const intent=/((<\/?think>)|```|javascript|the user has just told me|system prompt|json schema)/i.test(state.intent)?"":state.intent;await apply(id,{actionId:"continuity",intent,reflection:update.reflection??null,speech:null,projectUpdate:update.projectUpdate,selfUpdate:update.selfUpdate,beliefUpdate:update.beliefUpdate});console.info(`[EmergentCraft Brain] subjective continuity updated for ${id}`);}catch(error){console.warn(`[EmergentCraft Brain] subjective continuity failed for ${id}: ${error instanceof Error?error.message:String(error)}`);}finally{continuing.delete(id);}},"background");};
 return createServer(async(request,response)=>{try{if(request.method==="GET"&&request.url==="/health"){json(response,200,{ok:true,queue:{running:queue.running,queued:queue.queued}});return;}if(request.method==="POST"&&request.url==="/v1/status"){json(response,200,{config,queue:{running:queue.running,queued:queue.queued},provider:provider.discover?await provider.discover():{available:false,models:[]}});return;}if(request.method==="POST"&&request.url==="/v1/event"){const event=EmbodimentEventSchema.parse(await body(request));await memory.appendEmbodiment(event.agentId,event);void schedule(event.agentId);response.writeHead(204);response.end();return;}if(request.method==="POST"&&request.url==="/v1/recall"){const perception=PerceptionSchema.parse(await body(request));json(response,200,await memory.context(perception));return;}if(request.method==="POST"&&(request.url==="/v1/mind"||request.url==="/v1/memories")){const input=await body(request) as {agentId?:string};if(!input.agentId)throw new Error("agentId required");if(request.url==="/v1/mind"){const [self,projects,beliefs,episodes,chapters]=await Promise.all([memory.readState(input.agentId),memory.projects(input.agentId),memory.beliefs(input.agentId),memory.readEpisodes(input.agentId,Number.MAX_SAFE_INTEGER),memory.chapters(input.agentId)]);json(response,200,{self,projects,beliefs,memoryCounts:{episodes:episodes.length,chapters:chapters.length}});}else json(response,200,{episodes:await memory.readEpisodes(input.agentId,12),chapters:await memory.chapters(input.agentId,4)});return;}if(request.method!=="POST"||request.url!=="/v1/decide"){response.writeHead(404);response.end();return;}const perception=PerceptionSchema.parse(await body(request));await memory.observe(perception);const context=await memory.context(perception);const queued=performance.now(),decision=validateDecision(await queue.run(async()=>{const started=performance.now(),value=await provider.decide(perception,context,config);console.info(`[EmergentCraft Brain] ${perception.name} -> ${config.model} -> ${value.actionId} (${Math.round(performance.now()-started)}ms; queued ${Math.round(started-queued)}ms)`);return value;}),perception);await apply(perception.agentId,decision);void schedule(perception.agentId);scheduleContinuity(perception.agentId,context);json(response,200,decision);}catch(error){json(response,400,{error:error instanceof Error?error.message:"Invalid request"});}});
}
