import { createServer, type IncomingMessage, type ServerResponse } from "node:http";
import { EmbodimentEventSchema, PerceptionSchema, validateDecision, type Decision } from "./contracts.js";
import type { CognitionProvider } from "./provider.js";
import { MemoryStore, type Belief, type Project, type SubjectiveState } from "./memory.js";
import { AsyncQueue } from "./queue.js";

async function body(request:IncomingMessage):Promise<unknown>{let text="";for await(const chunk of request)text+=chunk;return JSON.parse(text);}
const json=(response:ServerResponse,status:number,value:unknown)=>{response.writeHead(status,{"content-type":"application/json"});response.end(JSON.stringify(value));};
const unique=(values:string[])=>([...new Set(values.map(value=>value.trim()).filter(Boolean))]).slice(0,6);
const now=()=>new Date().toISOString();

/** Loopback Brain API: all mutable mental layers remain per-agent and never cross identities. */
export function createBrainServer(provider:CognitionProvider,memory:MemoryStore,queue=new AsyncQueue(1)){
  const consolidating=new Set<string>(),after=Math.max(10,Number(process.env.MEMORY_CONSOLIDATE_AFTER_EVENTS??30)),batch=Math.max(5,Number(process.env.MEMORY_CONSOLIDATION_BATCH??20));
  const applyDecision=async(id:string,decision:Decision)=>{const timestamp=now(),state=await memory.readState(id);const update=decision.selfUpdate;const next:SubjectiveState={...state,intent:decision.intent.slice(0,280),updatedAt:timestamp};if(update?.selfDescription!==undefined)next.selfDescription=update.selfDescription;if(update?.preferences)next.preferences=unique([...(state.preferences??[]),...update.preferences]);if(update?.concerns)next.concerns=unique([...(state.concerns??[]),...update.concerns]);if(update?.aspirations)next.aspirations=unique([...(state.aspirations??[]),...update.aspirations]);await memory.writeState(id,next);if(decision.reflection)await memory.appendReflection(id,{at:timestamp,text:decision.reflection,salience:decision.memorySalience});const projectUpdate=decision.projectUpdate;if(projectUpdate&&projectUpdate.operation!=="KEEP"){const projects=await memory.projects(id);if(projectUpdate.operation==="CREATE"&&projectUpdate.title&&projectUpdate.purpose&&projects.filter(project=>project.status==="ACTIVE").length<3){projects.push({id:`project-${Date.now()}-${projects.length}`,title:projectUpdate.title,purpose:projectUpdate.purpose,status:"ACTIVE",createdAt:timestamp,lastUpdatedAt:timestamp,progress:projectUpdate.progress??"Started."});}else if(projectUpdate.projectId){const project=projects.find(value=>value.id===projectUpdate.projectId);if(project){if(projectUpdate.title)project.title=projectUpdate.title;if(projectUpdate.purpose)project.purpose=projectUpdate.purpose;if(projectUpdate.progress)project.progress=projectUpdate.progress;project.status=projectUpdate.operation==="COMPLETE"?"COMPLETED":projectUpdate.operation==="ABANDON"?"ABANDONED":projectUpdate.operation==="PAUSE"?"PAUSED":"ACTIVE";project.lastUpdatedAt=timestamp;}}await memory.writeProjects(id,projects);}const beliefUpdate=decision.beliefUpdate;if(beliefUpdate&&beliefUpdate.operation!=="KEEP"){let beliefs=await memory.beliefs(id);if(beliefUpdate.operation==="REMOVE"&&beliefUpdate.belief)beliefs=beliefs.filter(value=>value.belief!==beliefUpdate.belief);else if(beliefUpdate.belief){const existing=beliefs.find(value=>value.belief===beliefUpdate.belief);if(existing){existing.confidence=beliefUpdate.confidence??existing.confidence;existing.updatedAt=timestamp;}else if(beliefs.length<16)beliefs.push({id:`belief-${Date.now()}-${beliefs.length}`,belief:beliefUpdate.belief,confidence:beliefUpdate.confidence??0.5,createdAt:timestamp,updatedAt:timestamp});}await memory.writeBeliefs(id,beliefs);}};
  const schedule=async(id:string)=>{if(consolidating.has(id)||!provider.consolidate)return;const [episodes,meta]=await Promise.all([memory.readEpisodes(id,Number.MAX_SAFE_INTEGER),memory.meta(id)]);if(episodes.length-meta.consolidatedUntil<after)return;const start=meta.consolidatedUntil,end=Math.min(episodes.length,start+batch),source=episodes.slice(start,end);consolidating.add(id);console.info(`[EmergentCraft Brain] ${id} memory consolidation queued (${start}-${end})`);void queue.run(async()=>{try{const result=await provider.consolidate!(source);await memory.appendChapter(id,{id:`chapter-${Date.now()}-${start}`,startedAt:source[0].at,endedAt:source.at(-1)!.at,summary:result.summary,topics:result.topics,people:result.people,sourceStart:start,sourceEnd:end-1,createdAt:now()});await memory.writeMeta(id,{schemaVersion:1,consolidatedUntil:end});console.info(`[EmergentCraft Brain] ${id} consolidated episodes ${start}-${end-1}`);}catch(error){console.warn(`[EmergentCraft Brain] consolidation failed for ${id}: ${error instanceof Error?error.message:String(error)}`);}finally{consolidating.delete(id);}},"background");};
  return createServer(async(request,response)=>{if(request.method==="GET"&&request.url==="/health"){json(response,200,{ok:true,queue:{running:queue.running,queued:queue.queued}});return;}try{if(request.method==="POST"&&request.url==="/v1/event"){const event=EmbodimentEventSchema.parse(await body(request));await memory.appendEmbodiment(event.agentId,event);void schedule(event.agentId);response.writeHead(204);response.end();return;}if(request.method==="POST"&&request.url==="/v1/recall"){const perception=PerceptionSchema.parse(await body(request));json(response,200,await memory.context(perception));return;}if(request.method==="POST"&&(request.url==="/v1/mind"||request.url==="/v1/memories")){const input=await body(request) as {agentId?:string};if(!input.agentId)throw new Error("agentId required");if(request.url==="/v1/mind"){const [self,projects,beliefs,episodes,chapters]=await Promise.all([memory.readState(input.agentId),memory.projects(input.agentId),memory.beliefs(input.agentId),memory.readEpisodes(input.agentId,Number.MAX_SAFE_INTEGER),memory.chapters(input.agentId)]);json(response,200,{self,projects,beliefs,memoryCounts:{episodes:episodes.length,chapters:chapters.length}});}else json(response,200,{episodes:await memory.readEpisodes(input.agentId,12),chapters:await memory.chapters(input.agentId,4)});return;}if(request.method!=="POST"||request.url!=="/v1/decide"){response.writeHead(404);response.end();return;}const perception=PerceptionSchema.parse(await body(request));await memory.observe(perception);const context=await memory.context(perception);console.info(`[EmergentCraft Brain] ${perception.name} cognition context: working=${context.working.length} recalledEpisodes=${context.recalled.length} social=${context.social.length} beliefs=${context.beliefs.length} chapters=${context.chapters.length} projects=${context.projects.length} contextChars=${context.contextChars}`);const queuedAt=performance.now();const decision=validateDecision(await queue.run(async()=>{const started=performance.now(),result=await provider.decide(perception,context);console.info(`[EmergentCraft Brain] ${perception.name} completed in ${Math.round(performance.now()-started)}ms after ${Math.round(started-queuedAt)}ms queued: ${result.actionId}`);return result;}),perception);await applyDecision(perception.agentId,decision);void schedule(perception.agentId);json(response,200,decision);}catch(error){json(response,400,{error:error instanceof Error?error.message:"Invalid request"});}});
}
