import "dotenv/config";
import { OllamaProvider, resolveOllamaModel } from "./provider.js";
import { PerceptionSchema, validateDecision } from "./contracts.js";

// Frozen, non-executing scenario for the native Andy chat adapter.
const base=process.env.OLLAMA_BASE_URL??"http://127.0.0.1:11434",model=await resolveOllamaModel(base,process.env.OLLAMA_MODEL??"sweaterdog/andy-4:micro-q8_0"),profile=(process.env.EC_MODEL_PROFILE??"minecraft-andy4") as import("./profiles.js").ModelProfileId;
const perception=PerceptionSchema.parse({schemaVersion:1,agentId:"4bde43d4-cbe1-49d0-8a33-9b2e8004881d",name:"Smoke",epoch:1,capabilities:{playerHunger:true,inventory:true,nativeNavigation:true,blockBreaking:true,itemPickup:true,eating:true,equipment:true,combat:true,crafting:true,placement:true},self:{position:{x:0,y:64,z:0},health:20,maxHealth:20,alive:true,onGround:true,inWater:false,onFire:false,airSupply:300,fallDistance:0,effects:[],inventory:[{item:"minecraft:oak_planks",count:4}]},environment:{dimension:"minecraft:overworld",timeOfDay:6000,weather:"clear",light:15,biome:"minecraft:plains",daytime:true,temperature:0.8,downfall:0},entities:[],blocks:[{id:"block:oak",type:"minecraft:oak_log",relativePosition:{x:3,y:0,z:0},distance:3,hardness:2,breakable:true,solid:true,fluid:false,position:{x:3,y:64,z:0}}],items:[],events:[],candidates:[{id:"acquire:oak",kind:"ACQUIRE_BLOCK",description:"Acquire visible minecraft:oak_log.",targetId:"block:oak",target:{x:3,y:64,z:0}},{id:"place:planks",kind:"PLACE_BLOCK",description:"Place oak planks nearby.",targetId:"minecraft:oak_planks",target:{x:1,y:64,z:0}},{id:"build:1",kind:"BUILD_PLAN",description:"Build a small supplied placement plan."},{id:"travel:1",kind:"TRAVEL",description:"Travel to a reachable local location.",target:{x:6,y:64,z:0}},{id:"wait:1",kind:"WAIT",description:"Wait and observe."}]});
const context={working:[],recalled:[],social:[],knowledge:[],beliefs:[],reflections:[],projects:[],chapters:[],self:{intent:"",updatedAt:new Date(0).toISOString()},contextChars:0},started=performance.now(),provider=new OllamaProvider(base,Number(process.env.OLLAMA_REQUEST_TIMEOUT_MS??120000),process.env.OLLAMA_KEEP_ALIVE??"15m");
try{const decision=validateDecision(await provider.decide(perception,context,{model,profile}),perception);console.log(JSON.stringify({provider:"ollama",model,profile,scenario:"frozen/no-world-mutation",latencyMs:Math.round(performance.now()-started),rawCleaned:provider.lastAndyDiagnostic?.rawCleaned,parsedCommand:provider.lastAndyDiagnostic?.command,matchedCanonicalCandidate:provider.lastAndyDiagnostic?.candidateId,valid:provider.lastAndyDiagnostic?.valid===true,decision:{action:decision.actionId,intent:decision.intent}},null,2));}catch(error){console.log(JSON.stringify({provider:"ollama",model,profile,scenario:"frozen/no-world-mutation",latencyMs:Math.round(performance.now()-started),diagnostic:provider.lastAndyDiagnostic,error:error instanceof Error?error.message:String(error)},null,2));process.exitCode=1;}
