package nl.noscapect.emergentcraft.perception;

import nl.noscapect.emergentcraft.*;
import nl.noscapect.emergentcraft.actions.OfferedAction;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.entity.npc.villager.Villager;
import net.minecraft.world.level.ClipContext;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.Vec3;
import java.util.*;
import static nl.noscapect.emergentcraft.perception.PerceptionModels.*;

/** Bounded local, LOS-filtered observations and neutral affordance generation. */
public final class PerceptionBuilder {
    private static final int ENTITY_RADIUS=14, BLOCK_RADIUS=7, MAX_ENTITIES=16, MAX_BLOCKS=32, MAX_ITEMS=16;
    private final AgentRegistry registry; private final AgentInventoryStore inventory;
    public PerceptionBuilder(AgentRegistry registry,AgentInventoryStore inventory) { this.registry=registry; this.inventory=inventory; }
    public PerceptionFrame build(AgentRecord agent,GoalLessVillager body,List<RecentEvent> recent) {
        var level=(net.minecraft.server.level.ServerLevel)body.level(); long time=level.getOverworldClockTime(); BlockPos origin=body.blockPosition();
        List<ObservedEntity> entities=observeEntities(agent,body); List<ObservedItem> items=observeItems(body); List<ObservedBlock> blocks=observeBlocks(agent,body);
        List<ActionCandidate> candidates=new ArrayList<>(); Map<String,OfferedAction> offered=new LinkedHashMap<>(); add(candidates,offered,new ActionCandidate("wait:"+agent.epoch(),"WAIT","Wait and observe.",null,null),new OfferedAction("wait:"+agent.epoch(),OfferedAction.Kind.WAIT,null,null,null,null));
        int move=0; for(int[] offset:new int[][]{{4,0},{-4,0},{0,4},{0,-4},{3,3},{3,-3},{-3,3},{-3,-3}}) { BlockPos destination=origin.offset(offset[0],0,offset[1]); if(body.getNavigation().createPath(destination,0)!=null&&body.getNavigation().createPath(destination,0).canReach()) { String id="move:"+agent.epoch()+":"+move++; add(candidates,offered,new ActionCandidate(id,"MOVE_TO","Walk to a nearby reachable location.",null,new BlockPosition(destination.getX(),destination.getY(),destination.getZ())),new OfferedAction(id,OfferedAction.Kind.MOVE_TO,Vec3.atCenterOf(destination),null,destination,null)); } }
        for(ObservedEntity entity:entities) { if(candidates.size()>=32) break; UUID id=UUID.fromString(entity.id().substring("entity:".length())); String action="approach:"+agent.epoch()+":"+entity.id(); add(candidates,offered,new ActionCandidate(action,"APPROACH_ENTITY","Approach "+entity.type()+".",entity.id(),null),new OfferedAction(action,OfferedAction.Kind.APPROACH_ENTITY,null,id,null,entity.type())); if(entity.emergentCraft()!=null&&candidates.size()<32) { String speak="speak:"+agent.epoch()+":"+entity.id(); add(candidates,offered,new ActionCandidate(speak,"SPEAK","Speak to "+entity.name()+".",entity.id(),null),new OfferedAction(speak,OfferedAction.Kind.SPEAK,null,id,null,entity.type())); } }
        for(ObservedItem item:items) { if(candidates.size()>=32) break; UUID id=UUID.fromString(item.id().substring("item:".length())); String action="pickup:"+agent.epoch()+":"+item.id(); add(candidates,offered,new ActionCandidate(action,"PICK_UP_ITEM","Approach and pick up "+item.item()+".",item.id(),null),new OfferedAction(action,OfferedAction.Kind.PICK_UP_ITEM,null,id,null,item.item())); }
        for(ObservedBlock block:blocks) { if(candidates.size()>=31) break; BlockPos pos=new BlockPos(block.position().x(),block.position().y(),block.position().z()); String approach="approach:"+agent.epoch()+":"+block.id(); add(candidates,offered,new ActionCandidate(approach,"APPROACH_BLOCK","Approach "+block.type()+".",block.id(),block.position()),new OfferedAction(approach,OfferedAction.Kind.APPROACH_BLOCK,Vec3.atCenterOf(pos),null,pos,block.type())); if(block.breakable()&&candidates.size()<32) { String breaking="break:"+agent.epoch()+":"+block.id(); add(candidates,offered,new ActionCandidate(breaking,"BREAK_BLOCK","Attempt to break "+block.type()+".",block.id(),block.position()),new OfferedAction(breaking,OfferedAction.Kind.BREAK_BLOCK,Vec3.atCenterOf(pos),null,pos,block.type())); } }
        var capabilities=new Capabilities(false,true,true,true,true); var self=new SelfPerception(position(body.position()),body.getHealth(),body.getMaxHealth(),body.isAlive(),body.onGround(),body.isInWater(),body.isOnFire(),body.getAirSupply(),(float)Math.max(0d,body.fallDistance),body.getActiveEffects().stream().map(effect->BuiltInRegistries.MOB_EFFECT.getKey(effect.getEffect().value()).toString()).limit(16).toList(),inventory.entries(agent.id()).stream().map(entry->new InventoryEntry(entry.item(),entry.count())).toList());
        String biome=level.getBiome(origin).unwrapKey().map(key->key.identifier().toString()).orElse("minecraft:unknown"); var biomeValue=level.getBiome(origin).value(); String weather=level.isThundering()?"thunder":level.isRaining()?"rain":"clear"; var environment=new EnvironmentPerception(level.dimension().identifier().toString(),time,weather,level.getLightEngine().getRawBrightness(origin,0),biome,(time%24000)<12000,biomeValue.getBaseTemperature(),0f);
        return new PerceptionFrame(new AgentPerception(1,agent.id().toString(),agent.name(),agent.epoch(),capabilities,self,environment,entities,blocks,items,recent,candidates),Map.copyOf(offered));
    }
    private List<ObservedEntity> observeEntities(AgentRecord observer,GoalLessVillager body) { List<Entity> raw=body.level().getEntities(body,body.getBoundingBox().inflate(ENTITY_RADIUS),entity->entity!=body&&!(entity instanceof ItemEntity)&&visible(body,entity)); raw.sort(neutral(observer,entity->entity.getUUID().hashCode())); List<ObservedEntity> result=new ArrayList<>(); for(Entity entity:raw) { if(result.size()>=MAX_ENTITIES) break; Vec3 relative=entity.position().subtract(body.position()); AgentRegistry ignored=null; var record=registry.findByEmbodiment(entity.getUUID()); EmergentIdentity identity=record.map(value->new EmergentIdentity(value.id().toString(),value.name())).orElse(null); result.add(new ObservedEntity("entity:"+entity.getUUID(),BuiltInRegistries.ENTITY_TYPE.getKey(entity.getType()).toString(),position(relative),Math.sqrt(entity.distanceToSqr(body)),entity.getCustomName()==null?null:entity.getCustomName().getString(),entity.isAlive(),identity,entity.isOnFire(),entity instanceof Villager villager?villager.isBaby():null)); } return result; }
    private List<ObservedItem> observeItems(GoalLessVillager body) { List<ItemEntity> raw=body.level().getEntities(net.minecraft.world.level.entity.EntityTypeTest.forClass(ItemEntity.class),body.getBoundingBox().inflate(ENTITY_RADIUS),item->!item.isRemoved()&&visible(body,item)); raw.sort(Comparator.comparingDouble(item->item.distanceToSqr(body))); List<ObservedItem> result=new ArrayList<>(); for(ItemEntity item:raw) { if(result.size()>=MAX_ITEMS) break; var stack=item.getItem(); result.add(new ObservedItem("item:"+item.getUUID(),BuiltInRegistries.ITEM.getKey(stack.getItem()).toString(),stack.getCount(),position(item.position().subtract(body.position())),Math.sqrt(item.distanceToSqr(body)))); } return result; }
    private List<ObservedBlock> observeBlocks(AgentRecord agent,GoalLessVillager body) { var level=body.level(); BlockPos center=body.blockPosition(); List<ObservedBlock> found=new ArrayList<>(); for(BlockPos pos:BlockPos.betweenClosed(center.offset(-BLOCK_RADIUS,-4,-BLOCK_RADIUS),center.offset(BLOCK_RADIUS,4,BLOCK_RADIUS))) { if(pos.distSqr(center)>BLOCK_RADIUS*BLOCK_RADIUS) continue; BlockState state=level.getBlockState(pos); if(state.isAir()||!visible(body,pos)) continue; float hardness=state.getDestroySpeed(level,pos); Vec3 relative=Vec3.atCenterOf(pos).subtract(body.position()); found.add(new ObservedBlock("block:"+pos.getX()+":"+pos.getY()+":"+pos.getZ(),BuiltInRegistries.BLOCK.getKey(state.getBlock()).toString(),position(relative),relative.length(),hardness,hardness>=0,state.isSolid(),!level.getFluidState(pos).isEmpty(),new BlockPosition(pos.getX(),pos.getY(),pos.getZ()))); } found.sort(neutral(agent,block->block.id().hashCode())); return found.size()>MAX_BLOCKS?List.copyOf(found.subList(0,MAX_BLOCKS)):found; }
    private static boolean visible(GoalLessVillager body,Entity target) { return !(target instanceof LivingEntity living)||body.hasLineOfSight(living)||rayVisible(body,target.position()); }
    private static boolean visible(GoalLessVillager body,BlockPos target) { return rayVisible(body,Vec3.atCenterOf(target)); }
    private static boolean rayVisible(GoalLessVillager body,Vec3 target) { BlockHitResult hit=body.level().clip(new ClipContext(body.getEyePosition(),target,ClipContext.Block.COLLIDER,ClipContext.Fluid.NONE,body)); return hit.getType()==net.minecraft.world.phys.HitResult.Type.MISS||hit.getLocation().distanceToSqr(target)<1.0; }
    private static Position position(Vec3 value) { return new Position(value.x,value.y,value.z); }
    private static void add(List<ActionCandidate> candidates,Map<String,OfferedAction> offered,ActionCandidate candidate,OfferedAction action) { candidates.add(candidate); offered.put(candidate.id(),action); }
    private static <T> Comparator<T> neutral(AgentRecord agent,java.util.function.ToIntFunction<T> hash) { int seed=Objects.hash(agent.id(),agent.epoch()); return Comparator.comparingInt(value->Integer.rotateLeft(hash.applyAsInt(value)^seed,13)); }
}
