package nl.noscapect.emergentcraft.perception;

import nl.noscapect.emergentcraft.*;
import nl.noscapect.emergentcraft.actions.OfferedAction;
import nl.noscapect.emergentcraft.actions.RecipePlanner;
import net.minecraft.core.BlockPos;
import net.minecraft.core.component.DataComponents;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.entity.npc.villager.Villager;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.ClipContext;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.state.BlockState;
import net.minecraft.world.phys.AABB;
import net.minecraft.world.phys.BlockHitResult;
import net.minecraft.world.phys.Vec3;
import java.util.*;
import static nl.noscapect.emergentcraft.perception.PerceptionModels.*;

/** Bounded local, LOS-filtered observations and neutral affordance generation. */
public final class PerceptionBuilder {
    private static final int ENTITY_RADIUS=14, BLOCK_RADIUS=7, MAX_ENTITIES=16, MAX_BLOCKS=32, MAX_ITEMS=16, MAX_CANDIDATES=40;
    private final AgentRegistry registry; private final AgentInventoryStore inventory; private final AgentMetabolismStore metabolism;
    private record CandidateOffer(ActionCandidate candidate,OfferedAction action) { }
    public PerceptionBuilder(AgentRegistry registry,AgentInventoryStore inventory,AgentMetabolismStore metabolism) { this.registry=registry; this.inventory=inventory; this.metabolism=metabolism; }
    public PerceptionFrame build(AgentRecord agent,GoalLessVillager body,List<RecentEvent> recent) {
        var level=(net.minecraft.server.level.ServerLevel)body.level(); long time=level.getOverworldClockTime(),tick=level.getServer().getTickCount(); BlockPos origin=body.blockPosition(); List<ObservedEntity> entities=observeEntities(agent,body); List<ObservedItem> items=observeItems(body); List<ObservedBlock> blocks=observeBlocks(agent,body); Map<String,List<CandidateOffer>> buckets=new LinkedHashMap<>();
        offer(buckets,"wait",new ActionCandidate("wait:"+agent.epoch(),"WAIT","Wait and observe.",null,null),new OfferedAction("wait:"+agent.epoch(),OfferedAction.Kind.WAIT,null,null,null,null));
        int travel=0; for(int[] offset:new int[][]{{6,0},{-6,0},{0,6},{0,-6},{16,0},{-16,0},{0,16},{0,-16},{32,0},{-32,0},{0,32},{0,-32}}) { BlockPos destination=origin.offset(offset[0],0,offset[1]); var path=body.getNavigation().createPath(destination,0); if(path!=null&&path.canReach()) { String id="travel:"+agent.epoch()+":"+travel++; offer(buckets,"travel",new ActionCandidate(id,"TRAVEL","Travel to a reachable local location.",null,new BlockPosition(destination.getX(),destination.getY(),destination.getZ())),new OfferedAction(id,OfferedAction.Kind.TRAVEL,Vec3.atCenterOf(destination),null,destination,null)); } }
        for(ObservedEntity entity:entities) { UUID entityId=UUID.fromString(entity.id().substring("entity:".length())); String approach="approach:"+agent.epoch()+":"+entity.id(); offer(buckets,"entities",new ActionCandidate(approach,"APPROACH_ENTITY","Approach "+entity.type()+".",entity.id(),null),new OfferedAction(approach,OfferedAction.Kind.APPROACH_ENTITY,null,entityId,null,entity.type())); Entity live=level.getEntity(entityId); if(live instanceof LivingEntity&&live.isAlive()) { String engage="engage:"+agent.epoch()+":"+entity.id(); offer(buckets,"entities",new ActionCandidate(engage,"ENGAGE","Engage "+entity.type()+".",entity.id(),null),new OfferedAction(engage,OfferedAction.Kind.ENGAGE,null,entityId,null,entity.type())); } if(entity.emergentCraft()!=null) { String speak="speak:"+agent.epoch()+":"+entity.id(); offer(buckets,"social",new ActionCandidate(speak,"SPEAK","Speak to "+entity.name()+".",entity.id(),null),new OfferedAction(speak,OfferedAction.Kind.SPEAK,null,entityId,null,entity.type())); } }
        for(ObservedItem item:items) { UUID itemId=UUID.fromString(item.id().substring("item:".length())); String action="pickup:"+agent.epoch()+":"+item.id(); offer(buckets,"resources",new ActionCandidate(action,"PICK_UP_ITEM","Approach and pick up "+item.item()+".",item.id(),null),new OfferedAction(action,OfferedAction.Kind.PICK_UP_ITEM,null,itemId,null,item.item())); }
        for(ObservedBlock block:blocks) { BlockPos pos=new BlockPos(block.position().x(),block.position().y(),block.position().z()); String approach="approach:"+agent.epoch()+":"+block.id(); offer(buckets,"resources",new ActionCandidate(approach,"APPROACH_BLOCK","Approach "+block.type()+".",block.id(),block.position()),new OfferedAction(approach,OfferedAction.Kind.APPROACH_BLOCK,Vec3.atCenterOf(pos),null,pos,block.type())); if(block.breakable()) { String acquire="acquire:"+agent.epoch()+":"+block.id(); offer(buckets,"resources",new ActionCandidate(acquire,"ACQUIRE_BLOCK","Acquire "+block.type()+".",block.id(),block.position()),new OfferedAction(acquire,OfferedAction.Kind.ACQUIRE_BLOCK,Vec3.atCenterOf(pos),null,pos,block.type())); } }
        for(AgentInventoryStore.Entry entry:inventory.entries(agent.id())) { Item item=BuiltInRegistries.ITEM.getValue(Identifier.tryParse(entry.item())); if(item==null) continue; if(new ItemStack(item).get(DataComponents.FOOD)!=null) { String id="eat:"+agent.epoch()+":"+entry.item(); offer(buckets,"inventory",new ActionCandidate(id,"EAT_ITEM","Eat "+entry.item()+".",entry.item(),null),new OfferedAction(id,OfferedAction.Kind.EAT_ITEM,null,null,null,entry.item())); } EquipmentSlot slot=body.getEquipmentSlotForItem(new ItemStack(item)); String equip="equip:"+agent.epoch()+":"+entry.item(); offer(buckets,"inventory",new ActionCandidate(equip,"EQUIP_ITEM","Equip "+entry.item()+".",entry.item(),null),new OfferedAction(equip,OfferedAction.Kind.EQUIP_ITEM,null,null,null,entry.item()+":"+slot.name())); if(item instanceof BlockItem) for(BlockPos place:placementTargets(level,origin,2)) { String id="place:"+agent.epoch()+":"+entry.item()+":"+place.asLong(); offer(buckets,"placement",new ActionCandidate(id,"PLACE_BLOCK","Place "+entry.item()+" nearby.",entry.item(),new BlockPosition(place.getX(),place.getY(),place.getZ())),new OfferedAction(id,OfferedAction.Kind.PLACE_BLOCK,Vec3.atCenterOf(place),null,place,entry.item())); } }
        for(RecipePlanner.Plan plan:RecipePlanner.craftable(level,inventory,agent.id(),6)) { String id="craft:"+agent.epoch()+":"+plan.recipeId().replace('/','_'); offer(buckets,"crafting",new ActionCandidate(id,"CRAFT","Craft "+plan.outputId()+".",plan.outputId(),null),new OfferedAction(id,OfferedAction.Kind.CRAFT,null,null,null,plan.recipeId())); }
        if(inventory.entries(agent.id()).stream().anyMatch(entry->BuiltInRegistries.ITEM.getValue(Identifier.tryParse(entry.item())) instanceof BlockItem)) { String id="build:"+agent.epoch(); offer(buckets,"placement",new ActionCandidate(id,"BUILD_PLAN","Build a small supplied placement plan.",null,null),new OfferedAction(id,OfferedAction.Kind.BUILD_PLAN,null,null,null,null)); }
        List<ActionCandidate> candidates=new ArrayList<>(); Map<String,OfferedAction> offered=new LinkedHashMap<>(); int round=0; List<List<CandidateOffer>> groups=new ArrayList<>(buckets.values()); while(candidates.size()<MAX_CANDIDATES) { boolean added=false; for(List<CandidateOffer> group:groups) if(round<group.size()&&candidates.size()<MAX_CANDIDATES) { CandidateOffer next=group.get(round); candidates.add(next.candidate()); offered.put(next.candidate().id(),next.action()); added=true; } if(!added) break; round++; }
        AgentMetabolismStore.State hunger=metabolism.state(agent.id(),tick); AgentInventoryStore.Equipment equipped=inventory.equipment(agent.id()); var capabilities=new Capabilities(true,true,true,true,true,true,true,true,true,true); var self=new SelfPerception(position(body.position()),body.getHealth(),body.getMaxHealth(),body.isAlive(),body.onGround(),body.isInWater(),body.isOnFire(),body.getAirSupply(),(float)Math.max(0d,body.fallDistance),body.getActiveEffects().stream().map(effect->BuiltInRegistries.MOB_EFFECT.getKey(effect.getEffect().value()).toString()).limit(16).toList(),inventory.entries(agent.id()).stream().map(entry->new InventoryEntry(entry.item(),entry.count())).toList(),new Hunger(hunger.hunger(),20,hunger.saturation(),hunger.starving()),new Equipment(equipped.mainHand(),equipped.offHand(),equipped.head(),equipped.chest(),equipped.legs(),equipped.feet()));
        String biome=level.getBiome(origin).unwrapKey().map(key->key.identifier().toString()).orElse("minecraft:unknown"); var biomeValue=level.getBiome(origin).value(); String weather=level.isThundering()?"thunder":level.isRaining()?"rain":"clear"; var environment=new EnvironmentPerception(level.dimension().identifier().toString(),time,weather,level.getLightEngine().getRawBrightness(origin,0),biome,(time%24000)<12000,biomeValue.getBaseTemperature(),0f);
        return new PerceptionFrame(new AgentPerception(1,agent.id().toString(),agent.name(),agent.epoch(),capabilities,self,environment,entities,blocks,items,recent,candidates),Map.copyOf(offered));
    }
    private List<ObservedEntity> observeEntities(AgentRecord observer,GoalLessVillager body) { List<Entity> raw=body.level().getEntities(body,body.getBoundingBox().inflate(ENTITY_RADIUS),entity->entity!=body&&!(entity instanceof ItemEntity)&&visible(body,entity)); raw.sort(neutral(observer,entity->entity.getUUID().hashCode())); List<ObservedEntity> result=new ArrayList<>(); for(Entity entity:raw) { if(result.size()>=MAX_ENTITIES) break; Vec3 relative=entity.position().subtract(body.position()); AgentRegistry ignored=null; var record=registry.findByEmbodiment(entity.getUUID()); EmergentIdentity identity=record.map(value->new EmergentIdentity(value.id().toString(),value.name())).orElse(null); result.add(new ObservedEntity("entity:"+entity.getUUID(),BuiltInRegistries.ENTITY_TYPE.getKey(entity.getType()).toString(),position(relative),Math.sqrt(entity.distanceToSqr(body)),entity.getCustomName()==null?null:entity.getCustomName().getString(),entity.isAlive(),identity,entity.isOnFire(),entity instanceof Villager villager?villager.isBaby():null)); } return result; }
    private List<ObservedItem> observeItems(GoalLessVillager body) { List<ItemEntity> raw=body.level().getEntities(net.minecraft.world.level.entity.EntityTypeTest.forClass(ItemEntity.class),body.getBoundingBox().inflate(ENTITY_RADIUS),item->!item.isRemoved()&&visible(body,item)); raw.sort(Comparator.comparingDouble(item->item.distanceToSqr(body))); List<ObservedItem> result=new ArrayList<>(); for(ItemEntity item:raw) { if(result.size()>=MAX_ITEMS) break; var stack=item.getItem(); result.add(new ObservedItem("item:"+item.getUUID(),BuiltInRegistries.ITEM.getKey(stack.getItem()).toString(),stack.getCount(),position(item.position().subtract(body.position())),Math.sqrt(item.distanceToSqr(body)))); } return result; }
    private List<ObservedBlock> observeBlocks(AgentRecord agent,GoalLessVillager body) { var level=body.level(); BlockPos center=body.blockPosition(); List<ObservedBlock> found=new ArrayList<>(); for(BlockPos pos:BlockPos.betweenClosed(center.offset(-BLOCK_RADIUS,-4,-BLOCK_RADIUS),center.offset(BLOCK_RADIUS,4,BLOCK_RADIUS))) { if(pos.distSqr(center)>BLOCK_RADIUS*BLOCK_RADIUS) continue; BlockState state=level.getBlockState(pos); if(state.isAir()||!visible(body,pos)) continue; float hardness=state.getDestroySpeed(level,pos); Vec3 relative=Vec3.atCenterOf(pos).subtract(body.position()); found.add(new ObservedBlock("block:"+pos.getX()+":"+pos.getY()+":"+pos.getZ(),BuiltInRegistries.BLOCK.getKey(state.getBlock()).toString(),position(relative),relative.length(),hardness,hardness>=0,state.isSolid(),!level.getFluidState(pos).isEmpty(),new BlockPosition(pos.getX(),pos.getY(),pos.getZ()))); } found.sort(neutral(agent,block->block.id().hashCode())); return found.size()>MAX_BLOCKS?List.copyOf(found.subList(0,MAX_BLOCKS)):found; }
    private static boolean visible(GoalLessVillager body,Entity target) { return !(target instanceof LivingEntity living)||body.hasLineOfSight(living)||rayVisible(body,target.position()); }
    private static boolean visible(GoalLessVillager body,BlockPos target) { return rayVisible(body,Vec3.atCenterOf(target)); }
    private static boolean rayVisible(GoalLessVillager body,Vec3 target) { BlockHitResult hit=body.level().clip(new ClipContext(body.getEyePosition(),target,ClipContext.Block.COLLIDER,ClipContext.Fluid.NONE,body)); return hit.getType()==net.minecraft.world.phys.HitResult.Type.MISS||hit.getLocation().distanceToSqr(target)<1.0; }
    private static Position position(Vec3 value) { return new Position(value.x,value.y,value.z); }
    private static List<BlockPos> placementTargets(net.minecraft.server.level.ServerLevel level,BlockPos origin,int limit) { List<BlockPos> result=new ArrayList<>(); for(int[] offset:new int[][]{{1,0},{-1,0},{0,1},{0,-1},{2,0},{0,2},{-2,0},{0,-2}}) { BlockPos pos=origin.offset(offset[0],0,offset[1]); if(level.getBlockState(pos).isAir()&&level.getBlockState(pos.below()).isSolid()) { result.add(pos); if(result.size()>=limit) break; } } return result; }
    private static void offer(Map<String,List<CandidateOffer>> buckets,String category,ActionCandidate candidate,OfferedAction action) { buckets.computeIfAbsent(category,ignored->new ArrayList<>()).add(new CandidateOffer(candidate,action)); }
    private static void add(List<ActionCandidate> candidates,Map<String,OfferedAction> offered,ActionCandidate candidate,OfferedAction action) { candidates.add(candidate); offered.put(candidate.id(),action); }
    private static <T> Comparator<T> neutral(AgentRecord agent,java.util.function.ToIntFunction<T> hash) { int seed=Objects.hash(agent.id(),agent.epoch()); return Comparator.comparingInt(value->Integer.rotateLeft(hash.applyAsInt(value)^seed,13)); }
}
